package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.bluetooth.*;import android.bluetooth.le.*;import android.content.*;import android.os.*;import android.util.Log;import java.io.*;import java.util.*;

final class BleRuntime{
 static final UUID SERVICE=UUID.fromString("b11c0001-7a2b-4c3d-9e0f-112233445566"),RX=UUID.fromString("b11c0002-7a2b-4c3d-9e0f-112233445566"),TX=UUID.fromString("b11c0003-7a2b-4c3d-9e0f-112233445566");static String token;static long expires;static BluetoothGattServer gatt;static BluetoothLeAdvertiser advertiser;static BluetoothGattCharacteristic tx;static byte[]reply;static File result;static AdvertiseCallback advertiseCallback;static AdvertiseSettings settings;static AdvertiseData adData;
 static synchronized void start(Context c,Intent i)throws Exception{if(token!=null)throw new Exception("ble_active");String t=i.getStringExtra("run_token");ProbeCore.requireToken(t);long e=i.getLongExtra("expires_elapsed_ms",0),now=SystemClock.elapsedRealtime();if(e<=now||e-now>120000)throw new Exception("ble_expiry");BluetoothManager manager=(BluetoothManager)c.getSystemService(Context.BLUETOOTH_SERVICE);BluetoothAdapter adapter=manager.getAdapter();if(adapter==null||!adapter.isEnabled())throw new Exception("bluetooth_unavailable");token=t;expires=e;reply=CapabilityProvider.bleReady(t);if(reply==null||reply.length!=BleProtocol.FRAME||reply[1]!=(byte)BleProtocol.READY)throw new Exception("ready_reply");result=new File(c.getFilesDir(),"ble-"+t+".json");gatt=manager.openGattServer(c,CALLBACK);BluetoothGattService service=new BluetoothGattService(SERVICE,BluetoothGattService.SERVICE_TYPE_PRIMARY);BluetoothGattCharacteristic rx=new BluetoothGattCharacteristic(RX,BluetoothGattCharacteristic.PROPERTY_WRITE,BluetoothGattCharacteristic.PERMISSION_WRITE);tx=new BluetoothGattCharacteristic(TX,BluetoothGattCharacteristic.PROPERTY_READ|BluetoothGattCharacteristic.PROPERTY_NOTIFY,BluetoothGattCharacteristic.PERMISSION_READ);tx.addDescriptor(new BluetoothGattDescriptor(UUID.fromString("00002902-0000-1000-8000-00805f9b34fb"),BluetoothGattDescriptor.PERMISSION_READ|BluetoothGattDescriptor.PERMISSION_WRITE));service.addCharacteristic(rx);service.addCharacteristic(tx);advertiser=adapter.getBluetoothLeAdvertiser();if(advertiser==null)throw new Exception("advertiser");settings=new AdvertiseSettings.Builder().setConnectable(true).setAdvertiseMode(AdvertiseSettings.ADVERTISE_MODE_LOW_LATENCY).setTimeout(0).build();adData=new AdvertiseData.Builder().addServiceUuid(new ParcelUuid(SERVICE)).setIncludeDeviceName(false).build();advertiseCallback=new AdvertiseCallback(){public void onStartSuccess(AdvertiseSettings s){write("ready",0,BleProtocol.READY,null);Log.i(CapabilityRuntime.TAG,"BLE_READY token="+t);}public void onStartFailure(int code){write("blocked",-1,-1,"advertise_"+code);Log.e(CapabilityRuntime.TAG,"BLE_BLOCKED code="+code);stop(t);}};if(!gatt.addService(service))throw new Exception("gatt_service");new Thread(()->{try{Thread.sleep(Math.max(1,e-SystemClock.elapsedRealtime()));}catch(InterruptedException ignored){}stop(t);},"rqsc-ble-expiry").start();}
 static final BluetoothGattServerCallback CALLBACK=new BluetoothGattServerCallback(){public void onServiceAdded(int status,BluetoothGattService service){if(status!=BluetoothGatt.GATT_SUCCESS||!service.getUuid().equals(SERVICE)){write("blocked",-1,-1,"service_"+status);stop(token);return;}advertiser.startAdvertising(settings,adData,advertiseCallback);}public void onCharacteristicWriteRequest(BluetoothDevice d,int id,BluetoothGattCharacteristic c,boolean prepared,boolean responseNeeded,int offset,byte[]value){int status=BluetoothGatt.GATT_FAILURE;try{if(!c.getUuid().equals(RX)||prepared||offset!=0||value==null||value.length!=BleProtocol.FRAME||SystemClock.elapsedRealtime()>=expires)throw new Exception("write_shape");byte[]r=CapabilityProvider.bleExchange(token,value);if(r==null||r.length!=BleProtocol.FRAME)throw new Exception("reply_shape");synchronized(BleRuntime.class){reply=r.clone();tx.setValue(reply);}status=BluetoothGatt.GATT_SUCCESS;write("reply",BleProtocol.seq(r),r[1]&255,null);}catch(Throwable x){write("rejected",-1,-1,x.getClass().getName()+":"+x.getMessage());}if(responseNeeded&&gatt!=null)gatt.sendResponse(d,id,status,0,null);}public void onCharacteristicReadRequest(BluetoothDevice d,int id,int offset,BluetoothGattCharacteristic c){byte[]r; synchronized(BleRuntime.class){r=reply==null?null:reply.clone();}if(!c.getUuid().equals(TX)||r==null||offset<0||offset>r.length){gatt.sendResponse(d,id,BluetoothGatt.GATT_FAILURE,0,null);return;}gatt.sendResponse(d,id,BluetoothGatt.GATT_SUCCESS,offset,Arrays.copyOfRange(r,offset,r.length));}};
 static synchronized void onShellDeath(String t){if(t!=null&&t.equals(token))stop(t);}
 static synchronized void stop(String t){if(token==null||!token.equals(t))return;if(advertiser!=null&&advertiseCallback!=null)try{advertiser.stopAdvertising(advertiseCallback);}catch(Throwable ignored){}if(gatt!=null)try{gatt.close();}catch(Throwable ignored){}write("stopped",-1,-1,null);Log.i(CapabilityRuntime.TAG,"BLE_STOP token="+t);token=null;gatt=null;advertiser=null;advertiseCallback=null;reply=null;}
 static synchronized void write(String state,int seq,int outcome,String error){if(result==null)return;String s="{\"schema\":\"rusty.quest.shell_caps_ble.v1\",\"token\":"+ProbeCore.quote(token)+",\"state\":"+ProbeCore.quote(state)+",\"app_uid\":"+android.os.Process.myUid()+",\"app_pid\":"+android.os.Process.myPid()+",\"service_uuid\":"+ProbeCore.quote(SERVICE.toString())+",\"rx_uuid\":"+ProbeCore.quote(RX.toString())+",\"tx_uuid\":"+ProbeCore.quote(TX.toString())+",\"expires_elapsed_ms\":"+expires+",\"sequence\":"+seq+",\"outcome\":"+outcome+",\"error\":"+ProbeCore.quote(error)+"}";try(FileOutputStream o=new FileOutputStream(result)){o.write((s+"\n").getBytes("UTF-8"));o.getFD().sync();}catch(Exception x){Log.e(CapabilityRuntime.TAG,"ble_result",x);}}
}
