package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.content.*;import android.net.*;import android.os.*;import android.util.Log;import java.io.*;import java.net.*;import java.util.concurrent.*;

final class CapabilityRuntime{
 static final String TAG="RQShellCaps";static volatile String active;static volatile boolean resumed;static ExecutorService pool;static ServerSocket tcpServer;static LocalServerSocket udsServer;static final java.util.Set<java.io.Closeable> open=java.util.Collections.synchronizedSet(new java.util.HashSet<java.io.Closeable>());
 static synchronized void start(Context c,Intent i)throws Exception{if(active!=null)throw new Exception("already_active");String t=i.getStringExtra("run_token"),sn=i.getStringExtra("shell_uds_name");ProbeCore.requireToken(t);long expiry=i.getLongExtra("expires_elapsed_ms",0);if(expiry<=SystemClock.elapsedRealtime()||expiry-SystemClock.elapsedRealtime()>600000)throw new Exception("expiry");int tp=i.getIntExtra("shell_tcp_port",-1);if(tp<1||tp>65535||sn==null||!sn.equals("rqsc.shell."+t))throw new Exception("endpoint");active=t;pool=Executors.newFixedThreadPool(6);File f=new File(c.getFilesDir(),"capability-"+t+".json");tcpServer=new ServerSocket(0,1,InetAddress.getByName("127.0.0.1"));String an="rqsc.app."+t;udsServer=new LocalServerSocket(an);final ServerSocket tcp=tcpServer;final LocalServerSocket uds=udsServer;final String snapshot=AppSnapshot.capture(i.getIntExtra("shell_pid",-1));write(f,"{\"schema\":\"rusty.quest.shell_capabilities.v1\",\"token\":\""+t+"\",\"state\":\"ready\",\"app_uid\":"+android.os.Process.myUid()+",\"app_tcp_port\":"+tcp.getLocalPort()+",\"app_uds_name\":\""+an+"\",\"app_snapshot\":"+snapshot+"}");Log.i(TAG,"READY token="+t+" tcp="+tcp.getLocalPort()+" uds="+an);
  pool.submit(()->{Socket s=null;try{s=tcp.accept();open.add(s);ProbeCore.serve(s,t);log("shell_to_app_tcp_ok",null);}catch(Throwable e){log("shell_to_app_tcp",e);}finally{close(s);}});
  pool.submit(()->{LocalSocket s=null;try{s=uds.accept();open.add(s);Credentials p=s.getPeerCredentials();ProbeCore.serve(new LocalSocketAdapter(s),t);Log.i(TAG,"shell_to_app_uds_ok peer_uid="+p.getUid()+" peer_pid="+p.getPid());}catch(Throwable e){log("shell_to_app_uds",e);}finally{close(s);}});
  pool.submit(()->{String tcpResult,udsResult;try{Socket s=new Socket();open.add(s);try{s.connect(new InetSocketAddress("127.0.0.1",tp),3000);tcpResult=ProbeCore.client(s,t);}finally{close(s);}}catch(Throwable e){tcpResult=err(e);}try{LocalSocket s=new LocalSocket();open.add(s);try{s.connect(new LocalSocketAddress(sn,LocalSocketAddress.Namespace.ABSTRACT));Credentials p=s.getPeerCredentials();udsResult=ProbeCore.client(new LocalSocketAdapter(s),t).replace("}",",\"peer_uid\":"+p.getUid()+",\"peer_pid\":"+p.getPid()+"}");}finally{close(s);}}catch(Throwable e){udsResult=err(e);}write(f,"{\"schema\":\"rusty.quest.shell_capabilities.v1\",\"token\":\""+t+"\",\"state\":\"app_probes_complete\",\"app_uid\":"+android.os.Process.myUid()+",\"app_tcp_port\":"+tcp.getLocalPort()+",\"app_uds_name\":\""+an+"\",\"app_to_shell_tcp\":"+tcpResult+",\"app_to_shell_uds\":"+udsResult+",\"app_snapshot\":"+snapshot+"}");Log.i(TAG,"APP_PROBES_COMPLETE token="+t);});
  pool.submit(()->{try{long d=expiry-SystemClock.elapsedRealtime();if(d>0)Thread.sleep(d);}catch(InterruptedException ignored){}stop(t);});
 }
 static synchronized void stop(String t){if(active==null||!active.equals(t))return;active=null;try{if(tcpServer!=null)tcpServer.close();}catch(Exception ignored){}try{if(udsServer!=null)udsServer.close();}catch(Exception ignored){}tcpServer=null;udsServer=null;synchronized(open){for(java.io.Closeable c:open)try{c.close();}catch(Exception ignored){}open.clear();}if(pool!=null)pool.shutdownNow();pool=null;Log.i(TAG,"STOP token="+t);}
 static void close(java.io.Closeable c){if(c!=null){open.remove(c);try{c.close();}catch(Exception ignored){}}}
 static String err(Throwable e){return "{\"ok\":false,\"error\":"+ProbeCore.quote(e.getClass().getName()+":"+e.getMessage())+"}";}
 static void write(File f,String s){try{FileOutputStream o=new FileOutputStream(f);o.write(s.getBytes("UTF-8"));o.write('\n');o.getFD().sync();o.close();}catch(Exception e){log("write",e);}}
 static void log(String at,Throwable e){Log.e(TAG,at+(e==null?"":" error="+e.getClass().getName()+":"+e.getMessage()));}
 static final class LocalSocketAdapter extends Socket{final LocalSocket s;LocalSocketAdapter(LocalSocket x){s=x;}public InputStream getInputStream()throws IOException{return s.getInputStream();}public OutputStream getOutputStream()throws IOException{return s.getOutputStream();}public synchronized void close()throws IOException{s.close();}public void setSoTimeout(int n)throws SocketException{try{s.setSoTimeout(n);}catch(IOException e){throw new SocketException(e.toString());}}}
}
