package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.net.wifi.WifiManager;
import android.os.*;
import android.provider.Settings;
import java.io.File;
import java.util.concurrent.atomic.AtomicBoolean;

public final class CapabilityProvider extends ContentProvider {
    private static final LeaseRuntime LEASE=new LeaseRuntime();
    private static final AtomicBoolean POST_DROP_RUNNING=new AtomicBoolean();
    public boolean onCreate(){return true;} public String getType(Uri u){return null;} public Cursor query(Uri u,String[]p,String q,String[]a,String s){return null;} public Uri insert(Uri u,ContentValues v){return null;} public int delete(Uri u,String q,String[]a){return 0;} public int update(Uri u,ContentValues v,String q,String[]a){return 0;}
    @Override public Bundle call(String method,String token,Bundle extras){Bundle out=new Bundle();int caller=Binder.getCallingUid(),self=android.os.Process.myUid();out.putInt("provider_process_uid",self);out.putInt("provider_calling_uid",caller);try{ProbeCore.requireToken(token);requireShell(caller);int expected=extras.getInt("expected_app_uid",-1);if(expected!=self||expected<10000)throw new SecurityException("app_uid_mismatch");if("binder_handoff".equals(method))return oneShot(token,extras,out);if("lease_open".equals(method))return LEASE.open(token,extras,out);if("wifi_lease_open".equals(method))return LEASE.wifiOpen(token,extras,out);if("lease_status".equals(method))return LEASE.status(token,out);if("lease_stop".equals(method))return LEASE.stop(token,out);if("lease_negative_callback".equals(method))return LEASE.negative(token,out);throw new IllegalArgumentException("method");}catch(Throwable e){out.putBoolean("ok",false);out.putString("error",e.getClass().getName()+":"+e.getMessage());return out;}}
    static byte[] bleExchange(String token,byte[]frame)throws Exception{return LEASE.exchange(token,frame);}
    static byte[] bleReady(String token)throws Exception{return LEASE.ready(token);}
    static void startPostDropProbe(Context context,String token,long delayMs)throws Exception{
        ProbeCore.requireToken(token);if(delayMs<0||delayMs>30000)throw new IllegalArgumentException("post_drop_delay_ms");
        if(!POST_DROP_RUNNING.compareAndSet(false,true))throw new IllegalStateException("post_drop_probe_active");
        final File result=new File(context.getFilesDir(),"post-drop-"+token+".json");
        CapabilityRuntime.write(result,"{\"schema\":\"rusty.quest.shell_caps_post_drop_probe.v1\",\"state\":\"scheduled\",\"token\":"+ProbeCore.quote(token)+",\"app_uid\":"+android.os.Process.myUid()+",\"app_pid\":"+android.os.Process.myPid()+",\"scheduled_elapsed_ms\":"+SystemClock.elapsedRealtime()+",\"delay_ms\":"+delayMs+"}");
        new Thread(()->{long started=0;try{if(delayMs>0)Thread.sleep(delayMs);started=SystemClock.elapsedRealtime();CapabilityRuntime.write(result,LEASE.postDrop(token,context,started));}catch(Throwable e){CapabilityRuntime.write(result,"{\"schema\":\"rusty.quest.shell_caps_post_drop_probe.v1\",\"state\":\"failed\",\"token\":"+ProbeCore.quote(token)+",\"app_uid\":"+android.os.Process.myUid()+",\"app_pid\":"+android.os.Process.myPid()+",\"started_elapsed_ms\":"+started+",\"completed_elapsed_ms\":"+SystemClock.elapsedRealtime()+",\"error_type\":"+ProbeCore.quote(e.getClass().getName())+"}");}finally{POST_DROP_RUNNING.set(false);}},"rqsc-post-drop-probe").start();
    }
    private static Bundle oneShot(String token,Bundle extras,Bundle out)throws Exception{IBinder remote=extras.getBinder("shell_binder");if(remote==null)throw new Exception("binder_missing");Parcel data=Parcel.obtain(),reply=Parcel.obtain();try{data.writeInterfaceToken("rusty.quest.shell.capabilities");data.writeString(token);remote.transact(1,data,reply,0);reply.readException();out.putString("echo",reply.readString());out.putInt("shell_process_uid",reply.readInt());out.putInt("shell_observed_callback_uid",reply.readInt());out.putBoolean("ok",true);return out;}finally{data.recycle();reply.recycle();}}

    static final class LeaseRuntime {
        private IBinder shell,app; private String token; private int shellPid=-1; private final AtomicBoolean shellDead=new AtomicBoolean();
        synchronized Bundle open(String t,Bundle extras,Bundle out)throws Exception{if(shell!=null&&shell.isBinderAlive())throw new Exception("lease_active");shellPid=extras.getInt("shell_pid",-1);out.putString("app_snapshot",AppSnapshot.capture(shellPid));IBinder b=extras.getBinder("shell_binder");if(b==null)throw new Exception("binder_missing");token=t;shell=b;shellDead.set(false);shell.linkToDeath(()->shellDead.set(true),0);app=new Binder();identify(t);for(int size:new int[]{BinderProtocol.SMALL,BinderProtocol.LARGE}){out.putString("app_to_shell_"+size,appToShell(size));out.putString("shell_to_app_"+size,shellToApp(size));}out.putBinder("app_binder",app);out.putBoolean("ok",true);return out;}
        synchronized Bundle wifiOpen(String t,Bundle extras,Bundle out)throws Exception{if(shell!=null&&shell.isBinderAlive())throw new Exception("lease_active");IBinder b=extras.getBinder("shell_binder");if(b==null)throw new Exception("binder_missing");token=t;shell=b;shellDead.set(false);shell.linkToDeath(()->{shellDead.set(true);BleRuntime.onShellDeath(t);},0);app=new Binder();identify(t);out.putBinder("app_binder",app);out.putBoolean("ok",true);return out;}
        synchronized byte[] exchange(String t,byte[]frame)throws Exception{require(t);Parcel d=Parcel.obtain(),r=Parcel.obtain();try{d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(t);d.writeByteArray(frame);shell.transact(BinderProtocol.BLE_FRAME,d,r,0);r.readException();return r.createByteArray();}finally{d.recycle();r.recycle();}}
        synchronized byte[] ready(String t)throws Exception{require(t);Parcel d=Parcel.obtain(),r=Parcel.obtain();try{d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(t);shell.transact(BinderProtocol.BLE_READY,d,r,0);r.readException();return r.createByteArray();}finally{d.recycle();r.recycle();}}
        synchronized Bundle status(String t,Bundle out)throws Exception{require(t);out.putBoolean("shell_binder_alive",shell.isBinderAlive());out.putBoolean("shell_death_observed",shellDead.get());out.putBoolean("activity_resumed",CapabilityRuntime.resumed);Parcel d=Parcel.obtain(),r=Parcel.obtain();try{d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(t);shell.transact(BinderProtocol.STATUS,d,r,0);r.readException();out.putBoolean("shell_reported_alive",r.readInt()!=0);out.putInt("shell_callback_caller_uid",r.readInt());}finally{d.recycle();r.recycle();}out.putBoolean("ok",true);return out;}
        synchronized Bundle stop(String t,Bundle out)throws Exception{require(t);simple(BinderProtocol.STOP,t);out.putBoolean("stop_sent",true);out.putBoolean("ok",true);return out;}
        synchronized Bundle negative(String t,Bundle out)throws Exception{require(t);String wrong="00000000000000000000000000000000".equals(t)?"11111111111111111111111111111111":"00000000000000000000000000000000";boolean rejected=false;try{identify(wrong);}catch(Throwable e){rejected=true;out.putString("negative_error",e.getClass().getName()+":"+e.getMessage());}if(!rejected)throw new SecurityException("wrong_token_accepted");out.putBoolean("wrong_token_rejected",true);out.putBoolean("ok",true);return out;}
        synchronized String postDrop(String t,Context context,long started)throws Exception{require(t);String statusResult;try{Bundle out=new Bundle();status(t,out);statusResult="{\"ok\":true,\"shell_binder_alive\":"+out.getBoolean("shell_binder_alive",false)+",\"shell_death_observed\":"+out.getBoolean("shell_death_observed",false)+",\"shell_reported_alive\":"+out.getBoolean("shell_reported_alive",false)+",\"shell_callback_caller_uid\":"+out.getInt("shell_callback_caller_uid",-1)+"}";}catch(Throwable e){statusResult="{\"ok\":false,\"error_type\":"+ProbeCore.quote(e.getClass().getName())+"}";}StringBuilder r=new StringBuilder("{\"schema\":\"rusty.quest.shell_caps_post_drop_probe.v1\",\"state\":\"complete\",\"token\":").append(ProbeCore.quote(t)).append(",\"app_uid\":").append(android.os.Process.myUid()).append(",\"app_pid\":").append(android.os.Process.myPid()).append(",\"stored_shell_pid\":").append(shellPid).append(",\"started_elapsed_ms\":").append(started).append(",\"status\":").append(statusResult).append(",\"local_radio\":").append(localRadio(context));for(int size:new int[]{BinderProtocol.SMALL,BinderProtocol.LARGE}){r.append(",\"app_to_shell_").append(size).append("\":").append(probePipe(true,size)).append(",\"shell_to_app_").append(size).append("\":").append(probePipe(false,size));}return r.append(",\"completed_elapsed_ms\":").append(SystemClock.elapsedRealtime()).append('}').toString();}
        private String localRadio(Context context){try{int adb=Settings.Global.getInt(context.getContentResolver(),"adb_wifi_enabled",-1);WifiManager wifi=(WifiManager)context.getSystemService(Context.WIFI_SERVICE);return "{\"ok\":true,\"adb_wifi_enabled\":"+adb+",\"wifi_enabled\":"+(wifi!=null&&wifi.isWifiEnabled())+"}";}catch(Throwable e){return "{\"ok\":false,\"error_type\":"+ProbeCore.quote(e.getClass().getName())+"}";}}
        private String probePipe(boolean appToShell,int size){try{String hash=appToShell?appToShell(size):shellToApp(size);return "{\"ok\":true,\"sha256\":"+ProbeCore.quote(hash)+"}";}catch(Throwable e){return "{\"ok\":false,\"error_type\":"+ProbeCore.quote(e.getClass().getName())+"}";}}
        private void require(String t)throws Exception{if(shell==null||token==null||!token.equals(t))throw new Exception("lease_missing");}
        private void identify(String t)throws Exception{simple(BinderProtocol.IDENTIFY,t);}
        private void simple(int code,String t)throws Exception{Parcel d=Parcel.obtain(),r=Parcel.obtain();try{d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(t);shell.transact(code,d,r,0);r.readException();}finally{d.recycle();r.recycle();}}
        private String appToShell(int size)throws Exception{final ParcelFileDescriptor[]p=ParcelFileDescriptor.createPipe();final java.util.concurrent.atomic.AtomicReference<Throwable>failure=new java.util.concurrent.atomic.AtomicReference<>();Thread w=new Thread(()->{try{BinderProtocol.writePattern(p[1],size);}catch(Throwable x){failure.set(x);}},"rqsc-app-writer");Parcel d=Parcel.obtain(),r=Parcel.obtain();try{w.start();d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(token);d.writeInt(size);p[0].writeToParcel(d,0);shell.transact(BinderProtocol.APP_TO_SHELL_FD,d,r,0);r.readException();String hash=r.readString();w.join(30000);if(w.isAlive())throw new Exception("app_writer_timeout");if(failure.get()!=null)throw new Exception("app_writer_failed",failure.get());return hash;}finally{try{p[0].close();}catch(Exception ignored){}try{p[1].close();}catch(Exception ignored){}d.recycle();r.recycle();}}
        private String shellToApp(int size)throws Exception{Parcel d=Parcel.obtain(),r=Parcel.obtain();ParcelFileDescriptor read=null;try{d.writeInterfaceToken(BinderProtocol.DESCRIPTOR);d.writeString(token);d.writeInt(size);shell.transact(BinderProtocol.SHELL_TO_APP_FD,d,r,0);r.readException();read=ParcelFileDescriptor.CREATOR.createFromParcel(r);return BinderProtocol.readPattern(read,size);}finally{if(read!=null)try{read.close();}catch(Exception ignored){}d.recycle();r.recycle();}}
    }
    private static void requireShell(int caller){if(caller!=2000)throw new SecurityException("shell_uid_required");}
}
