package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.content.AttributionSource;
import android.os.*;
import java.lang.reflect.Method;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicReference;

public final class LeaseShellRole {
    static volatile String stage="entry";
    public static void main(String[] args){int code=0;try{run(args);}catch(Throwable e){code=1;Throwable x=unwrap(e);print("{\"schema\":\"rusty.quest.shell_caps_lease_fatal.v1\",\"stage\":"+ProbeCore.quote(stage)+",\"error\":"+ProbeCore.quote(x.getClass().getName()+":"+x.getMessage())+"}");}finally{System.exit(code);}}
    static void run(String[] a)throws Exception{if(android.os.Process.myUid()!=2000)throw new Exception("uid2000_required");if(a.length<3)throw new Exception("args");String mode=a[0],token=a[1];ProbeCore.requireToken(token);int uid=Integer.parseInt(a[2]);if(uid<10000)throw new Exception("app_uid");if("server".equals(mode)){if(a.length!=4)throw new Exception("server_args");server(token,uid,Integer.parseInt(a[3]));}else if("status".equals(mode))call(mode,"lease_status",token,uid);else if("stop".equals(mode))call(mode,"lease_stop",token,uid);else if("negative-callback".equals(mode))call(mode,"lease_negative_callback",token,uid);else throw new Exception("mode");}
    static void server(String token,int uid,int ttl)throws Exception{if(ttl<1000||ttl>120000)throw new Exception("ttl");final Thread watchdog=new Thread(()->{try{Thread.sleep(ttl);print("{\"schema\":\"rusty.quest.shell_caps_lease_watchdog.v1\",\"expired\":true}");System.exit(2);}catch(InterruptedException expected){}},"rqsc-watchdog");watchdog.start();LeaseBinder binder=new LeaseBinder(token,uid);Bundle in=new Bundle();in.putBinder("shell_binder",binder);in.putInt("expected_app_uid",uid);in.putInt("shell_pid",android.os.Process.myPid());Bundle out=providerCall("lease_open",token,in);if(!out.getBoolean("ok",false))throw new Exception("lease_open:"+out.getString("error"));IBinder app=out.getBinder("app_binder");if(app==null)throw new Exception("app_binder_missing");app.linkToDeath(()->{binder.appDead=true;binder.done.countDown();print("{\"schema\":\"rusty.quest.shell_caps_app_death.v1\",\"observed\":true}");},0);print("{\"schema\":\"rusty.quest.shell_caps_lease_ready.v1\",\"token\":"+ProbeCore.quote(token)+",\"shell_pid\":"+android.os.Process.myPid()+",\"shell_uid\":2000,\"app_uid\":"+uid+",\"app_snapshot\":"+out.getString("app_snapshot")+",\"app_to_shell_4096\":"+ProbeCore.quote(out.getString("app_to_shell_4096"))+",\"shell_to_app_4096\":"+ProbeCore.quote(out.getString("shell_to_app_4096"))+",\"app_to_shell_4194304\":"+ProbeCore.quote(out.getString("app_to_shell_4194304"))+",\"shell_to_app_4194304\":"+ProbeCore.quote(out.getString("shell_to_app_4194304"))+"}");boolean signaled=binder.done.await(ttl,TimeUnit.MILLISECONDS);watchdog.interrupt();print("{\"schema\":\"rusty.quest.shell_caps_lease_terminal.v1\",\"stop_received\":"+binder.stop+",\"app_death_observed\":"+binder.appDead+",\"ttl_expired\":"+(!signaled)+"}");}
    static void call(String label,String method,String token,int uid)throws Exception{Bundle in=new Bundle();in.putInt("expected_app_uid",uid);Bundle out=providerCall(method,token,in);print("{\"schema\":\"rusty.quest.shell_caps_lease_call.v1\",\"operation\":"+ProbeCore.quote(label)+",\"ok\":"+out.getBoolean("ok",false)+",\"error\":"+ProbeCore.quote(out.getString("error"))+",\"shell_binder_alive\":"+out.getBoolean("shell_binder_alive",false)+",\"shell_death_observed\":"+out.getBoolean("shell_death_observed",false)+",\"shell_reported_alive\":"+out.getBoolean("shell_reported_alive",false)+",\"shell_callback_caller_uid\":"+out.getInt("shell_callback_caller_uid",-1)+",\"activity_resumed\":"+out.getBoolean("activity_resumed",false)+",\"wrong_token_rejected\":"+out.getBoolean("wrong_token_rejected",false)+",\"negative_error\":"+ProbeCore.quote(out.getString("negative_error"))+",\"stop_sent\":"+out.getBoolean("stop_sent",false)+"}");}

    static final class LeaseBinder extends Binder {
        final String token;final int appUid;final CountDownLatch done=new CountDownLatch(1);volatile boolean stop,appDead;
        LeaseBinder(String token,int appUid){this.token=token;this.appUid=appUid;}
        @Override protected boolean onTransact(int code,Parcel data,Parcel reply,int flags)throws RemoteException{if(code<1||code>BinderProtocol.STOP)return false;data.enforceInterface(BinderProtocol.DESCRIPTOR);String got=data.readString();int caller=Binder.getCallingUid();if(!token.equals(got)||caller!=appUid)throw new SecurityException("callback_identity");try{if(code==BinderProtocol.IDENTIFY){reply.writeNoException();return true;}if(code==BinderProtocol.STATUS){reply.writeNoException();reply.writeInt(1);reply.writeInt(caller);return true;}if(code==BinderProtocol.STOP){stop=true;done.countDown();reply.writeNoException();return true;}int size=data.readInt();if(size!=BinderProtocol.SMALL&&size!=BinderProtocol.LARGE)throw new SecurityException("fd_size");if(code==BinderProtocol.APP_TO_SHELL_FD){ParcelFileDescriptor read=ParcelFileDescriptor.CREATOR.createFromParcel(data);String hash=BinderProtocol.readPattern(read,size);reply.writeNoException();reply.writeString(hash);return true;}if(code==BinderProtocol.SHELL_TO_APP_FD){final ParcelFileDescriptor[]pipe=ParcelFileDescriptor.createPipe();Thread writer=new Thread(()->{try{BinderProtocol.writePattern(pipe[1],size);}catch(Throwable x){print("{\"schema\":\"rusty.quest.shell_caps_pipe_writer_failure.v1\",\"error\":"+ProbeCore.quote(x.getClass().getName()+":"+x.getMessage())+"}");}},"rqsc-shell-writer");writer.start();reply.writeNoException();pipe[0].writeToParcel(reply,0);pipe[0].close();return true;}return false;}catch(Throwable e){throw new RemoteException(e.getClass().getName()+":"+e.getMessage());}}
    }

    static Bundle providerCall(String method,String token,Bundle extras)throws Exception{final String authority="io.github.mesmerprism.rustyquest.shellcapabilities";IBinder lease=new Binder();Class<?> sm=Class.forName("android.os.ServiceManager"),stub=Class.forName("android.app.IActivityManager$Stub"),iam=Class.forName("android.app.IActivityManager"),icp=Class.forName("android.content.IContentProvider");Method acquire=iam.getMethod("getContentProviderExternal",String.class,int.class,IBinder.class,String.class),call=icp.getMethod("call",AttributionSource.class,String.class,String.class,String.class,Bundle.class),release=iam.getMethod("removeContentProviderExternalAsUser",String.class,IBinder.class,int.class);Object am=null,holder=null;Bundle result=null;Throwable primary=null;try{stage="activity_service";IBinder activity=(IBinder)sm.getMethod("getService",String.class).invoke(null,"activity");stage="activity_interface";am=stub.getMethod("asInterface",IBinder.class).invoke(null,activity);stage="provider_acquire";holder=acquire.invoke(am,authority,0,lease,"rqsc");if(holder==null)throw new Exception("provider_holder_null");stage="provider_field";java.lang.reflect.Field field=holder.getClass().getDeclaredField("provider");field.setAccessible(true);Object provider=field.get(holder);stage="provider_call";result=(Bundle)call.invoke(provider,new AttributionSource.Builder(2000).setPackageName("com.android.shell").build(),authority,method,token,extras);stage="provider_call_complete";}catch(Throwable x){primary=unwrap(x);}finally{if(holder!=null&&am!=null)try{release.invoke(am,authority,lease,0);print("{\"schema\":\"rusty.quest.shell_caps_provider_release.v1\",\"provider_lease_released\":true}");}catch(Throwable x){Throwable r=unwrap(x);print("{\"schema\":\"rusty.quest.shell_caps_provider_release.v1\",\"provider_lease_released\":false,\"error\":"+ProbeCore.quote(r.getClass().getName()+":"+r.getMessage())+"}");if(primary==null)primary=r;}}if(primary!=null){if(primary instanceof Exception)throw(Exception)primary;throw new Exception(primary);}return result;}
    static Throwable unwrap(Throwable x){while(x instanceof java.lang.reflect.InvocationTargetException&&x.getCause()!=null)x=x.getCause();return x;}
    static synchronized void print(String value){System.out.println(value);System.out.flush();}
}
