package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.content.*;import android.net.*;import android.os.*;import java.io.*;import java.lang.reflect.Method;import java.net.*;import java.util.concurrent.*;

public final class ShellRole{
 static volatile String stage="entry";
 public static void main(String[]a){int code=0;try{run(a);}catch(Throwable e){code=1;Throwable x=unwrap(e);System.out.println("{\"schema\":\"rusty.quest.shell_caps_fatal.v1\",\"stage\":"+ProbeCore.quote(stage)+",\"error\":"+ProbeCore.quote(x.getClass().getName()+":"+x.getMessage())+"}");System.out.flush();}finally{System.exit(code);}}
 static void run(String[]a)throws Exception{if(android.os.Process.myUid()!=2000)throw new Exception("uid2000_required");if(a.length<2)throw new Exception("args");String mode=a[0],t=a[1];ProbeCore.requireToken(t);if("serve".equals(mode))serve(t);else if("probe-app".equals(mode))probeApp(t,Integer.parseInt(a[2]),a[3]);else if("binder".equals(mode))binder(t,Integer.parseInt(a[2]));else throw new Exception("mode");}
 static void serve(String t)throws Exception{ServerSocket tcp=new ServerSocket(0,1,InetAddress.getByName("127.0.0.1"));tcp.setSoTimeout(30000);String name="rqsc.shell."+t;LocalServerSocket uds=new LocalServerSocket(name);ExecutorService x=Executors.newFixedThreadPool(3);try{System.out.println("{\"schema\":\"rusty.quest.shell_caps_shell_ready.v1\",\"token\":\""+t+"\",\"shell_uid\":"+android.os.Process.myUid()+",\"tcp_port\":"+tcp.getLocalPort()+",\"uds_name\":\""+name+"\"}");System.out.flush();Future<String> ft=x.submit(()->{try{Socket s=tcp.accept();ProbeCore.serve(s,t);s.close();return "{\"ok\":true}";}catch(Throwable e){return err(e);}});Future<String> fu=x.submit(()->{try{LocalSocket s=uds.accept();Credentials c=s.getPeerCredentials();ProbeCore.serve(new LS(s),t);s.close();return "{\"ok\":true,\"peer_uid\":"+c.getUid()+",\"peer_pid\":"+c.getPid()+"}";}catch(Throwable e){return err(e);}});x.submit(()->{try{Thread.sleep(30000);uds.close();}catch(Throwable ignored){}});String tr,ur;try{tr=ft.get(35,TimeUnit.SECONDS);}catch(Throwable e){tr=err(e);}try{ur=fu.get(35,TimeUnit.SECONDS);}catch(Throwable e){ur=err(e);}System.out.println("{\"schema\":\"rusty.quest.shell_caps_shell_result.v1\",\"app_to_shell_tcp\":"+tr+",\"app_to_shell_uds\":"+ur+"}");}finally{try{tcp.close();}catch(Exception ignored){}try{uds.close();}catch(Exception ignored){}x.shutdownNow();}}
 static void probeApp(String t,int port,String name)throws Exception{String tr,ur;try{Socket s=new Socket();s.connect(new InetSocketAddress("127.0.0.1",port),3000);tr=ProbeCore.client(s,t);s.close();}catch(Throwable e){tr=err(e);}try{LocalSocket s=new LocalSocket();s.connect(new LocalSocketAddress(name,LocalSocketAddress.Namespace.ABSTRACT));Credentials c=s.getPeerCredentials();ur=ProbeCore.client(new LS(s),t).replace("}",",\"peer_uid\":"+c.getUid()+",\"peer_pid\":"+c.getPid()+"}");s.close();}catch(Throwable e){ur=err(e);}System.out.println("{\"schema\":\"rusty.quest.shell_caps_probe_app.v1\",\"shell_uid\":"+android.os.Process.myUid()+",\"shell_to_app_tcp\":"+tr+",\"shell_to_app_uds\":"+ur+"}");}
 static void binder(String t,int expectedAppUid)throws Exception{if(expectedAppUid<10000)throw new Exception("app_uid");if(Looper.getMainLooper()==null)Looper.prepareMainLooper();final int[] callback={-1};Binder b=new Binder(){protected boolean onTransact(int code,Parcel data,Parcel reply,int flags)throws android.os.RemoteException{if(code!=1)return false;data.enforceInterface("rusty.quest.shell.capabilities");String got=data.readString();callback[0]=Binder.getCallingUid();if(!t.equals(got)||callback[0]!=expectedAppUid)throw new SecurityException("callback_identity");reply.writeNoException();reply.writeString(got);reply.writeInt(android.os.Process.myUid());reply.writeInt(callback[0]);return true;}};Bundle in=new Bundle();in.putBinder("shell_binder",b);in.putInt("expected_app_uid",expectedAppUid);Bundle out=externalProviderCall("binder_handoff",t,in);System.out.println("{\"schema\":\"rusty.quest.shell_caps_binder.v1\",\"provider_route\":\"activity_manager_external\",\"context_package\":\"com.android.shell\",\"shell_uid\":"+android.os.Process.myUid()+",\"provider_uid\":"+out.getInt("provider_process_uid",-1)+",\"provider_observed_calling_uid\":"+out.getInt("provider_calling_uid",-1)+",\"shell_observed_callback_uid\":"+out.getInt("shell_observed_callback_uid",-1)+",\"echo\":"+ProbeCore.quote(out.getString("echo"))+",\"ok\":"+out.getBoolean("ok",false)+",\"error\":"+ProbeCore.quote(out.getString("error"))+"}");}
 static Bundle externalProviderCall(String providerMethod,String token,Bundle extras)throws Exception{final String authority="io.github.mesmerprism.rustyquest.shellcapabilities";IBinder lease=new Binder();Class<?> sm=Class.forName("android.os.ServiceManager"),stub=Class.forName("android.app.IActivityManager$Stub"),iam=Class.forName("android.app.IActivityManager"),icp=Class.forName("android.content.IContentProvider");Method acquire=iam.getMethod("getContentProviderExternal",String.class,int.class,IBinder.class,String.class);Method call=icp.getMethod("call",android.content.AttributionSource.class,String.class,String.class,String.class,Bundle.class);Method release=iam.getMethod("removeContentProviderExternalAsUser",String.class,IBinder.class,int.class);System.out.println("{\"schema\":\"rusty.quest.shell_caps_binder_signatures.v1\",\"acquire\":"+ProbeCore.quote(acquire.toGenericString())+",\"call\":"+ProbeCore.quote(call.toGenericString())+",\"release\":"+ProbeCore.quote(release.toGenericString())+"}");System.out.flush();Object am=null,holder=null;Bundle result=null;Throwable primary=null;try{stage="activity_service";IBinder activity=(IBinder)sm.getMethod("getService",String.class).invoke(null,"activity");stage="activity_interface";am=stub.getMethod("asInterface",IBinder.class).invoke(null,activity);stage="provider_acquire";holder=acquire.invoke(am,authority,0,lease,"rqsc");if(holder==null)throw new Exception("provider_holder_null");stage="provider_field";java.lang.reflect.Field pf=holder.getClass().getDeclaredField("provider");pf.setAccessible(true);Object provider=pf.get(holder);if(provider==null)throw new Exception("provider_null");stage="provider_call";android.content.AttributionSource source=new android.content.AttributionSource.Builder(2000).setPackageName("com.android.shell").build();Object out=call.invoke(provider,source,authority,providerMethod,token,extras);if(!(out instanceof Bundle))throw new Exception("provider_result");result=(Bundle)out;stage="provider_call_complete";}catch(Throwable x){primary=unwrap(x);}finally{if(holder!=null&&am!=null){try{stage="provider_release";release.invoke(am,authority,lease,0);System.out.println("{\"schema\":\"rusty.quest.shell_caps_provider_release.v1\",\"provider_lease_released\":true}");}catch(Throwable x){Throwable r=unwrap(x);System.out.println("{\"schema\":\"rusty.quest.shell_caps_provider_release.v1\",\"provider_lease_released\":false,\"error\":"+ProbeCore.quote(r.getClass().getName()+":"+r.getMessage())+"}");if(primary==null)primary=r;}System.out.flush();}}if(primary!=null){if(primary instanceof Exception)throw(Exception)primary;throw new Exception(primary);}return result;}
 static Throwable unwrap(Throwable x){while(x instanceof java.lang.reflect.InvocationTargetException&&x.getCause()!=null)x=x.getCause();return x;}
 static String err(Throwable e){return "{\"ok\":false,\"error\":"+ProbeCore.quote(e.getClass().getName()+":"+e.getMessage())+"}";}
 static final class LS extends Socket{final LocalSocket s;LS(LocalSocket x){s=x;}public InputStream getInputStream()throws IOException{return s.getInputStream();}public OutputStream getOutputStream()throws IOException{return s.getOutputStream();}public synchronized void close()throws IOException{s.close();}public void setSoTimeout(int n)throws SocketException{try{s.setSoTimeout(n);}catch(IOException e){throw new SocketException(e.toString());}}}
}
