package io.github.mesmerprism.rustyquest.shellcapabilities;

import android.os.*;import java.io.*;import java.util.concurrent.*;

public final class WifiShellRole{
 static final class Server extends Binder{
  final String token;final byte[]tokenBytes,secret;final int appUid;final CountDownLatch done=new CountDownLatch(1);final long expires;int lastSeq;String state="BASELINE";boolean noop,stop,appDead,offDispatched;java.lang.Process guardian;
  Server(String t,int uid,long expires,byte[]secret){token=t;tokenBytes=BleProtocol.token(t);appUid=uid;this.expires=expires;this.secret=secret;}
  protected boolean onTransact(int code,Parcel data,Parcel reply,int flags)throws RemoteException{if(code<BinderProtocol.IDENTIFY||code>BinderProtocol.BLE_READY)return false;data.enforceInterface(BinderProtocol.DESCRIPTOR);String got=data.readString();if(!token.equals(got)||Binder.getCallingUid()!=appUid)throw new SecurityException("callback_identity");try{if(code==BinderProtocol.IDENTIFY){reply.writeNoException();return true;}if(code==BinderProtocol.STATUS){reply.writeNoException();reply.writeInt(1);reply.writeInt(Binder.getCallingUid());return true;}if(code==BinderProtocol.STOP){stop=true;done.countDown();reply.writeNoException();return true;}if(code==BinderProtocol.BLE_READY){reply.writeNoException();reply.writeByteArray(BleProtocol.reply(BleProtocol.READY,0,tokenBytes,secret));return true;}if(code!=BinderProtocol.BLE_FRAME)throw new SecurityException("closed_method");byte[]frame=data.createByteArray();byte[]response=command(frame);reply.writeNoException();reply.writeByteArray(response);return true;}catch(Throwable x){throw new RemoteException(x.getClass().getName()+":"+x.getMessage());}}
  synchronized byte[]command(byte[]f)throws Exception{int seq=f!=null&&f.length>=4?BleProtocol.seq(f):0,op=f!=null&&f.length>=2?f[1]&255:0,outcome;if(SystemClock.elapsedRealtime()>=expires)outcome=BleProtocol.EXPIRED;else if(!BleProtocol.valid(f,tokenBytes,secret,'C'))outcome=BleProtocol.BAD_MAC;else if(seq!=lastSeq+1)outcome=BleProtocol.REPLAY;else if(op==BleProtocol.NOOP&&state.equals("BASELINE")&&!noop){noop=true;lastSeq=seq;outcome=BleProtocol.NOOP;}else if(op==BleProtocol.OFF&&state.equals("BASELINE")&&noop){armGuardian();offDispatched=true;runSet("disabled");requireState(false);state="OFF";lastSeq=seq;outcome=BleProtocol.OFF;}else if(op==BleProtocol.RESUME&&state.equals("OFF")){runSet("enabled");requireState(true);stopGuardian();offDispatched=false;state="RESTORED";lastSeq=seq;outcome=BleProtocol.RESUME;}else outcome=BleProtocol.PHASE;WifiShellRole.print("{\"schema\":\"rusty.quest.shell_caps_wifi_command.v1\",\"caller_uid\":"+Binder.getCallingUid()+",\"app_uid\":"+appUid+",\"sequence\":"+seq+",\"operation\":"+op+",\"outcome\":"+outcome+",\"state\":"+ProbeCore.quote(state)+"}");return BleProtocol.reply(outcome,seq,tokenBytes,secret);}
  void armGuardian()throws Exception{if(guardian!=null)throw new Exception("guardian_active");String cp=System.getenv("CLASSPATH");ProcessBuilder b=new ProcessBuilder("/system/bin/app_process","/",WifiRestoreGuardian.class.getName(),token,"30000");b.environment().put("CLASSPATH",cp);b.redirectOutput(new File("/dev/null"));b.redirectError(new File("/dev/null"));guardian=b.start();Thread.sleep(50);if(!guardian.isAlive())throw new Exception("guardian_start");long gp=pid(guardian);print("{\"schema\":\"rusty.quest.shell_caps_guardian.v1\",\"state\":\"armed\",\"token\":"+ProbeCore.quote(token)+",\"pid\":"+gp+",\"start_ticks\":"+start(gp)+",\"restore_deadline_elapsed_ms\":"+(SystemClock.elapsedRealtime()+30000)+"}");}
  void stopGuardian()throws Exception{if(guardian==null)return;guardian.destroy();if(!guardian.waitFor(1000,TimeUnit.MILLISECONDS)){guardian.destroyForcibly();if(!guardian.waitFor(2000,TimeUnit.MILLISECONDS))throw new Exception("guardian_exit_timeout");}print("{\"schema\":\"rusty.quest.shell_caps_guardian.v1\",\"state\":\"stopped\",\"alive\":false}");guardian=null;}
  synchronized void restore(){if(!offDispatched&&guardian==null)return;try{if(!enabled())runSet("enabled");requireState(true);stopGuardian();offDispatched=false;print("{\"schema\":\"rusty.quest.shell_caps_wifi_restore.v1\",\"enabled\":true}");}catch(Throwable x){print("{\"schema\":\"rusty.quest.shell_caps_wifi_restore.v1\",\"enabled\":false,\"guardian_retained\":"+(guardian!=null&&guardian.isAlive())+",\"error\":"+ProbeCore.quote(x.getClass().getName()+":"+x.getMessage())+"}");}}
 }
 public static void main(String[]a){int code=0;try{run(a);}catch(Throwable x){code=1;print("{\"schema\":\"rusty.quest.shell_caps_wifi_fatal.v1\",\"error\":"+ProbeCore.quote(x.getClass().getName()+":"+x.getMessage())+"}");}finally{System.exit(code);}}
 static void run(String[]a)throws Exception{if(android.os.Process.myUid()!=2000||a.length<3)throw new Exception("args_uid");String mode=a[0],token=a[1];int uid=Integer.parseInt(a[2]);ProbeCore.requireToken(token);if("server".equals(mode)){if(a.length!=5)throw new Exception("server_args");server(token,uid,Integer.parseInt(a[3]),BleProtocol.secret(a[4]));}else if("status".equals(mode)||"stop".equals(mode)){Bundle in=new Bundle();in.putInt("expected_app_uid",uid);Bundle out=LeaseShellRole.providerCall(mode.equals("stop")?"lease_stop":"lease_status",token,in);print("{\"schema\":\"rusty.quest.shell_caps_wifi_control.v1\",\"operation\":"+ProbeCore.quote(mode)+",\"ok\":"+out.getBoolean("ok",false)+",\"error\":"+ProbeCore.quote(out.getString("error"))+",\"shell_binder_alive\":"+out.getBoolean("shell_binder_alive",false)+",\"shell_death_observed\":"+out.getBoolean("shell_death_observed",false)+"}");}else throw new Exception("mode");}
 static void server(String token,int uid,int ttl,byte[]secret)throws Exception{if(uid<10000||ttl<1000||ttl>120000)throw new Exception("server_bounds");long expires=SystemClock.elapsedRealtime()+ttl;Server server=new Server(token,uid,expires,secret);Thread watchdog=new Thread(()->{try{Thread.sleep(ttl);server.restore();print("{\"schema\":\"rusty.quest.shell_caps_wifi_watchdog.v1\",\"expired\":true}");System.exit(2);}catch(InterruptedException expected){}},"rqsc-wifi-watchdog");watchdog.start();if(!enabled())throw new Exception("baseline_not_enabled");Bundle in=new Bundle();in.putBinder("shell_binder",server);in.putInt("expected_app_uid",uid);Bundle out=LeaseShellRole.providerCall("wifi_lease_open",token,in);if(!out.getBoolean("ok",false))throw new Exception("lease_open:"+out.getString("error"));IBinder app=out.getBinder("app_binder");app.linkToDeath(()->{server.appDead=true;server.done.countDown();},0);print("{\"schema\":\"rusty.quest.shell_caps_wifi_ready.v1\",\"token\":"+ProbeCore.quote(token)+",\"shell_uid\":2000,\"shell_pid\":"+android.os.Process.myPid()+",\"app_uid\":"+uid+",\"baseline_enabled\":true,\"expires_elapsed_ms\":"+expires+"}");try{server.done.await(Math.max(1,expires-SystemClock.elapsedRealtime()),TimeUnit.MILLISECONDS);}finally{server.restore();watchdog.interrupt();print("{\"schema\":\"rusty.quest.shell_caps_wifi_terminal.v1\",\"stop_received\":"+server.stop+",\"app_death_observed\":"+server.appDead+",\"final_enabled\":"+enabled()+"}");}}
 static boolean enabled()throws Exception{String s=runCmd("status");if(s.startsWith("Wifi is enabled"))return true;if(s.startsWith("Wifi is disabled"))return false;throw new Exception("wifi_status:"+s);}
 static void requireState(boolean want)throws Exception{long end=SystemClock.elapsedRealtime()+5000;while(SystemClock.elapsedRealtime()<end){if(enabled()==want)return;Thread.sleep(100);}throw new Exception("wifi_state_timeout");}
 static void runSet(String value)throws Exception{String out=runCmd("set-wifi-enabled",value);print("{\"schema\":\"rusty.quest.shell_caps_wifi_effect.v1\",\"caller_uid\":2000,\"value\":"+ProbeCore.quote(value)+",\"stdout\":"+ProbeCore.quote(out)+"}");}
 static String runCmd(String...args)throws Exception{String[]c=new String[args.length+2];c[0]="/system/bin/cmd";c[1]="wifi";System.arraycopy(args,0,c,2,args.length);java.lang.Process p=new ProcessBuilder(c).redirectErrorStream(true).start();ByteArrayOutputStream b=new ByteArrayOutputStream();InputStream in=p.getInputStream();try{p.getOutputStream().close();byte[]buf=new byte[1024];long deadline=SystemClock.elapsedRealtime()+5000;while(p.isAlive()&&SystemClock.elapsedRealtime()<deadline&&b.size()<4096){while(in.available()>0&&b.size()<4096){int n=in.read(buf,0,Math.min(buf.length,4096-b.size()));if(n>0)b.write(buf,0,n);}Thread.sleep(10);}if(p.isAlive()){p.destroyForcibly();p.waitFor(1000,TimeUnit.MILLISECONDS);throw new Exception("cmd_timeout");}while(in.available()>0&&b.size()<4096){int n=in.read(buf,0,Math.min(buf.length,4096-b.size()));if(n>0)b.write(buf,0,n);}if(p.exitValue()!=0)throw new Exception("cmd_exit_"+p.exitValue()+":"+b.toString("UTF-8"));return b.toString("UTF-8").trim();}finally{try{in.close();}catch(Exception ignored){}try{p.getErrorStream().close();}catch(Exception ignored){}}}
 static long start(long pid){try{String raw=AppSnapshot.read("/proc/"+pid+"/stat");String tail=raw.substring(raw.lastIndexOf(')')+2);return Long.parseLong(tail.split(" ")[19]);}catch(Throwable x){return-1;}}
 static long pid(java.lang.Process p){try{return((Long)java.lang.Process.class.getMethod("pid").invoke(p)).longValue();}catch(Throwable x){return-1;}}
 static synchronized void print(String s){System.out.println(s);System.out.flush();}
}
