import java.util.*;
/** Immutable cleanup identity derived from live source-owned formation, not a topology grant. */
final class OriginalStationFormationAdmission {
  static final Set<String> INPUT_KEYS=new HashSet<>(Arrays.asList("run_id","run_token","serial","boot_id","pair_apk_sha256","guardian_dex_sha256","source_revision","source_tree","pid","pid_start_ticks","go_serial","go_boot_id","go_receipt_sha256"));
  static final Set<String> LIVE_INPUT_KEYS=liveKeys();
  static Set<String> liveKeys(){Set<String> keys=new HashSet<>(INPUT_KEYS);keys.remove("pid");keys.remove("pid_start_ticks");keys.add("process_binding");return keys;}
  static boolean liveInput(Properties p){return p.stringPropertyNames().equals(LIVE_INPUT_KEYS);}
  static Properties parseInput(String text){return strict(text,text.contains("process_binding=")?LIVE_INPUT_KEYS:INPUT_KEYS);}
  static boolean pendingCarrier(Properties p){return liveInput(p)&&"pending-authenticated-carrier".equals(p.getProperty("go_receipt_sha256"));}
  static final Set<String> RECEIPT_KEYS=new HashSet<>(Arrays.asList("run_id","run_token","serial","boot_id","local_owner","network","owner_mac","pair_apk_sha256","guardian_dex_sha256","source_revision","source_tree","pid","pid_start_ticks","config_sha256","state_sha256","observed_elapsed_ms","go_receipt_sha256"));
  static Properties strict(String text,Set<String> keys){Properties p=new Properties();for(String line:text.split("\n",-1)){if(line.isEmpty())continue;int at=line.indexOf('=');if(at<1||line.indexOf('\r')>=0||!keys.contains(line.substring(0,at))||p.setProperty(line.substring(0,at),line.substring(at+1))!=null)throw new SecurityException("formation_keys");}if(!p.stringPropertyNames().equals(keys))throw new SecurityException("formation_keys");return p;}
  static final class Monitor {
    final String inputSha;String receiptSha;boolean busy;
    Monitor(String input){hash(input);inputSha=input;}
    void current(String input,String receipt){if(!inputSha.equals(input))throw new SecurityException("formation_input_changed");if(receiptSha==null?receipt!=null:!receiptSha.equals(receipt))throw new SecurityException("formation_receipt_changed");}
    boolean begin(long now,long deadline){if(now<0||deadline<0)throw new SecurityException("formation_monitor_deadline");if(busy)throw new SecurityException("formation_monitor_reentrant");if(deadline<=now||receiptSha!=null)return false;busy=true;return true;}
    void complete(String sha){if(!busy||receiptSha!=null)throw new SecurityException("formation_monitor_reentrant");hash(sha);receiptSha=sha;busy=false;}
    void unavailable(){if(!busy)throw new SecurityException("formation_monitor_reentrant");busy=false;}
  }
  static void processCommand(String cmd,String pkg){if(cmd==null||!cmd.matches(java.util.regex.Pattern.quote(pkg)+"\\x00+"))throw new SecurityException("formation_process_command");}
  static void hash(String s){if(s==null||!s.matches("[0-9a-f]{64}"))throw new SecurityException("formation_hash");}
  static void input(Properties p,OriginalStationGuardContract c){if((!p.stringPropertyNames().equals(INPUT_KEYS)&&!liveInput(p))||!c.run.equals(p.getProperty("run_token"))||!c.serial.equals(p.getProperty("serial"))||!c.boot.equals(p.getProperty("boot_id"))||!p.getProperty("run_id").matches("[A-Za-z0-9_-]{1,128}")||(!liveInput(p)&&(!p.getProperty("pid").matches("[1-9][0-9]{0,8}")||!p.getProperty("pid_start_ticks").matches("[0-9]+")))||(liveInput(p)&&!"current-source-provider".equals(p.getProperty("process_binding")))||!p.getProperty("source_revision").matches("[0-9a-f]{40}")||!p.getProperty("source_tree").matches("[0-9a-f]{40}"))throw new SecurityException("formation_input_identity");hash(p.getProperty("pair_apk_sha256"));hash(p.getProperty("guardian_dex_sha256"));
    if(c.localOwner){if(!p.getProperty("go_serial").equals(c.serial)||!p.getProperty("go_boot_id").equals(c.boot)||!p.getProperty("go_receipt_sha256").equals("none"))throw new SecurityException("formation_go_input");}else{if(!p.getProperty("go_serial").matches("[A-Za-z0-9]{8,32}")||p.getProperty("go_serial").equals(c.serial)||!p.getProperty("go_boot_id").matches("[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"))throw new SecurityException("formation_peer_input");if(!pendingCarrier(p))hash(p.getProperty("go_receipt_sha256"));}}
  static void live(Properties p,OriginalStationGuardContract c,Map<String,String> v,long now){input(p,c);if(v==null||!v.keySet().equals(new HashSet<>(Arrays.asList("run_id","run_token","boot_id","pid","pid_start_ticks","network","owner_mac","local_owner","observed_elapsed_ms"))))throw new SecurityException("formation_live_keys");for(String k:Arrays.asList("run_id","run_token","boot_id","pid","pid_start_ticks"))if(!(liveInput(p)&&(k.equals("pid")||k.equals("pid_start_ticks")))&&!p.getProperty(k).equals(v.get(k)))throw new SecurityException("formation_live_identity");if(!c.network.equals(v.get("network"))||!String.valueOf(c.localOwner).equals(v.get("local_owner"))||!v.get("owner_mac").matches("[0-9a-f]{2}(:[0-9a-f]{2}){5}"))throw new SecurityException("formation_live_group");if(!v.get("pid").matches("[1-9][0-9]{0,8}")||!v.get("pid_start_ticks").matches("[0-9]+"))throw new SecurityException("formation_live_process");long observed=Long.parseLong(v.get("observed_elapsed_ms"));if(observed<0||now<observed||now-observed>2000)throw new SecurityException("formation_live_age");}
  static boolean carrierAvailable(boolean payload,boolean descriptor){if(descriptor&&!payload)throw new SecurityException("formation_descriptor_without_payload");return payload&&descriptor;}
  static void processPair(Properties p,String pid,String birth){if(!liveInput(p)&&(!pid.equals(p.getProperty("pid"))||!birth.equals(p.getProperty("pid_start_ticks"))))throw new SecurityException("formation_process");}
  static void liveProcess(Map<String,String> v,String pid,String birth){if(!pid.equals(v.get("pid"))||!birth.equals(v.get("pid_start_ticks")))throw new SecurityException("formation_actor_changed");}
  static void peer(Properties input,Properties go,String mac){if(!go.stringPropertyNames().equals(RECEIPT_KEYS)||!"true".equals(go.getProperty("local_owner"))||!input.getProperty("go_serial").equals(go.getProperty("serial"))||!input.getProperty("go_boot_id").equals(go.getProperty("boot_id"))||!mac.equals(go.getProperty("owner_mac")))throw new SecurityException("formation_peer_group");for(String k:Arrays.asList("run_id","run_token","pair_apk_sha256","guardian_dex_sha256","source_revision","source_tree"))if(!input.getProperty(k).equals(go.getProperty(k)))throw new SecurityException("formation_peer_identity");if(!("DIRECT-rp-"+input.getProperty("run_token").substring(0,20)).equals(go.getProperty("network")))throw new SecurityException("formation_peer_network");}
  static void cleanup(Properties receipt,OriginalStationGuardContract c,String configSha,String stateSha,String dexSha,String network,String mac,boolean owner){if(!receipt.stringPropertyNames().equals(RECEIPT_KEYS)||!c.run.equals(receipt.getProperty("run_token"))||!c.serial.equals(receipt.getProperty("serial"))||!c.boot.equals(receipt.getProperty("boot_id"))||!configSha.equals(receipt.getProperty("config_sha256"))||!stateSha.equals(receipt.getProperty("state_sha256"))||!dexSha.equals(receipt.getProperty("guardian_dex_sha256"))||!c.network.equals(network)||!network.equals(receipt.getProperty("network"))||!mac.equals(receipt.getProperty("owner_mac"))||owner!=c.localOwner||!String.valueOf(owner).equals(receipt.getProperty("local_owner")))throw new SecurityException("formation_cleanup_identity");}
  static String text(Properties p){List<String> keys=new ArrayList<>(p.stringPropertyNames());Collections.sort(keys);StringBuilder b=new StringBuilder();for(String key:keys)b.append(key).append('=').append(p.getProperty(key)).append('\n');return b.toString();}
}
