param(
    [string]$RepoRoot
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
}
$repoRootPath = Resolve-Path $RepoRoot
$appRoot = Join-Path $repoRootPath "apps\kuramoto-spatial-sdk-android"
$sourceRoot = Join-Path $appRoot "app\src\main\java\io\github\mesmerprism\rustyquest\kuramoto_spatial"

function Read-RequiredText {
    param(
        [string]$Path,
        [string]$Label
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Missing Kuramoto Spatial SDK static file ($Label): $Path"
    }
    return Get-Content -Raw -LiteralPath $Path
}

function Assert-ContainsTokens {
    param(
        [string]$Text,
        [string[]]$Tokens,
        [string]$Label
    )
    foreach ($token in $Tokens) {
        if ($Text -notmatch $token) {
            throw "Kuramoto Spatial SDK static check failed for ${Label}: missing token: $token"
        }
    }
}

$settings = Read-RequiredText (Join-Path $appRoot "settings.gradle.kts") "settings"
$rootBuild = Read-RequiredText (Join-Path $appRoot "build.gradle.kts") "root build"
$gradleProperties = Read-RequiredText (Join-Path $appRoot "gradle.properties") "Gradle properties"
$versions = Read-RequiredText (Join-Path $appRoot "gradle\libs.versions.toml") "version catalog"
$appBuild = Read-RequiredText (Join-Path $appRoot "app\build.gradle.kts") "app build"
$manifest = Read-RequiredText (Join-Path $appRoot "app\src\main\AndroidManifest.xml") "manifest"
$ids = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\ids.xml") "ids"
$styles = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\styles.xml") "styles"
$colors = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\colors.xml") "colors"
$activity = Read-RequiredText (Join-Path $sourceRoot "KuramotoSpatialActivity.kt") "Spatial activity"
$store = Read-RequiredText (Join-Path $sourceRoot "KuramotoExperimentStore.kt") "experiment store"
$polarSensorPanel = Read-RequiredText (Join-Path $sourceRoot "PolarSensorPanel.java") "Polar sensor panel"
$nativeReceiptCargo = Read-RequiredText (Join-Path $appRoot "native-receipt\Cargo.toml") "native receipt Cargo manifest"
$nativeReceiptRust = Read-RequiredText (Join-Path $appRoot "native-receipt\src\lib.rs") "native receipt Rust source"
$nativeReceiptSurfaceLayer = Read-RequiredText (Join-Path $appRoot "native-receipt\src\surface_particle_layer.rs") "native receipt surface particle layer"
$nativeReceiptReplayHands = Read-RequiredText (Join-Path $appRoot "native-receipt\src\replay_hands.rs") "native receipt replay hand renderer"
$nativeReceiptLiveHandJoints = Read-RequiredText (Join-Path $appRoot "native-receipt\src\live_hand_joints.rs") "native receipt live hand joint source"
$nativeReceiptBuild = Read-RequiredText (Join-Path $appRoot "native-receipt\build.rs") "native receipt build script"
$nativeReceiptComputeShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\surface_particles.comp.glsl") "native receipt compute shader"
$nativeReceiptVertexShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\surface_particles.vert.glsl") "native receipt vertex shader"
$nativeReceiptReplayHandVertexShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\replay_hands.vert.glsl") "native receipt replay hand vertex shader"
$nativeReceiptReplayHandFragmentShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\replay_hands.frag.glsl") "native receipt replay hand fragment shader"
$buildScript = Read-RequiredText (Join-Path $repoRootPath "tools\Build-KuramotoSpatialSdkAndroid.ps1") "build wrapper"
$selfTestTool = Read-RequiredText (Join-Path $repoRootPath "tools\Invoke-KuramotoSpatialSdkAndroidSelfTest.ps1") "headset self-test wrapper"
$polarLiveTool = Read-RequiredText (Join-Path $repoRootPath "tools\Invoke-KuramotoSpatialSdkAndroidPolarLive.ps1") "live Polar headset wrapper"
$depthOffsetTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialLiveHandDepthOffset.ps1") "live hand depth-offset hotload tool"
$targetDistanceTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialParticleLayerTargetDistance.ps1") "particle layer target-distance hotload tool"
$overscanTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialParticleLayerOverscan.ps1") "particle layer overscan hotload tool"
$diagnosticModeTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialParticleDiagnosticMode.ps1") "particle diagnostic mode hotload tool"
$liveHandSceneTransformTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialLiveHandSceneTransform.ps1") "live hand scene-transform hotload tool"
$panelHeadlockTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialPanelHeadlock.ps1") "panel headlock hotload tool"
$uiActionTool = Read-RequiredText (Join-Path $repoRootPath "tools\Invoke-KuramotoSpatialSdkAndroidUiAction.ps1") "Spatial UI action wrapper"
$readme = Read-RequiredText (Join-Path $appRoot "README.md") "app README"
$plan = Read-RequiredText (Join-Path $repoRootPath "docs\SPATIAL_SDK_PORT_IMPLEMENTATION_PLAN.md") "implementation plan"

Assert-ContainsTokens $settings @(
    'rootProject\.name = "RustyQuestKuramotoSpatialSdk"',
    'include\(":app"\)',
    'mavenCentral\(\)',
    'google\(\)'
) "Gradle settings"

Assert-ContainsTokens $rootBuild @(
    'libs\.plugins\.android\.application',
    'libs\.plugins\.jetbrains\.kotlin\.android'
) "root Gradle plugins"

Assert-ContainsTokens $gradleProperties @(
    'android\.useAndroidX=true',
    'android\.nonTransitiveRClass=true',
    'org\.gradle\.configuration-cache=true'
) "Gradle properties"

Assert-ContainsTokens $versions @(
    'spatialsdk = "0\.13\.1"',
    'agp = "8\.11\.1"',
    'kotlin = "2\.1\.0"',
    'meta-spatial-sdk-base',
    'meta-spatial-sdk-compose',
    'meta-spatial-sdk-toolkit',
    'meta-spatial-sdk-vr'
) "version catalog"

Assert-ContainsTokens $appBuild @(
    'libs\.plugins\.meta\.spatial\.plugin',
    'libs\.plugins\.compose\.compiler',
    'namespace = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial"',
    'applicationId = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial"',
    'compileSdk = 34',
    'minSdk = 34',
    'targetSdk = 34',
    'compose = true',
    'kotlinCompilerExtensionVersion = "1\.5\.15"',
    'jniLibs\.srcDir\(layout\.buildDirectory\.dir\("generated/rustJniLibs"\)\)',
    'allowUsageDataCollection\.set\(false\)',
    'implementation\(libs\.meta\.spatial\.sdk\.base\)',
    'implementation\(libs\.meta\.spatial\.sdk\.compose\)',
    'implementation\(libs\.meta\.spatial\.sdk\.toolkit\)',
    'implementation\(libs\.meta\.spatial\.sdk\.vr\)'
) "app Gradle build"

Assert-ContainsTokens $manifest @(
    'horizonos:uses-horizonos-sdk',
    'android\.hardware\.vr\.headtracking',
    'com\.oculus\.intent\.category\.VR',
    'android\.intent\.category\.LAUNCHER',
    'android\.permission\.ACCESS_FINE_LOCATION',
    'android\.permission\.BLUETOOTH',
    'android\.permission\.BLUETOOTH_ADMIN',
    'android\.permission\.BLUETOOTH_CONNECT',
    'android\.permission\.BLUETOOTH_SCAN',
    'com\.oculus\.supportedDevices',
    'libossdk\.oculus\.so',
    'KuramotoSpatialActivity',
    'android:configChanges="screenSize\|screenLayout\|orientation\|keyboardHidden\|keyboard\|navigation\|uiMode"'
) "Android manifest"

Assert-ContainsTokens $ids @(
    'kuramoto_experiment_panel',
    'kuramoto_panel_launcher',
    'kuramoto_particle_surface_panel'
) "panel id"

Assert-ContainsTokens $styles @(
    'PanelAppThemeOpaqueProbe',
    'android:windowBackground">@color/kuramoto_panel_probe_background',
    'android:colorAccent">@color/kuramoto_panel_probe_button'
) "panel styles"

Assert-ContainsTokens $colors @(
    'kuramoto_panel_probe_background">#FFF3B0',
    'kuramoto_panel_probe_button">#FF5A1F'
) "panel colors"

Assert-ContainsTokens $activity @(
    'class KuramotoSpatialActivity : AppSystemActivity',
    'VRFeature\(this\)',
    'ComposeFeature\(\)',
    'ComposeViewPanelRegistration',
    'VideoSurfacePanelRegistration',
    'MediaPanelSettings',
    'MediaPanelRenderOptions',
    'FixedMediaPanelDisplayOptions',
    'PanelSurface',
    'SamplerConfig',
    'UIPanelSettings',
    'QuadShapeOptions\(width = PANEL_WIDTH_METERS, height = PANEL_HEIGHT_METERS\)',
    'DpPerMeterDisplayOptions\(dpPerMeter = PANEL_DP_PER_METER\)',
    'Entity\.createPanelEntity',
    'R\.id\.kuramoto_particle_surface_panel',
    'R\.id\.kuramoto_panel_launcher',
    'scene\.setViewOrigin\(0\.0f, 0\.0f, 2\.0f, 180\.0f\)',
    'diagnosticBackdrop=false',
    'contrastEnvironment=false',
    'PanelDimensions\(Vector2\(panelPlacement\.widthMeters, panelPlacement\.heightMeters\)\)',
    'Visible\(true\)',
    'Visible\(panelPlacement\.visible\)',
    'Visible\(!panelPlacement\.visible\)',
    'Quaternion\(6\.12323426e-17f, 6\.12323426e-17f, 1\.0f, -3\.74939976e-33f\)',
    'setBackgroundColor\(android\.graphics\.Color\.rgb\(255, 243, 176\)\)',
    'PanelAppThemeOpaqueProbe',
    'PanelColorProbe',
    'PANEL COLOR PROBE',
    'Visible Button',
    'lightColorScheme',
    'onVRReady\(\)',
    'logNativeInteropProbe\(phase = "scene-ready", probeSurface = false\)',
    'logNativeInteropProbe\(phase = "vr-ready", probeSurface = true\)',
    'loadNativeReceiptLibrary\(\)',
    'System\.loadLibrary\(NATIVE_RECEIPT_LIBRARY\)',
    'recordNativeInteropReceipt',
    'nativeRecordNoRenderInteropReceipt',
    'nativeStartSurfaceParticleLayer',
    'nativeStopSurfaceParticleLayer',
    'nativeUpdateSurfaceParticleParameters',
    'liveHandJointInputExpected=true',
    'status=surface-consumer-called',
    'status=lifecycle-check',
    'kuramoto_spatial_activity_markers\.log',
    'particleSurfaceConsumerCalled',
    'nativeSurfaceStartRequested',
    'VALIDATION_STUDY_CONDITION_ID = "lche"',
    'prioritizeConditionForValidation\(VALIDATION_STUDY_CONDITION_ID\)',
    'openXrProbe\.openXrInstanceHandle',
    'openXrProbe\.openXrSessionHandle',
    'openXrProbe\.openXrGetInstanceProcAddrHandle',
    'SurfaceParticleControlState',
    'SurfaceParticleControls',
    'NativeParticleSlider',
    'AndroidView',
    'PolarSensorPanel',
    'ensurePolarSensorPanel',
    'onRequestPermissionsResult',
    'appendPolarEvent',
    'polar-panel-close',
    'streamMirror=kuramoto-experiment-store',
    'PanelModeControls',
    'KuramotoPanelLauncher',
    'setWorkflowPanelVisible',
    'setPanelHeadlocked',
    'panel-headlock-toggle',
    'resizeWorkflowPanel',
    'resetWorkflowPanelPlacement',
    'panelStateToken',
    'spatial-sdk-workflow-panel-open',
    'spatial-sdk-particle-view-panel-closed',
    'particleLayerRenderContinuity=kept-running',
    'launcherPanelRegistrationId=kuramoto_panel_launcher',
    'workflowPanelVisible',
    'launcherPanelVisible',
    'StereoMode\.LeftRight',
    'PARTICLE_LAYER_STEREO_MODE',
    'perEyeExtent',
    'packedExtent',
    'computeParameterBridge=true',
    'transport=jni-live-queue',
    'driver0Value01',
    'driver1Value01',
    'pointScale',
    'applyExperimentBlockToParticleControls',
    'experiment-condition-parameter-handoff',
    'experiment-block-start',
    'experiment-ready-next-block',
    'panel-first-flow-ready',
    'shouldResetExperimentForPanelFirstLaunch',
    'panel-first-launch-reset',
    'freshSpatialActivityLaunch=true',
    'initialStage=participant',
    'panelFirstExperimentFlow=true',
    'blockStartRequiresPanelClose=true',
    'questionnaireSubmitAutoStartsNextBlock=false',
    'questionnaireDueReopensPanel=true',
    'particleLayerVisibleForPanelMode',
    'panelClosedBeforeHandoff',
    'self-test-experiment-block-start',
    'movementBaseFrequencyHz',
    'movementCoupling',
    'panelMustNotBeAuthority=true',
    'highRatePayloadsAllowed=false',
    'rendererAuthority=native-vulkan-wsi-surface-panel',
    'NativeInteropReceiptResult',
    'SpatialNativeInteropProbe',
    'NativeInteropSurfaceProbeResult',
    'SpatialSDKExperimentalAPI',
    '@OptIn\(SpatialSDKExperimentalAPI::class\)',
    'PanelSurface\(scene, 64, 64, 1, SamplerConfig\(\), true, false, "", false\)',
    'scene\.getRuntimeName\(\)',
    'scene\.getOpenXrInstanceHandle\(\)',
    'scene\.getOpenXrSessionHandle\(\)',
    'scene\.getOpenXrGetInstanceProcAddrHandle\(\)',
    'native-interop-probe',
    'native-interop-receipt',
    'native-surface-particle-layer',
    'native-vulkan-wsi-surface-panel',
    'nativeReceiptMask',
    'nativeReceiptOpenXrInstanceHandleNonZero',
    'nativeReceiptOpenXrGetInstanceProcAddrCallable',
    'nativeReceiptXrGetInstancePropertiesResolved',
    'nativeReceiptXrGetInstancePropertiesSucceeded',
    'nativeReceiptXrGetSystemResolved',
    'nativeReceiptXrVulkanGraphicsRequirements2Succeeded',
    'nativeReceiptXrCreateVulkanInstanceResolved',
    'nativeReceiptVkInstanceCreated',
    'nativeReceiptVkGraphicsDeviceObtained',
    'nativeReceiptVkGraphicsComputeQueueFound',
    'nativeReceiptVkDeviceCreated',
    'nativeReceiptVkQueueObtained',
    'nativeReceiptVkObjectsDestroyed',
    'renderPolicy',
    'no-render',
    'surfaceProbeStatus',
    'created-destroyed-no-render',
    'onSceneTick\(\)',
    'scene\.getViewerPose\(\)',
    'scene\.getEyeOffsets\(\)',
    'Quaternion\.fromDirection\(forward, up\)',
    'headlockedPanelPoseFromViewer',
    'updateWorkflowPanelHeadlockFromViewer',
    'pollPanelHeadlockHotload',
    'persistPanelHeadlockTuning',
    'kuramoto_spatial_panel_headlock_tuning\.json',
    'headlockedPanelEnabled=\$\{panelPlacement\.headlocked\}',
    'headlockedPanelDefaultEnabled=true',
    'status=headlocked-pose-updated',
    'status=headlock-hotload-updated',
    'dispatchGenericMotionEvent',
    'applyPanelHeadlockJoystickInput',
    'MotionEvent\.AXIS_X',
    'MotionEvent\.AXIS_RY',
    'InputDevice\.SOURCE_JOYSTICK',
    'status=headlock-joystick-adjusted',
    'controllerJoystickMapping=left-stick-x-y-offset-right-stick-y-distance-right-stick-x-scale',
    'headlockedPanelJoystickTranslateRateProperty',
    'AvatarSystem',
    'setShowHands\(false\)',
    'builtInMetaHandVisualPolicy=disabled',
    'status=projection-plane-updated',
    'projectionPlaneFacingMode=viewer-forward-front-face',
    'viewerPoseSource=Scene\.getViewerPose',
    'Transform\(panelPose\(\)\)',
    'Transform\(panelLauncherPose\(\)\)',
    'Scale\(Vector3',
    'PANEL_WIDTH_METERS = 1\.20f',
    'PANEL_HEIGHT_METERS = 1\.254f',
    'PANEL_FOCUS_Z_METERS = 0\.475f',
    'PANEL_RESIZE_STEP_METERS = 0\.12f',
    'PANEL_HEADLOCK_OFFSET_X_METERS = 0\.0f',
    'PANEL_HEADLOCK_OFFSET_Y_METERS = 0\.0f',
    'PANEL_HEADLOCK_DISTANCE_METERS = 1\.40f',
    'PANEL_HEADLOCK_SCALE = 0\.65f',
    'PANEL_HEADLOCK_ENABLED_PROPERTY =',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.enabled',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.distance_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.scale',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.enabled',
    'PANEL_LAUNCHER_WIDTH_METERS = 0\.78f',
    'PANEL_LAUNCHER_HEIGHT_METERS = 0\.30f',
    'PARTICLE_LAYER_PER_EYE_WIDTH_PX = 1024',
    'PARTICLE_LAYER_WIDTH_PX = PARTICLE_LAYER_PER_EYE_WIDTH_PX \* 2',
    'PARTICLE_LAYER_HEIGHT_PX = 1024',
    'PARTICLE_LAYER_TARGET_DISTANCE_METERS = 0\.72f',
    'PARTICLE_LAYER_TARGET_DISTANCE_PROPERTY =\s*"debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters"',
    'currentParticleLayerTargetDistanceMeters\(\)',
    'PARTICLE_LAYER_SURFACE_OVERSCAN_SCALE = 1\.35f',
    'PARTICLE_LAYER_SURFACE_OVERSCAN_PROPERTY =\s*"debug\.rustyquest\.kuramoto_spatial\.particle_layer\.surface_overscan_scale"',
    'currentParticleLayerSurfaceOverscanScale\(\)',
    'particleLayerProjectionWidthMeters',
    'particleLayerSurfaceWidthMeters',
    'surface-geometry-hotload-updated',
    'projectionPlanePoseInvariantWithOverscan=true',
    'particleWorldScaleInvariantWithOverscan=true',
    'particleLayerTargetDistanceParameterSource=runtime-hotload-android-property',
    'particleLayerTargetDistanceProperty=\$PARTICLE_LAYER_TARGET_DISTANCE_PROPERTY',
    'particleLayerSurfaceOverscanParameterSource=runtime-hotload-android-property',
    'particleLayerSurfaceOverscanProperty=\$PARTICLE_LAYER_SURFACE_OVERSCAN_PROPERTY',
    'PARTICLE_LAYER_WIDTH_METERS = 1\.44f',
    'PARTICLE_LAYER_HEIGHT_METERS = 1\.44f',
    'PARTICLE_LAYER_X_METERS = 0\.0f',
    'PARTICLE_LAYER_Z_METERS = -0\.72f',
    'PARTICLE_LAYER_PARTICLE_COUNT = 2048',
    'PARTICLE_LAYER_STEREO_MODE = "LeftRight"',
    'PARTICLE_LAYER_PLACEMENT_MODE = "viewer-pose-projection-locked-quad"',
    'PARTICLE_LAYER_PLACEMENT_AUTHORITY = "spatial-sdk-viewer-pose-scene-tick"',
    'PARTICLE_LAYER_TARGET_COORDINATE_SPACE = "spatial-sdk-surface-panel-eye-uv"',
    'PARTICLE_LAYER_TARGET_PROJECTION_SPACE =\s*"spatial-sdk-panel-plane-perspective-projection"',
    'PARTICLE_LAYER_PROJECTION_CONTENT_MAPPING_MODE =\s*"world-to-spatial-sdk-panel-plane-left-right"',
    'PARTICLE_LAYER_TARGET_FOV_TANGENTS = "panel-plane-derived"',
    'PARTICLE_LAYER_TARGET_SURFACE_UV_RECT = "0\.0;0\.0;1\.0;1\.0"',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=\$PARTICLE_LAYER_PLACEMENT_MODE',
    'targetProjectionSpace=\$PARTICLE_LAYER_TARGET_PROJECTION_SPACE',
    'projectionContentMappingMode=\$PARTICLE_LAYER_PROJECTION_CONTENT_MAPPING_MODE',
    'leftTargetSurfaceUvRect=\$PARTICLE_LAYER_TARGET_SURFACE_UV_RECT',
    'NATIVE_RECEIPT_LIBRARY = "kuramoto_spatial_native_receipt"',
    'NATIVE_RECEIPT_XR_GET_INSTANCE_PROPERTIES_SUCCEEDED_BIT',
    'NATIVE_RECEIPT_XR_VULKAN_REQUIREMENTS2_SUCCEEDED_BIT',
    'Color\(0xFFFFF3B0\)',
    'Color\(0xFF0F5F6F\)',
    'Color\(0xFFFF5A1F\)',
    'RUN_WORKFLOW_SELF_TEST',
    'RUN_POLAR_LIVE_VALIDATION',
    'RUN_UI_COMMAND',
    'RUN_SURFACE_TARGET',
    'runPolarLiveValidationIfRequested',
    'runUiCommandIfRequested',
    'runSurfaceTargetActivationIfRequested',
    'ui-command-complete',
    'ui-command-failed',
    'surface-target-activated',
    'startRemoteSurfaceBlock',
    '\$source-block-start',
    '\$source-particle-view',
    'dispatchKeyEvent',
    'pollSpatialControllerPrimaryButton',
    'Query\.where \{ has\(Controller\.id\) \}',
    'ButtonBits\.ButtonA',
    'ControllerType\.CONTROLLER',
    'inputSource=spatial-sdk-controller-component',
    'controller-input-route-ready',
    'controller-input-route-error',
    'android-generic-motion-button',
    'SPATIAL_CONTROLLER_ROUTE_MARKER_INTERVAL_MS',
    'handleControllerPrimaryButton',
    'KEYCODE_BUTTON_A',
    'controller-primary-opened-panel',
    'right-controller-primary-button',
    'polar_scan_seconds',
    'polar_connect_delay_seconds',
    'polar_ecg_seconds',
    'polar-panel-automation-ready',
    'scan-command-issued',
    'connectBestDiscovered\("ecg"\)',
    'channel=polar-live-validation status=complete ecgReceiving=',
    'self-test-complete',
    'self-test-particle-view',
    'self-test-workflow-panel',
    'RUSTY_QUEST_KURAMOTO_SPATIAL',
    'hand_rendering_expected'
) "Spatial activity and panel"

Assert-ContainsTokens $polarSensorPanel @(
    'package io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial',
    'final class PolarSensorPanel',
    'REQUEST_BLE_PERMISSIONS = 9103',
    'MARKER_PREFIX = "RUSTY_QUEST_KURAMOTO_SPATIAL"',
    'CHANNEL = "polar-sensor-panel"',
    'STREAM_EVENTS_FILE = "polar_stream_events\.jsonl"',
    'STATUS_FILE = "polar_sensor_status\.json"',
    'BLUETOOTH_SCAN',
    'BLUETOOTH_CONNECT',
    'ACCESS_FINE_LOCATION',
    'stream\.polar_h10\.hr_rr',
    'stream\.polar_h10\.ecg',
    'stream\.polar_h10\.acc',
    'stream\.polar_h10\.device_status',
    'Direct BLE intake for Polar H10 streams',
    'handleCommand\(String rawCommand\)',
    'select_ecg',
    'connectBestDiscovered\(String preferredPmdMode\)',
    'status=auto-connect-selected',
    'start_ecg',
    'status=ecg-frame',
    'decodeHeartRateMeasurement',
    'decodeEcg',
    'decodeAcc',
    'rusty_quest_spatial_sdk_polar_panel',
    'rusty\.manifold\.stream\.event\.v1',
    'rusty\.quest\.kuramoto_spatial\.polar_sensor_status\.v1',
    'host\.onPolarStreamEvent\(event\)'
) "Polar sensor panel"

Assert-ContainsTokens $nativeReceiptCargo @(
    'name = "kuramoto-spatial-native-receipt"',
    'name = "kuramoto_spatial_native_receipt"',
    'crate-type = \["cdylib"\]',
    'ash = "0\.38"',
    'libc = "0\.2"',
    'openxr-sys = "0\.13\.1"',
    'serde_json = "1"',
    'build = "build\.rs"',
    'unsafe_code = "allow"'
) "native receipt Cargo manifest"

Assert-ContainsTokens $nativeReceiptRust @(
    '__android_log_print',
    'ash::Entry::load',
    'vk::ApplicationInfo',
    'vk::InstanceCreateInfo',
    'vk::DeviceQueueCreateInfo',
    'vk::DeviceCreateInfo',
    'openxr_sys::Instance::from_raw',
    'openxr_sys::pfn::GetInstanceProcAddr',
    'openxr_sys::pfn::GetInstanceProperties',
    'openxr_sys::pfn::GetSystem',
    'openxr_sys::pfn::GetVulkanGraphicsRequirements2KHR',
    'openxr_sys::pfn::CreateVulkanInstanceKHR',
    'openxr_sys::pfn::GetVulkanGraphicsDevice2KHR',
    'openxr_sys::pfn::CreateVulkanDeviceKHR',
    'openxr_sys::InstanceProperties::out',
    'openxr_sys::GraphicsRequirementsVulkanKHR::out',
    'openxr_sys::VulkanInstanceCreateInfoKHR',
    'openxr_sys::VulkanGraphicsDeviceGetInfoKHR',
    'openxr_sys::VulkanDeviceCreateInfoKHR',
    'RUSTY_QUEST_KURAMOTO_SPATIAL_NATIVE',
    'channel=native-interop-receipt',
    'channel=native-vulkan-object-probe',
    'renderPolicy=no-render',
    'xrGetInstanceProperties',
    'xrGetSystem',
    'xrGetVulkanGraphicsRequirements2KHR',
    'xrCreateVulkanInstanceKHR',
    'xrGetVulkanGraphicsDevice2KHR',
    'xrCreateVulkanDeviceKHR',
    'openXrGetInstanceProcAddrCallable',
    'xrGetInstancePropertiesSucceeded',
    'xrGetVulkanGraphicsRequirements2Succeeded',
    'vkInstanceCreated',
    'vkGraphicsDeviceObtained',
    'vkGraphicsComputeQueueFound',
    'vkDeviceCreated',
    'vkQueueObtained',
    'vkObjectsDestroyed',
    'destroy_device',
    'destroy_instance',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeRecordNoRenderInteropReceipt',
    'RECEIPT_OPENXR_INSTANCE_NONZERO',
    'RECEIPT_OPENXR_SESSION_NONZERO',
    'RECEIPT_OPENXR_GET_PROC_NONZERO',
    'RECEIPT_PANEL_SURFACE_VALID',
    'RECEIPT_OPENXR_GET_PROC_CALLABLE',
    'RECEIPT_XR_GET_INSTANCE_PROPERTIES_RESOLVED',
    'RECEIPT_XR_GET_INSTANCE_PROPERTIES_SUCCEEDED',
    'RECEIPT_XR_GET_SYSTEM_SUCCEEDED',
    'RECEIPT_XR_VULKAN_REQUIREMENTS2_SUCCEEDED',
    'RECEIPT_XR_CREATE_VULKAN_INSTANCE_RESOLVED',
    'RECEIPT_XR_GET_VULKAN_GRAPHICS_DEVICE2_RESOLVED',
    'RECEIPT_XR_CREATE_VULKAN_DEVICE_RESOLVED',
    'RECEIPT_VK_INSTANCE_CREATED',
    'RECEIPT_VK_GRAPHICS_DEVICE_OBTAINED',
    'RECEIPT_VK_GRAPHICS_COMPUTE_QUEUE_FOUND',
    'RECEIPT_VK_DEVICE_CREATED',
    'RECEIPT_VK_QUEUE_OBTAINED',
    'RECEIPT_VK_OBJECTS_DESTROYED'
) "native receipt Rust source"

Assert-ContainsTokens $nativeReceiptBuild @(
    'surface_particles\.vert\.glsl',
    'surface_particles\.frag\.glsl',
    'surface_particles\.comp\.glsl',
    'replay_hands\.vert\.glsl',
    'replay_hands\.frag\.glsl',
    'recorded_hand_replay_source\.json',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_FRAME_LIMIT',
    'validation_mesh_jsonl',
    'surface_particles\.comp\.spv',
    '-fshader-stage=\{stage\}',
    'glslc',
    'ANDROID_NDK_HOME',
    'shader-tools'
) "native receipt build script"

Assert-ContainsTokens $nativeReceiptSurfaceLayer @(
    'ANativeWindow_fromSurface',
    'ANativeWindow_release',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeStartSurfaceParticleLayer',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeStopSurfaceParticleLayer',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeUpdateSurfaceParticleParameters',
    '__system_property_get',
    'SURFACE_PARTICLE_LIVE_HAND_DEPTH_OFFSET_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'SURFACE_PARTICLE_DIAGNOSTIC_MODE_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'parse_surface_particle_diagnostic_mode',
    'surface_particle_diagnostic_mode_name',
    'triangle-bands',
    'projection-clamp',
    'particleDiagnosticModeName=',
    'liveHandDepthOffsetParameterSource=runtime-hotload-android-property',
    'liveHandDepthOffsetMeters',
    'target_distance_meters',
    'panelTargetDistanceMeters',
    'ash::khr::android_surface::NAME',
    'ash::khr::swapchain::NAME',
    'vk::QueueFlags::GRAPHICS \| vk::QueueFlags::COMPUTE',
    'vk::DescriptorType::STORAGE_BUFFER',
    'create_descriptor_set_layout',
    'create_particle_descriptor_set',
    'create_buffer_with_memory',
    'create_compute_pipeline',
    'ReplayHandsRenderer::new',
    'LiveHandOpenXrHandles',
    'openxr_instance_handle',
    'openxr_session_handle',
    'openxr_get_instance_proc_addr_handle',
    'update_live_joints_buffer',
    'ReplayHandsRenderer',
    'replay_hands\.marker_fields\(\)',
    'surface_particles\.comp\.spv',
    'cmd_dispatch',
    'cmd_pipeline_barrier',
    'COMPUTE_SHADER',
    'VERTEX_SHADER',
    'surface_particle_stereo_layout',
    'SurfaceParticleStereoLayout',
    'cmd_set_viewport',
    'cmd_set_scissor',
    'sideBySideStereoProof=true',
    'stereoDebugMarkers=false',
    'stereoMode',
    'perEyeExtent',
    'packedExtent',
    'SURFACE_PARTICLE_PROJECTION_MARKERS',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'targetCoordinateSpace=spatial-sdk-surface-panel-eye-uv',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'targetFovTangents=panel-plane-derived',
    'leftTargetSurfaceUvRect=0\.0;0\.0;1\.0;1\.0',
    'rightTargetSurfaceUvRect=0\.0;0\.0;1\.0;1\.0',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'extent\.height as f32 \* 0\.018',
    'transport=jni-live-queue',
    'create_android_surface',
    'create_swapchain',
    'get_swapchain_images',
    'acquire_next_image',
    'queue_present',
    'surface_particles\.vert\.spv',
    'surface_particles\.frag\.spv',
    'channel=native-surface-particle-layer',
    'render-loop-ready',
    'first-frame-presented',
    'native-vulkan-wsi-surface-panel',
    'particleCount',
    'STOP_SURFACE_PARTICLES'
) "native receipt surface particle layer"

Assert-ContainsTokens $nativeReceiptReplayHands @(
    'RECORDED_HAND_REPLAY_JSON',
    'recorded_hand_replay_source\.json',
    'ReplayHandsRenderer',
    'ReplayHandVertex',
    'ReplayHandSkinningVertex',
    'ReplayHandGpuPose',
    'ReplayHandPush',
    'target_distance_meters',
    'external-recorded-capture-build-env',
    'public-shape-fallback',
    'validation_mesh_jsonl',
    'triangle_indices',
    'bind_vertices',
    'vertex_blend_indices',
    'vertex_blend_weights',
    'bind_normals',
    'bind_normal',
    'bind_joint_sources',
    'HAND_MESH_COMPONENT_POLICY',
    'keep_two_largest_components_drop_wrist_bridge_boundaries_v1',
    'HAND_MESH_KEPT_COMPONENT_RANK_COUNT',
    'component_filtered_triangles',
    'analyze_mesh_components',
    'MeshComponentSummary',
    'component_marker_fields',
    'native-kuramoto-study-hand-mesh-components',
    'native-kuramoto-study-left-hand-mesh-components',
    'native-kuramoto-study-right-hand-mesh-components',
    'liveMeshSurfacePolicy=',
    'liveMeshComponentRank0=hand-inside',
    'liveMeshComponentRank1=hand-back',
    'liveMeshComponentRank2=wrist-cap',
    'liveMeshWristCapPolicy=drop-component-rank-2',
    'liveMeshNormalFallbackPolicy=skinned-bind-normal-for-small-triangle-area',
    'HandMeshSamplingTriangleCount=',
    'HandMeshDroppedTriangleCount=',
    'native-kuramoto-study-particles-ready',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandGpuSkinningParticles=true',
    'jointClusterMode=false',
    'compactJointSkinningKernel=true',
    'compactJointPoseUploadPerFrame=true',
    'jointMatrixUploadPerFrame=false',
    'privateKuramotoPayloadActive=false',
    'studyProfileDynamicsActive=true',
    'kuramotoConditionId=',
    'kuramotoStudyProfileId=',
    'kuramotoMovementBaseHz=',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'KURAMOTO_STUDY_PARTICLES_PER_HAND',
    'PARTICLE_VERTICES_PER_INSTANCE',
    'REPLAY_HAND_IPD_METERS',
    'REPLAY_HAND_HEAD_Y_METERS',
    'REPLAY_HAND_HEAD_Z_METERS',
    'vk::PrimitiveTopology::TRIANGLE_LIST',
    'replay_hands\.vert\.spv',
    'replay_hands\.frag\.spv',
    'cmd_draw'
) "native receipt replay hand renderer"

Assert-ContainsTokens $nativeReceiptLiveHandJoints @(
    'XR_EXT_hand_tracking',
    'XR_KHR_convert_timespec_time_CLOCK_MONOTONIC',
    'LiveHandOpenXrHandles',
    'LiveHandJointRow',
    'LIVE_HAND_ROW_COUNT',
    '__system_property_get',
    'xrCreateHandTrackerEXT',
    'xrLocateHandJointsEXT',
    'xrLocateViews',
    'xrCreateReferenceSpace',
    'xrConvertTimespecTimeToTimeKHR',
    'clock_gettime',
    'recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandJointPlacementMode=viewer-relative-openxr-to-spatial-sdk-panel-plane',
    'liveHandCoordinateTransform=',
    'viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'raw-openxr-local-floor-to-spatial-sdk-scene-fallback',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'LIVE_HAND_SCENE_OFFSET_Z_PROPERTY',
    'LIVE_HAND_SCENE_YAW_DEGREES_PROPERTY',
    'LIVE_HAND_SCENE_HORIZONTAL_SIGN_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'current_live_hand_scene_transform',
    'apply_live_hand_scene_transform',
    'store_live_hand_panel_basis',
    'current_view_panel_mapping',
    'apply_live_hand_view_panel_mapping',
    'ViewConfigurationType::PRIMARY_STEREO',
    'poll_live_hand_scene_sign_property',
    'multiply_quat_xyzw',
    'live-hand-scene-transform-hotload-updated',
    'liveHandSceneHorizontalSignDefault=-1.000',
    'liveHandPoseOrientationUpload=true',
    'liveHandJointStatusY=pose-valid',
    'liveHandCompactUploadEquivalent=true',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveHandRuntimeJointPoseCount=',
    'liveHandTipLengthCount=',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'LIVE_HAND_COMPACT_RUNTIME_OPENXR_JOINTS',
    'LIVE_HAND_COMPACT_TIP_OPENXR_PAIRS',
    'liveHandJointFrameReady',
    'liveHandFallbackToReplay',
    'liveHandCorrectPositionSizeProof=spatial-sdk-panel-plane-projection'
) "native receipt live hand joint source"

Assert-ContainsTokens $nativeReceiptComputeShader @(
    'layout\(local_size_x = 64',
    'layout\(set = 0, binding = 0, std430\) buffer ParticleBuffer',
    'ParticleRow',
    'driver0Value01',
    'driver1Value01',
    'pointScale',
    'particleBuffer\.particles\[index\]\.positionSize',
    'particleBuffer\.particles\[index\]\.color'
) "native receipt surface particle compute shader"

Assert-ContainsTokens $nativeReceiptVertexShader @(
    'float eyeIndex = clamp\(pc\.reserved0',
    'index < 32u',
    'markerColor',
    'eyeTint',
    'gl_Position = vec4\(markerX, markerY',
    'outColor = vec4\(tinted, particle\.color\.a\)'
) "native receipt surface particle vertex shader"

Assert-ContainsTokens $nativeReceiptReplayHandVertexShader @(
    'ReplayHandVertex',
    'ReplayHandVertexBuffer',
    'LiveHandJointBuffer',
    'SkinningVertex',
    'SkinningVertexBuffer',
    'SkinningTriangleBuffer',
    'BindJointPoseBuffer',
    'BindJointSourceBuffer',
    'ReplayHandPush',
    'eyeIndex',
    'liveFrameReady',
    'pc\.dynamics',
    'pc\.profile',
    'pc\.liveAdjust',
    'LIVE_MESH_TRIANGLE_VALIDATION_ATTEMPTS',
    'bindNormal',
    'transform_joint_normal',
    'skin_normal_at',
    'fallbackNormal',
    'triangle\.w >= 2u',
    'diagnosticMode',
    'degenerateTriangle',
    'particle\.debug0',
    'particle\.debug1',
    'projectionDiagnosticVisible',
    'transform_joint\(joints\.x, vertex\.bindPosition\) \* weights\.x',
    'valid = true',
    'weighted / totalWeight',
    'particle\.center -= panelForward \* pc\.liveAdjust\.x',
    'OPENXR_HAND_JOINT_COUNT',
    'BIND_JOINT_COUNT_PER_HAND',
    'anchor_barycentric',
    'openxr_joint_for_runtime',
    'tip_length_at',
    'current_bind_joint_pose',
    'skin_vertex_at',
    'live_mesh_particle',
    'gl_InstanceIndex',
    'QUAD_POSITIONS',
    'pc\.projection\.w',
    'tangent',
    'gl_Position'
) "native receipt replay hand vertex shader"

Assert-ContainsTokens $nativeReceiptReplayHandFragmentShader @(
    'inMaskUv',
    'softMask',
    'outColor',
    'vec4\(rgb \* alpha, alpha\)'
) "native receipt replay hand fragment shader"

Assert-ContainsTokens $liveHandSceneTransformTool @(
    'rusty\.quest\.kuramoto_spatial_live_hand_scene_transform_set\.v1',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Pass -Serial or set RUSTY_QUEST_SERIAL',
    'adb setprop',
    'adb getprop'
) "live hand scene-transform hotload tool"

Assert-ContainsTokens $panelHeadlockTool @(
    'rusty\.quest\.kuramoto_spatial_panel_headlock_set\.v1',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.enabled',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.distance_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.width_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.height_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.scale',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.enabled',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.translate_rate_mps',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.distance_rate_mps',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.scale_rate_per_second',
    'files/kuramoto_spatial_panel_headlock_tuning\.json',
    'Pass -Serial or set RUSTY_QUEST_SERIAL',
    'shell", "setprop"',
    'shell", "getprop"',
    'exec-out", "run-as"'
) "panel headlock hotload tool"

Assert-ContainsTokens $uiActionTool @(
    'rusty\.quest\.kuramoto_spatial_ui_action_invoked\.v1',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_UI_COMMAND',
    'panel-open',
    'panel-close',
    'panel-reset',
    'panel-headlock-on',
    'panel-headlock-off',
    'panel-headlock-toggle',
    'panel-adjust',
    'panel-resize',
    'particle-controls',
    'participant-reset',
    'participant-begin',
    'polar-setup-save',
    'surface-select',
    'start-block',
    'surface-target-activate',
    'questionnaire-submit',
    'surface_target_id',
    'delta_width',
    'point_scale',
    'comfort_rating',
    'ReadMarkers',
    'files/kuramoto_spatial_activity_markers\.log'
) "Spatial UI action wrapper"

Assert-ContainsTokens $store @(
    'QUESTIONNAIRE_SCHEMA = "rusty\.kuramoto\.mesh\.experiment_questionnaire\.v2"',
    'DEFAULT_BLOCK_DURATION_MS = 10_000L',
    'fun prioritizeConditionForValidation\(conditionId: String\)',
    'fun recordPanelForegroundState\(panelState: String, source: String\)',
    'fun appendPolarEvent\(event: JSONObject\)',
    'fun startNextBlock\(\): ActiveBlockSnapshot\?',
    'spatial-sdk-direct-ble-panel',
    'live_polar_intake',
    'polar-stream-event-recorded',
    'ecgMirrored',
    'kuramoto_experiment',
    'stream\.polar_h10\.ecg',
    'stream\.polar_h10\.device_status',
    'spatial_polar_setup',
    'spatial-sdk-workflow-panel-open',
    'panel_state_source',
    'spatial_panel_state_changed',
    'validation-condition-prioritized',
    'validation_condition_prioritized',
    'participant_id',
    'session_id',
    'block_index',
    'block_number',
    'condition_id',
    'profile_id',
    'movement_base_frequency_hz',
    'movement_coupling',
    'movementBaseFrequencyHz',
    'movementCoupling',
    'surface_target_id',
    '"signature"',
    'questionnaire_results\.jsonl',
    'polar_events\.jsonl',
    'ecg_events\.jsonl',
    'lcle',
    'lche',
    'hcle',
    'hche',
    'real-hands',
    'gpu-replay-hands',
    'icosphere'
) "experiment store"

Assert-ContainsTokens $buildScript @(
    'NdkHome = \$env:ANDROID_NDK_HOME',
    'RecordedHandCaptureDir = \$env:RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RecordedHandFrameLimit = 24',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_FRAME_LIMIT',
    'gradle-\$Version-bin\.zip',
    'services\.gradle\.org',
    'CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER',
    'aarch64-linux-android',
    'generated\\rustJniLibs',
    'lib/arm64-v8a/libkuramoto_spatial_native_receipt\.so',
    'Test-ZipEntry',
    'GRADLE_USER_HOME',
    ':app:assembleDebug',
    'rusty-quest-kuramoto-spatial-sdk\.apk',
    'rusty\.quest\.kuramoto_spatial_sdk_android\.build_manifest\.v1',
    'high_rate_json_payload = \$false',
    'hand_rendering_expected = \$true',
    'native_interop_probe = "spatial-sdk-openxr-handles-and-panelsurface-capability"',
    'native_interop_probe_rendering = "no-render"',
    'native_interop_probe_surface = "PanelSurface-create-destroy"',
    'native_receipt_probe = "rust-jni-openxr-handle-and-panelsurface-receipt"',
    'native_receipt_openxr_probe = "xrGetInstanceProperties-vulkan-requirements-and-no-present-vulkan-objects-through-sdk-getInstanceProcAddr"',
    'native_receipt_vulkan_object_probe = "no-present-instance-device-queue-create-destroy"',
    'native_receipt_mask_bits = @\(',
    'xrGetVulkanGraphicsRequirements2KHR-succeeded',
    'xrCreateVulkanInstanceKHR-resolved',
    'vk-instance-created',
    'vk-device-created',
    'vk-objects-destroyed',
    'native_receipt_jni_bridge = "KuramotoSpatialActivity\.nativeRecordNoRenderInteropReceipt"',
    'native_receipt_library_packaged = \$nativeReceiptLibraryPackaged',
    'native_surface_particle_layer = "VideoSurfacePanelRegistration-native-vulkan-wsi-surface-panel"',
    'native_surface_particle_layer_rendering = "native-vulkan-wsi-surface-panel-live-openxr-gpu-skinned-resident-rig-kuramoto-study-hand-anchor-particles-packed-stereo-left-right"',
    'native_surface_particle_layer_jni_bridge = "KuramotoSpatialActivity\.nativeStartSurfaceParticleLayer"',
    'native_surface_particle_layer_parameter_bridge = "KuramotoSpatialActivity\.nativeUpdateSurfaceParticleParameters"',
    'native_surface_particle_layer_parameter_transport = "jni-live-queue"',
    'experiment_condition_parameter_bridge = "KuramotoSpatialActivity\.applyExperimentBlockToParticleControls-to-nativeUpdateSurfaceParticleParameters"',
    'experiment_condition_driver_mapping = "movement_base_frequency_hz-to-driver0-energy;movement_coupling-to-driver1-coherence"',
    'experiment_mode_flow = "panel-first-workflow-then-explicit-panel-close-starts-particle-block"',
    'experiment_condition_panel_transition = "setWorkflowPanelVisible\(false,false,source=experiment-block-start\)-before-startNextBlock"',
    'experiment_questionnaire_next_block_policy = "questionnaire-submit-keeps-panel-open-ready_next_block-explicit-start"',
    'experiment_surface_modes = @\("real-hands", "gpu-replay-hands", "icosphere"\)',
    'experiment_condition_high_rate_policy = "condition-metadata-and-bounded-scalars-only"',
    'native_surface_particle_layer_hotload_property = "debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters"',
    'native_surface_particle_layer_live_hand_depth_offset_default_meters = 0\.0',
    'native_surface_particle_layer_live_hand_scene_transform = "viewer-relative-openxr-to-spatial-sdk-panel-basis"',
    'native_surface_particle_layer_live_hand_scene_fallback_transform = "raw-openxr-local-floor-to-spatial-sdk-scene"',
    'native_surface_particle_layer_live_hand_scene_transform_source = "runtime-hotload-android-property"',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'native_surface_particle_layer_live_hand_scene_offset_default_meters = "0\.0;0\.0;2\.0"',
    'native_surface_particle_layer_live_hand_scene_yaw_default_degrees = 180\.0',
    'native_surface_particle_layer_live_hand_scene_horizontal_sign_default = -1\.0',
    'native_surface_particle_layer_target_distance_hotload_property = "debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters"',
    'native_surface_particle_layer_target_distance_default_meters = 0\.72',
    'native_surface_particle_layer_target_distance_range_meters = "0\.20\.\.1\.50"',
    'forced_replay_hand_source_mode',
    'forced_replay_hand_frame_limit',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandJointFrameSource=XR_EXT_hand_tracking',
    'liveHandJointGpuInputPath=recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandJointPlacementMode=viewer-relative-openxr-to-spatial-sdk-panel-plane',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'liveHandSceneOffsetDefaultM=0\.000;0\.000;2\.000',
    'liveHandSceneYawDefaultDegrees=180\.000',
    'liveHandSceneHorizontalSignDefault=-1\.000',
    'liveHandCompactUploadEquivalent=true',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveHandRuntimeJointPoseCount=',
    'liveHandTipLengthCount=',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandCorrectPositionSizeProof=spatial-sdk-panel-plane-projection',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'liveHandDepthOffsetParameterSource=runtime-hotload-android-property',
    'liveHandDepthOffsetProperty=debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'particleLayerTargetDistanceParameterSource=runtime-hotload-android-property',
    'particleLayerTargetDistanceProperty=debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'privateKuramotoPayloadActive=false',
    'studyProfileDynamicsActive=true',
    'kuramotoConditionId=lche',
    'kuramotoStudyProfileId=kuramoto.private.native.profile.high-energy-low-coherence.movement-only.v1',
    'kuramotoMovementBaseHz=0.88',
    'kuramotoMovementCoupling=0.0',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'native-surface-compute-stereo-proof=true',
    'sideBySideStereoProof=true',
    'stereoMode=LeftRight',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=viewer-pose-projection-locked-quad',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'width_px = 2048',
    'per_eye_width_px = 1024',
    'height_px = 1024',
    'stereo_mode = "StereoMode\.LeftRight"',
    'packed_stereo_layout = "left-right"',
    'width_meters = 1\.44',
    'height_meters = 1\.44',
    'target_distance_meters = 0\.72',
    'x_meters = 0\.0',
    'z_meters = -0\.72',
    'placement_authority = "spatial-sdk-viewer-pose-scene-tick"',
    'target_coordinate_space = "spatial-sdk-surface-panel-eye-uv"',
    'target_projection_space = "spatial-sdk-panel-plane-perspective-projection"',
    'target_fov_tangents = "panel-plane-derived"',
    'left_target_surface_uv_rect = "0\.0;0\.0;1\.0;1\.0"',
    'first-frame-presented',
    'particle_surface_panel_registration_id = "kuramoto_particle_surface_panel"',
    'polar_sensor_panel = "spatial-sdk-direct-ble-panel"',
    'polar_sensor_permissions = @\(',
    'android\.permission\.BLUETOOTH_CONNECT',
    'android\.permission\.BLUETOOTH_SCAN',
    'polar_sensor_streams = @\(',
    'stream\.polar_h10\.ecg',
    'polar_sensor_event_mirror = "KuramotoExperimentStore\.appendPolarEvent-to-polar_events-jsonl-and-ecg_events-jsonl"',
    'polar_sensor_high_rate_policy = "ble-stream-decoded-in-panel-not-renderer-json"',
    'polar_live_validation_action = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_POLAR_LIVE_VALIDATION"',
    'polar_live_validation_wrapper = "tools/Invoke-KuramotoSpatialSdkAndroidPolarLive\.ps1"',
    'polar_live_validation_required_markers = @\(',
    'polar-live-validation status=polar-panel-automation-ready',
    'polar-live-validation status=scan-command-issued',
    'polar-sensor-panel status=pmd-started mode=ecg',
    'polar-sensor-panel status=ecg-frame',
    'polar_live_validation_app_private_files = @\(',
    'polar_stream_events\.jsonl',
    'panel_launcher_registration_id = "kuramoto_panel_launcher"',
    'spatial_panel_mode = "workflow-panel-open-or-particle-view-panel-closed"',
    'spatial_panel_mode_transition = "Visible\(false\)-workflow-panel-with-launcher-reopen"',
    'spatial_panel_mode_renderer_continuity = "native-vulkan-surface-particle-layer-kept-running"',
    'spatial_panel_focus_pose_meters = "0\.0;1\.1;0\.475"',
    'spatial_panel_surface_target_activation_action = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_SURFACE_TARGET"',
    'spatial_panel_ui_action = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_UI_COMMAND"',
    'spatial_panel_ui_action_wrapper = "tools/Invoke-KuramotoSpatialSdkAndroidUiAction\.ps1"',
    'spatial_panel_ui_actions = @\(',
    'surface-target-activate',
    'questionnaire-submit',
    'spatial_panel_debug_controller_reopen = "right-controller-primary-button-SpatialSDK-Controller-ButtonA-plus-Android-KeyEvent-and-motion-fallback-opens-workflow-panel-when-closed"',
    'spatial_panel_headlock_mode = "enabled-by-default-viewer-relative-while-workflow-panel-open"',
    'spatial_panel_headlock_default_pose_meters = "0\.0;0\.0;1\.40"',
    'spatial_panel_headlock_default_scale = 0\.65',
    'spatial_panel_headlock_hotload_tool = "tools/Set-KuramotoSpatialPanelHeadlock\.ps1"',
    'spatial_panel_headlock_hotload_properties = @\(',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.enabled',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.distance_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.scale_rate_per_second',
    'spatial_panel_headlock_joystick_controls = "android-generic-motion-left-stick-x-y-offset-right-stick-y-distance-right-stick-x-scale"',
    'spatial_panel_headlock_tuning_file = "files/kuramoto_spatial_panel_headlock_tuning\.json"',
    'diagnostic_backdrop = "disabled-vulkan-carrier-is-user-facing-surface"',
    'panel_content_probe = "sample-quaternion-opaque-yellow-background-teal-banner-orange-button"'
) "build wrapper"

Assert-ContainsTokens $selfTestTool @(
    'RUSTY_QUEST_SERIAL',
    'adb_serial_required = \$true',
    'device-scoped-adb',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_WORKFLOW_SELF_TEST',
    'install", "-r", "-d", "-g"',
    '"am"',
    '"start"',
    '"-W"',
    '"--es"',
    '"participant_id"',
    '"surface_target_id"',
    'logcat", "-d", "-v", "time", "--pid"',
    'tag-logcat\.txt',
    'evidence-summary\.json',
    'files/kuramoto_experiment_session\.json',
    'session_manifest\.json',
    'block_events\.jsonl',
    'foreground_events\.jsonl',
    'polar_events\.jsonl',
    'ecg_events\.jsonl',
    'questionnaire_results\.jsonl',
    'condition_handoff_marker',
    'self_test_condition_handoff_marker',
    'parameter_submit_self_test_marker',
    'panel_closed_for_self_test',
    'workflow_panel_reopen_marker',
    'panel_registration_count_3',
    'polar_setup_recorded',
    'polar_panel_created',
    'polar_stream_mirror_registered',
    'particle_surface_start_requested',
    'particle_surface_panel_ready',
    'lifecycle_particle_layer_started',
    'render_loop_ready',
    'first_frame_presented',
    'self_test_complete',
    'block_events_block_started',
    'block_events_block_elapsed',
    'block_events_questionnaire_submitted',
    'foreground_events_panel_closed',
    'foreground_events_panel_reopened',
    'polar_events_setup_row',
    'questionnaire_result_row',
    'AndroidRuntime',
    'render-failed',
    'AllowMissingPolarPanelCreated',
    'Kuramoto Spatial SDK self-test evidence'
) "headset self-test wrapper"

Assert-ContainsTokens $polarLiveTool @(
    'RUSTY_QUEST_SERIAL',
    'adb_serial_required = \$true',
    'device-scoped-adb',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial\.action\.RUN_POLAR_LIVE_VALIDATION',
    'install", "-r", "-d", "-g"',
    'android\.permission\.BLUETOOTH_SCAN',
    'android\.permission\.BLUETOOTH_CONNECT',
    'android\.permission\.ACCESS_FINE_LOCATION',
    '"am"',
    '"start"',
    '"-W"',
    '"--es"',
    '"participant_id"',
    '"surface_target_id"',
    '"--ei"',
    '"polar_scan_seconds"',
    '"polar_connect_delay_seconds"',
    '"polar_ecg_seconds"',
    'logcat", "-d", "-v", "time", "--pid"',
    'tag-logcat\.txt',
    'evidence-summary\.json',
    'files/polar_sensor_status\.json',
    'files/polar_stream_events\.jsonl',
    'files/kuramoto_spatial_activity_markers\.log',
    'clear-app-private-live-polar\.txt',
    '"rm", "-f", \$privateFile',
    'files/kuramoto_experiment_session\.json',
    'polar_events\.jsonl',
    'ecg_events\.jsonl',
    'live_validation_started',
    'polar_panel_created',
    'polar_panel_ready',
    'polar_panel_automation_ready',
    'select_ecg_command',
    'scan_started',
    'scan_command_issued',
    'device_found',
    'auto_connect_selected',
    'connected',
    'pmd_ready',
    'pmd_started_ecg',
    'ecg_frame_marker',
    'live_validation_complete_receiving',
    'store_ecg_mirror_marker',
    'root_polar_stream_events_ecg',
    'polar_events_ecg_row',
    'ecg_events_stream_row',
    'AllowMissingLivePolar',
    'AndroidRuntime',
    'render-failed',
    'Kuramoto Spatial SDK live Polar evidence'
) "live Polar headset wrapper"

Assert-ContainsTokens $depthOffsetTool @(
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_live_hand_depth_offset_set\.v1',
    'requested_meters',
    'applied_meters'
) "live hand depth-offset hotload tool"

Assert-ContainsTokens $targetDistanceTool @(
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_particle_layer_target_distance_set\.v1',
    'requested_meters',
    'applied_meters'
) "particle layer target-distance hotload tool"

Assert-ContainsTokens $overscanTool @(
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.surface_overscan_scale',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_particle_layer_overscan_set\.v1',
    'requested_scale',
    'applied_scale'
) "particle layer overscan hotload tool"

Assert-ContainsTokens $diagnosticModeTool @(
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_particle_diagnostic_mode_set\.v1',
    'requested_mode',
    'applied_mode'
) "particle diagnostic mode hotload tool"

Assert-ContainsTokens $readme @(
    'separate Meta Spatial SDK lane',
    'does not replace the native renderer APK',
    'libkuramoto_spatial_native_receipt\.so',
    'nativeRecordNoRenderInteropReceipt',
    'xrGetInstanceProperties',
    'xrGetVulkanGraphicsRequirements2KHR',
    'RUSTY_QUEST_KURAMOTO_SPATIAL_NATIVE',
    'nativeUpdateSurfaceParticleParameters',
    'compute-written\s+storage buffer',
    'native Kuramoto study hand-anchor particle draw path',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'StereoMode\.LeftRight',
    'packed extent `2048x1024`',
    'per-eye extent\s+`1024x1024`',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandJointGpuInputPath=recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Set-KuramotoSpatialLiveHandSceneTransform\.ps1',
    'Set-KuramotoSpatialPanelHeadlock\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.enabled',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.distance_meters',
    'debug\.rustyquest\.kuramoto_spatial\.panel\.headlocked\.joystick\.scale_rate_per_second',
    'files/kuramoto_spatial_panel_headlock_tuning\.json',
    'Android generic-motion controller input maps left stick to panel x/y offset',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'particleDiagnosticModeProperty=debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'Set-KuramotoSpatialParticleDiagnosticMode\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Set-KuramotoSpatialLiveHandDepthOffset\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Set-KuramotoSpatialParticleLayerTargetDistance\.ps1',
    'Invoke-KuramotoSpatialSdkAndroidSelfTest\.ps1',
    'RUN_WORKFLOW_SELF_TEST',
    'Invoke-KuramotoSpatialSdkAndroidUiAction\.ps1',
    'RUN_UI_COMMAND',
    'surface-target-activate',
    'questionnaire-submit',
    'Spatial SDK `Controller` component',
    'ButtonBits\.ButtonA',
    'KEYCODE_BUTTON_A',
    'inputSource',
    'Invoke-KuramotoSpatialSdkAndroidPolarLive\.ps1',
    'RUN_POLAR_LIVE_VALIDATION',
    'polar_sensor_status\.json',
    'polar_stream_events\.jsonl',
    'evidence-summary\.json',
    'privateKuramotoPayloadActive=false',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'native-surface-compute-stereo-proof=true',
    'stereoMode=LeftRight',
    'perEyeExtent=1024x1024',
    'packedExtent=2048x1024',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=viewer-pose-projection-locked-quad',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial/\.KuramotoSpatialActivity',
    'target/kuramoto-spatial-sdk-android/rusty-quest-kuramoto-spatial-sdk\.apk'
) "app README"

Assert-ContainsTokens $plan @(
    'Initial Hypothesis',
    'Resources Consulted',
    'Architecture Decisions',
    'Iteration Log',
    'Final Build/Run Recipe',
    'Remaining Risks And Follow-Ups',
    'apps/kuramoto-spatial-sdk-android',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial',
    'Foreground coexistence boundary',
    'native_frame_like_after_spatial_count=0',
    'same native process id',
    'simultaneous overlay over the current NativeActivity renderer',
    'single-immersive-owner architecture',
    'native receipt probe',
    'libkuramoto_spatial_native_receipt\.so',
    'nativeRecordNoRenderInteropReceipt',
    'OpenXR handle-usability',
    'OpenXR Vulkan capability',
    'xrGetInstanceProperties',
    'xrGetVulkanGraphicsRequirements2KHR',
    'xrCreateVulkanInstanceKHR',
    'VR-ready native receipt mask\s+was `2097151`',
    'Adreno__TM__740',
    'native-vulkan-object-probe',
    'no-present Vulkan',
    'Panel-to-native parameter boundary',
    'compute-resource parity source slice',
    'nativeUpdateSurfaceParticleParameters',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'headlocked workflow panel mode',
    'tools/Set-KuramotoSpatialPanelHeadlock\.ps1',
    'files/kuramoto_spatial_panel_headlock_tuning\.json',
    'native Vulkan particle layer embedded in Spatial SDK world',
    'VideoSurfacePanelRegistration',
    'SceneSwapchain\.createAsAndroid',
    'Scene\.createQuadLayer',
    'ANativeWindow',
    'xrWaitFrame',
    'onSceneTick',
    'native-surface-compute-stereo-proof',
    'StereoMode\.LeftRight',
    'per-eye extent `1024x1024`',
    'packed surface extent\s+`2048x1024`',
    'viewer-pose-projection-locked-quad',
    'spatial-sdk-panel-plane-perspective-projection',
    'spatial-sdk-surface-panel-eye-uv',
    'world-to-spatial-sdk-panel-plane-left-right',
    'resident rig live-skinning correction',
    'live skinning robustness and diagnostic depth hotload',
    'live hand raw-to-scene transform correction',
    'live hand viewer-relative panel-basis correction',
    'recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Set-KuramotoSpatialLiveHandSceneTransform\.ps1',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Set-KuramotoSpatialLiveHandDepthOffset\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Set-KuramotoSpatialParticleLayerTargetDistance\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.surface_overscan_scale',
    'Set-KuramotoSpatialParticleLayerOverscan\.ps1',
    'Invoke-KuramotoSpatialSdkAndroidSelfTest\.ps1',
    'Invoke-KuramotoSpatialSdkAndroidPolarLive\.ps1',
    'RUN_POLAR_LIVE_VALIDATION',
    'polar-live-validation',
    'ecgReceiving=true',
    'polar_stream_events\.jsonl',
    'projectionWidthMeters',
    'surfaceWidthMeters',
    'projectionPlanePoseInvariantWithOverscan=true',
    'particleWorldScaleInvariantWithOverscan=true',
    'AvatarSystem\.setShowHands\(false\)',
    'explicit-only base hand mesh policy',
    'Open Questions For Meta Or SDK Reference Checks'
) "implementation plan"

Write-Host "Rusty Quest Kuramoto Spatial SDK Android static validation passed"
