param(
    [string]$RepoRoot
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
}
$repoRootPath = Resolve-Path $RepoRoot
$appRoot = Join-Path $repoRootPath "apps\kuramoto-spatial-sdk-android"
$sourceRoot = Join-Path $appRoot "app\src\main\java\io\github\mesmerprism\rustyquest\kuramoto_spatial"

function Read-RequiredText {
    param(
        [string]$Path,
        [string]$Label
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Missing Kuramoto Spatial SDK static file ($Label): $Path"
    }
    return Get-Content -Raw -LiteralPath $Path
}

function Assert-ContainsTokens {
    param(
        [string]$Text,
        [string[]]$Tokens,
        [string]$Label
    )
    foreach ($token in $Tokens) {
        if ($Text -notmatch $token) {
            throw "Kuramoto Spatial SDK static check failed for ${Label}: missing token: $token"
        }
    }
}

$settings = Read-RequiredText (Join-Path $appRoot "settings.gradle.kts") "settings"
$rootBuild = Read-RequiredText (Join-Path $appRoot "build.gradle.kts") "root build"
$gradleProperties = Read-RequiredText (Join-Path $appRoot "gradle.properties") "Gradle properties"
$versions = Read-RequiredText (Join-Path $appRoot "gradle\libs.versions.toml") "version catalog"
$appBuild = Read-RequiredText (Join-Path $appRoot "app\build.gradle.kts") "app build"
$manifest = Read-RequiredText (Join-Path $appRoot "app\src\main\AndroidManifest.xml") "manifest"
$ids = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\ids.xml") "ids"
$styles = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\styles.xml") "styles"
$colors = Read-RequiredText (Join-Path $appRoot "app\src\main\res\values\colors.xml") "colors"
$activity = Read-RequiredText (Join-Path $sourceRoot "KuramotoSpatialActivity.kt") "Spatial activity"
$store = Read-RequiredText (Join-Path $sourceRoot "KuramotoExperimentStore.kt") "experiment store"
$nativeReceiptCargo = Read-RequiredText (Join-Path $appRoot "native-receipt\Cargo.toml") "native receipt Cargo manifest"
$nativeReceiptRust = Read-RequiredText (Join-Path $appRoot "native-receipt\src\lib.rs") "native receipt Rust source"
$nativeReceiptSurfaceLayer = Read-RequiredText (Join-Path $appRoot "native-receipt\src\surface_particle_layer.rs") "native receipt surface particle layer"
$nativeReceiptReplayHands = Read-RequiredText (Join-Path $appRoot "native-receipt\src\replay_hands.rs") "native receipt replay hand renderer"
$nativeReceiptLiveHandJoints = Read-RequiredText (Join-Path $appRoot "native-receipt\src\live_hand_joints.rs") "native receipt live hand joint source"
$nativeReceiptBuild = Read-RequiredText (Join-Path $appRoot "native-receipt\build.rs") "native receipt build script"
$nativeReceiptComputeShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\surface_particles.comp.glsl") "native receipt compute shader"
$nativeReceiptVertexShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\surface_particles.vert.glsl") "native receipt vertex shader"
$nativeReceiptReplayHandVertexShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\replay_hands.vert.glsl") "native receipt replay hand vertex shader"
$nativeReceiptReplayHandFragmentShader = Read-RequiredText (Join-Path $appRoot "native-receipt\shaders\replay_hands.frag.glsl") "native receipt replay hand fragment shader"
$buildScript = Read-RequiredText (Join-Path $repoRootPath "tools\Build-KuramotoSpatialSdkAndroid.ps1") "build wrapper"
$depthOffsetTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialLiveHandDepthOffset.ps1") "live hand depth-offset hotload tool"
$targetDistanceTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialParticleLayerTargetDistance.ps1") "particle layer target-distance hotload tool"
$diagnosticModeTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialParticleDiagnosticMode.ps1") "particle diagnostic mode hotload tool"
$liveHandSceneTransformTool = Read-RequiredText (Join-Path $repoRootPath "tools\Set-KuramotoSpatialLiveHandSceneTransform.ps1") "live hand scene-transform hotload tool"
$readme = Read-RequiredText (Join-Path $appRoot "README.md") "app README"
$plan = Read-RequiredText (Join-Path $repoRootPath "docs\SPATIAL_SDK_PORT_IMPLEMENTATION_PLAN.md") "implementation plan"

Assert-ContainsTokens $settings @(
    'rootProject\.name = "RustyQuestKuramotoSpatialSdk"',
    'include\(":app"\)',
    'mavenCentral\(\)',
    'google\(\)'
) "Gradle settings"

Assert-ContainsTokens $rootBuild @(
    'libs\.plugins\.android\.application',
    'libs\.plugins\.jetbrains\.kotlin\.android'
) "root Gradle plugins"

Assert-ContainsTokens $gradleProperties @(
    'android\.useAndroidX=true',
    'android\.nonTransitiveRClass=true',
    'org\.gradle\.configuration-cache=true'
) "Gradle properties"

Assert-ContainsTokens $versions @(
    'spatialsdk = "0\.13\.1"',
    'agp = "8\.11\.1"',
    'kotlin = "2\.1\.0"',
    'meta-spatial-sdk-base',
    'meta-spatial-sdk-compose',
    'meta-spatial-sdk-toolkit',
    'meta-spatial-sdk-vr'
) "version catalog"

Assert-ContainsTokens $appBuild @(
    'libs\.plugins\.meta\.spatial\.plugin',
    'libs\.plugins\.compose\.compiler',
    'namespace = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial"',
    'applicationId = "io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial"',
    'compileSdk = 34',
    'minSdk = 34',
    'targetSdk = 34',
    'compose = true',
    'kotlinCompilerExtensionVersion = "1\.5\.15"',
    'jniLibs\.srcDir\(layout\.buildDirectory\.dir\("generated/rustJniLibs"\)\)',
    'allowUsageDataCollection\.set\(false\)',
    'implementation\(libs\.meta\.spatial\.sdk\.base\)',
    'implementation\(libs\.meta\.spatial\.sdk\.compose\)',
    'implementation\(libs\.meta\.spatial\.sdk\.toolkit\)',
    'implementation\(libs\.meta\.spatial\.sdk\.vr\)'
) "app Gradle build"

Assert-ContainsTokens $manifest @(
    'horizonos:uses-horizonos-sdk',
    'android\.hardware\.vr\.headtracking',
    'com\.oculus\.intent\.category\.VR',
    'android\.intent\.category\.LAUNCHER',
    'com\.oculus\.supportedDevices',
    'libossdk\.oculus\.so',
    'KuramotoSpatialActivity',
    'android:configChanges="screenSize\|screenLayout\|orientation\|keyboardHidden\|keyboard\|navigation\|uiMode"'
) "Android manifest"

Assert-ContainsTokens $ids @(
    'kuramoto_experiment_panel',
    'kuramoto_particle_surface_panel'
) "panel id"

Assert-ContainsTokens $styles @(
    'PanelAppThemeOpaqueProbe',
    'android:windowBackground">@color/kuramoto_panel_probe_background',
    'android:colorAccent">@color/kuramoto_panel_probe_button'
) "panel styles"

Assert-ContainsTokens $colors @(
    'kuramoto_panel_probe_background">#FFF3B0',
    'kuramoto_panel_probe_button">#FF5A1F'
) "panel colors"

Assert-ContainsTokens $activity @(
    'class KuramotoSpatialActivity : AppSystemActivity',
    'VRFeature\(this\)',
    'ComposeFeature\(\)',
    'ComposeViewPanelRegistration',
    'VideoSurfacePanelRegistration',
    'MediaPanelSettings',
    'MediaPanelRenderOptions',
    'FixedMediaPanelDisplayOptions',
    'PanelSurface',
    'SamplerConfig',
    'UIPanelSettings',
    'QuadShapeOptions\(width = PANEL_WIDTH_METERS, height = PANEL_HEIGHT_METERS\)',
    'DpPerMeterDisplayOptions\(dpPerMeter = PANEL_DP_PER_METER\)',
    'Entity\.createPanelEntity',
    'R\.id\.kuramoto_particle_surface_panel',
    'scene\.setViewOrigin\(0\.0f, 0\.0f, 2\.0f, 180\.0f\)',
    'createDiagnosticBackdrop\(\)',
    'Mesh\("mesh://skybox"\.toUri\(\), hittable = MeshCollision\.NoCollision\)',
    'Box\(\)',
    'Mesh\("mesh://box"\.toUri\(\), hittable = MeshCollision\.NoCollision\)',
    'Material\(\)\.apply',
    'Color4\(0\.19f, 0\.42f, 0\.57f, 1\.0f\)',
    'PanelDimensions\(Vector2\(PANEL_WIDTH_METERS, PANEL_HEIGHT_METERS\)\)',
    'Visible\(true\)',
    'Quaternion\(6\.12323426e-17f, 6\.12323426e-17f, 1\.0f, -3\.74939976e-33f\)',
    'setBackgroundColor\(android\.graphics\.Color\.rgb\(255, 243, 176\)\)',
    'PanelAppThemeOpaqueProbe',
    'PanelColorProbe',
    'PANEL COLOR PROBE',
    'Visible Button',
    'lightColorScheme',
    'onVRReady\(\)',
    'logNativeInteropProbe\(phase = "scene-ready", probeSurface = false\)',
    'logNativeInteropProbe\(phase = "vr-ready", probeSurface = true\)',
    'loadNativeReceiptLibrary\(\)',
    'System\.loadLibrary\(NATIVE_RECEIPT_LIBRARY\)',
    'recordNativeInteropReceipt',
    'nativeRecordNoRenderInteropReceipt',
    'nativeStartSurfaceParticleLayer',
    'nativeStopSurfaceParticleLayer',
    'nativeUpdateSurfaceParticleParameters',
    'liveHandJointInputExpected=true',
    'status=surface-consumer-called',
    'status=lifecycle-check',
    'kuramoto_spatial_activity_markers\.log',
    'particleSurfaceConsumerCalled',
    'nativeSurfaceStartRequested',
    'VALIDATION_STUDY_CONDITION_ID = "lche"',
    'prioritizeConditionForValidation\(VALIDATION_STUDY_CONDITION_ID\)',
    'openXrProbe\.openXrInstanceHandle',
    'openXrProbe\.openXrSessionHandle',
    'openXrProbe\.openXrGetInstanceProcAddrHandle',
    'SurfaceParticleControlState',
    'SurfaceParticleControls',
    'NativeParticleSlider',
    'StereoMode\.LeftRight',
    'PARTICLE_LAYER_STEREO_MODE',
    'perEyeExtent',
    'packedExtent',
    'computeParameterBridge=true',
    'transport=jni-live-queue',
    'driver0Value01',
    'driver1Value01',
    'pointScale',
    'NativeInteropReceiptResult',
    'SpatialNativeInteropProbe',
    'NativeInteropSurfaceProbeResult',
    'SpatialSDKExperimentalAPI',
    '@OptIn\(SpatialSDKExperimentalAPI::class\)',
    'PanelSurface\(scene, 64, 64, 1, SamplerConfig\(\), true, false, "", false\)',
    'scene\.getRuntimeName\(\)',
    'scene\.getOpenXrInstanceHandle\(\)',
    'scene\.getOpenXrSessionHandle\(\)',
    'scene\.getOpenXrGetInstanceProcAddrHandle\(\)',
    'native-interop-probe',
    'native-interop-receipt',
    'native-surface-particle-layer',
    'native-vulkan-wsi-surface-panel',
    'nativeReceiptMask',
    'nativeReceiptOpenXrInstanceHandleNonZero',
    'nativeReceiptOpenXrGetInstanceProcAddrCallable',
    'nativeReceiptXrGetInstancePropertiesResolved',
    'nativeReceiptXrGetInstancePropertiesSucceeded',
    'nativeReceiptXrGetSystemResolved',
    'nativeReceiptXrVulkanGraphicsRequirements2Succeeded',
    'nativeReceiptXrCreateVulkanInstanceResolved',
    'nativeReceiptVkInstanceCreated',
    'nativeReceiptVkGraphicsDeviceObtained',
    'nativeReceiptVkGraphicsComputeQueueFound',
    'nativeReceiptVkDeviceCreated',
    'nativeReceiptVkQueueObtained',
    'nativeReceiptVkObjectsDestroyed',
    'renderPolicy',
    'no-render',
    'surfaceProbeStatus',
    'created-destroyed-no-render',
    'onSceneTick\(\)',
    'scene\.getViewerPose\(\)',
    'scene\.getEyeOffsets\(\)',
    'Quaternion\.fromDirection\(forward, up\)',
    'status=projection-plane-updated',
    'projectionPlaneFacingMode=viewer-forward-front-face',
    'viewerPoseSource=Scene\.getViewerPose',
    'Transform\(panelPose\(\)\)',
    'Scale\(Vector3',
    'PANEL_WIDTH_METERS = 2\.048f',
    'PANEL_HEIGHT_METERS = 1\.254f',
    'PARTICLE_LAYER_PER_EYE_WIDTH_PX = 1024',
    'PARTICLE_LAYER_WIDTH_PX = PARTICLE_LAYER_PER_EYE_WIDTH_PX \* 2',
    'PARTICLE_LAYER_HEIGHT_PX = 1024',
    'PARTICLE_LAYER_TARGET_DISTANCE_METERS = 0\.72f',
    'PARTICLE_LAYER_TARGET_DISTANCE_PROPERTY =\s*"debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters"',
    'currentParticleLayerTargetDistanceMeters\(\)',
    'particleLayerWidthMeters',
    'target-distance-hotload-updated',
    'particleLayerTargetDistanceParameterSource=runtime-hotload-android-property',
    'particleLayerTargetDistanceProperty=\$PARTICLE_LAYER_TARGET_DISTANCE_PROPERTY',
    'PARTICLE_LAYER_WIDTH_METERS = 1\.44f',
    'PARTICLE_LAYER_HEIGHT_METERS = 1\.44f',
    'PARTICLE_LAYER_X_METERS = 0\.0f',
    'PARTICLE_LAYER_Z_METERS = -0\.72f',
    'PARTICLE_LAYER_PARTICLE_COUNT = 2048',
    'PARTICLE_LAYER_STEREO_MODE = "LeftRight"',
    'PARTICLE_LAYER_PLACEMENT_MODE = "viewer-pose-projection-locked-quad"',
    'PARTICLE_LAYER_PLACEMENT_AUTHORITY = "spatial-sdk-viewer-pose-scene-tick"',
    'PARTICLE_LAYER_TARGET_COORDINATE_SPACE = "spatial-sdk-surface-panel-eye-uv"',
    'PARTICLE_LAYER_TARGET_PROJECTION_SPACE =\s*"spatial-sdk-panel-plane-perspective-projection"',
    'PARTICLE_LAYER_PROJECTION_CONTENT_MAPPING_MODE =\s*"world-to-spatial-sdk-panel-plane-left-right"',
    'PARTICLE_LAYER_TARGET_FOV_TANGENTS = "panel-plane-derived"',
    'PARTICLE_LAYER_TARGET_SURFACE_UV_RECT = "0\.0;0\.0;1\.0;1\.0"',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=\$PARTICLE_LAYER_PLACEMENT_MODE',
    'targetProjectionSpace=\$PARTICLE_LAYER_TARGET_PROJECTION_SPACE',
    'projectionContentMappingMode=\$PARTICLE_LAYER_PROJECTION_CONTENT_MAPPING_MODE',
    'leftTargetSurfaceUvRect=\$PARTICLE_LAYER_TARGET_SURFACE_UV_RECT',
    'NATIVE_RECEIPT_LIBRARY = "kuramoto_spatial_native_receipt"',
    'NATIVE_RECEIPT_XR_GET_INSTANCE_PROPERTIES_SUCCEEDED_BIT',
    'NATIVE_RECEIPT_XR_VULKAN_REQUIREMENTS2_SUCCEEDED_BIT',
    'Color\(0xFFFFF3B0\)',
    'Color\(0xFF0F5F6F\)',
    'Color\(0xFFFF5A1F\)',
    'RUN_WORKFLOW_SELF_TEST',
    'self-test-complete',
    'RUSTY_QUEST_KURAMOTO_SPATIAL',
    'hand_rendering_expected'
) "Spatial activity and panel"

Assert-ContainsTokens $nativeReceiptCargo @(
    'name = "kuramoto-spatial-native-receipt"',
    'name = "kuramoto_spatial_native_receipt"',
    'crate-type = \["cdylib"\]',
    'ash = "0\.38"',
    'libc = "0\.2"',
    'openxr-sys = "0\.13\.1"',
    'serde_json = "1"',
    'build = "build\.rs"',
    'unsafe_code = "allow"'
) "native receipt Cargo manifest"

Assert-ContainsTokens $nativeReceiptRust @(
    '__android_log_print',
    'ash::Entry::load',
    'vk::ApplicationInfo',
    'vk::InstanceCreateInfo',
    'vk::DeviceQueueCreateInfo',
    'vk::DeviceCreateInfo',
    'openxr_sys::Instance::from_raw',
    'openxr_sys::pfn::GetInstanceProcAddr',
    'openxr_sys::pfn::GetInstanceProperties',
    'openxr_sys::pfn::GetSystem',
    'openxr_sys::pfn::GetVulkanGraphicsRequirements2KHR',
    'openxr_sys::pfn::CreateVulkanInstanceKHR',
    'openxr_sys::pfn::GetVulkanGraphicsDevice2KHR',
    'openxr_sys::pfn::CreateVulkanDeviceKHR',
    'openxr_sys::InstanceProperties::out',
    'openxr_sys::GraphicsRequirementsVulkanKHR::out',
    'openxr_sys::VulkanInstanceCreateInfoKHR',
    'openxr_sys::VulkanGraphicsDeviceGetInfoKHR',
    'openxr_sys::VulkanDeviceCreateInfoKHR',
    'RUSTY_QUEST_KURAMOTO_SPATIAL_NATIVE',
    'channel=native-interop-receipt',
    'channel=native-vulkan-object-probe',
    'renderPolicy=no-render',
    'xrGetInstanceProperties',
    'xrGetSystem',
    'xrGetVulkanGraphicsRequirements2KHR',
    'xrCreateVulkanInstanceKHR',
    'xrGetVulkanGraphicsDevice2KHR',
    'xrCreateVulkanDeviceKHR',
    'openXrGetInstanceProcAddrCallable',
    'xrGetInstancePropertiesSucceeded',
    'xrGetVulkanGraphicsRequirements2Succeeded',
    'vkInstanceCreated',
    'vkGraphicsDeviceObtained',
    'vkGraphicsComputeQueueFound',
    'vkDeviceCreated',
    'vkQueueObtained',
    'vkObjectsDestroyed',
    'destroy_device',
    'destroy_instance',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeRecordNoRenderInteropReceipt',
    'RECEIPT_OPENXR_INSTANCE_NONZERO',
    'RECEIPT_OPENXR_SESSION_NONZERO',
    'RECEIPT_OPENXR_GET_PROC_NONZERO',
    'RECEIPT_PANEL_SURFACE_VALID',
    'RECEIPT_OPENXR_GET_PROC_CALLABLE',
    'RECEIPT_XR_GET_INSTANCE_PROPERTIES_RESOLVED',
    'RECEIPT_XR_GET_INSTANCE_PROPERTIES_SUCCEEDED',
    'RECEIPT_XR_GET_SYSTEM_SUCCEEDED',
    'RECEIPT_XR_VULKAN_REQUIREMENTS2_SUCCEEDED',
    'RECEIPT_XR_CREATE_VULKAN_INSTANCE_RESOLVED',
    'RECEIPT_XR_GET_VULKAN_GRAPHICS_DEVICE2_RESOLVED',
    'RECEIPT_XR_CREATE_VULKAN_DEVICE_RESOLVED',
    'RECEIPT_VK_INSTANCE_CREATED',
    'RECEIPT_VK_GRAPHICS_DEVICE_OBTAINED',
    'RECEIPT_VK_GRAPHICS_COMPUTE_QUEUE_FOUND',
    'RECEIPT_VK_DEVICE_CREATED',
    'RECEIPT_VK_QUEUE_OBTAINED',
    'RECEIPT_VK_OBJECTS_DESTROYED'
) "native receipt Rust source"

Assert-ContainsTokens $nativeReceiptBuild @(
    'surface_particles\.vert\.glsl',
    'surface_particles\.frag\.glsl',
    'surface_particles\.comp\.glsl',
    'replay_hands\.vert\.glsl',
    'replay_hands\.frag\.glsl',
    'recorded_hand_replay_source\.json',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_FRAME_LIMIT',
    'validation_mesh_jsonl',
    'surface_particles\.comp\.spv',
    '-fshader-stage=\{stage\}',
    'glslc',
    'ANDROID_NDK_HOME',
    'shader-tools'
) "native receipt build script"

Assert-ContainsTokens $nativeReceiptSurfaceLayer @(
    'ANativeWindow_fromSurface',
    'ANativeWindow_release',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeStartSurfaceParticleLayer',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeStopSurfaceParticleLayer',
    'Java_io_github_mesmerprism_rustyquest_kuramoto_1spatial_KuramotoSpatialActivity_nativeUpdateSurfaceParticleParameters',
    '__system_property_get',
    'SURFACE_PARTICLE_LIVE_HAND_DEPTH_OFFSET_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'SURFACE_PARTICLE_DIAGNOSTIC_MODE_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'parse_surface_particle_diagnostic_mode',
    'surface_particle_diagnostic_mode_name',
    'triangle-bands',
    'projection-clamp',
    'particleDiagnosticModeName=',
    'liveHandDepthOffsetParameterSource=runtime-hotload-android-property',
    'liveHandDepthOffsetMeters',
    'target_distance_meters',
    'panelTargetDistanceMeters',
    'ash::khr::android_surface::NAME',
    'ash::khr::swapchain::NAME',
    'vk::QueueFlags::GRAPHICS \| vk::QueueFlags::COMPUTE',
    'vk::DescriptorType::STORAGE_BUFFER',
    'create_descriptor_set_layout',
    'create_particle_descriptor_set',
    'create_buffer_with_memory',
    'create_compute_pipeline',
    'ReplayHandsRenderer::new',
    'LiveHandOpenXrHandles',
    'openxr_instance_handle',
    'openxr_session_handle',
    'openxr_get_instance_proc_addr_handle',
    'update_live_joints_buffer',
    'ReplayHandsRenderer',
    'replay_hands\.marker_fields\(\)',
    'surface_particles\.comp\.spv',
    'cmd_dispatch',
    'cmd_pipeline_barrier',
    'COMPUTE_SHADER',
    'VERTEX_SHADER',
    'surface_particle_stereo_layout',
    'SurfaceParticleStereoLayout',
    'cmd_set_viewport',
    'cmd_set_scissor',
    'sideBySideStereoProof=true',
    'stereoDebugMarkers=false',
    'stereoMode',
    'perEyeExtent',
    'packedExtent',
    'SURFACE_PARTICLE_PROJECTION_MARKERS',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'targetCoordinateSpace=spatial-sdk-surface-panel-eye-uv',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'targetFovTangents=panel-plane-derived',
    'leftTargetSurfaceUvRect=0\.0;0\.0;1\.0;1\.0',
    'rightTargetSurfaceUvRect=0\.0;0\.0;1\.0;1\.0',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'extent\.height as f32 \* 0\.018',
    'transport=jni-live-queue',
    'create_android_surface',
    'create_swapchain',
    'get_swapchain_images',
    'acquire_next_image',
    'queue_present',
    'surface_particles\.vert\.spv',
    'surface_particles\.frag\.spv',
    'channel=native-surface-particle-layer',
    'render-loop-ready',
    'first-frame-presented',
    'native-vulkan-wsi-surface-panel',
    'particleCount',
    'STOP_SURFACE_PARTICLES'
) "native receipt surface particle layer"

Assert-ContainsTokens $nativeReceiptReplayHands @(
    'RECORDED_HAND_REPLAY_JSON',
    'recorded_hand_replay_source\.json',
    'ReplayHandsRenderer',
    'ReplayHandVertex',
    'ReplayHandSkinningVertex',
    'ReplayHandGpuPose',
    'ReplayHandPush',
    'target_distance_meters',
    'external-recorded-capture-build-env',
    'public-shape-fallback',
    'validation_mesh_jsonl',
    'triangle_indices',
    'bind_vertices',
    'vertex_blend_indices',
    'vertex_blend_weights',
    'bind_normals',
    'bind_normal',
    'bind_joint_sources',
    'HAND_MESH_COMPONENT_POLICY',
    'keep_two_largest_components_drop_wrist_bridge_boundaries_v1',
    'HAND_MESH_KEPT_COMPONENT_RANK_COUNT',
    'component_filtered_triangles',
    'analyze_mesh_components',
    'MeshComponentSummary',
    'component_marker_fields',
    'native-kuramoto-study-hand-mesh-components',
    'native-kuramoto-study-left-hand-mesh-components',
    'native-kuramoto-study-right-hand-mesh-components',
    'liveMeshSurfacePolicy=',
    'liveMeshComponentRank0=hand-inside',
    'liveMeshComponentRank1=hand-back',
    'liveMeshComponentRank2=wrist-cap',
    'liveMeshWristCapPolicy=drop-component-rank-2',
    'liveMeshNormalFallbackPolicy=skinned-bind-normal-for-small-triangle-area',
    'HandMeshSamplingTriangleCount=',
    'HandMeshDroppedTriangleCount=',
    'native-kuramoto-study-particles-ready',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandGpuSkinningParticles=true',
    'jointClusterMode=false',
    'compactJointSkinningKernel=true',
    'compactJointPoseUploadPerFrame=true',
    'jointMatrixUploadPerFrame=false',
    'privateKuramotoPayloadActive=false',
    'studyProfileDynamicsActive=true',
    'kuramotoConditionId=',
    'kuramotoStudyProfileId=',
    'kuramotoMovementBaseHz=',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'KURAMOTO_STUDY_PARTICLES_PER_HAND',
    'PARTICLE_VERTICES_PER_INSTANCE',
    'REPLAY_HAND_IPD_METERS',
    'REPLAY_HAND_HEAD_Y_METERS',
    'REPLAY_HAND_HEAD_Z_METERS',
    'vk::PrimitiveTopology::TRIANGLE_LIST',
    'replay_hands\.vert\.spv',
    'replay_hands\.frag\.spv',
    'cmd_draw'
) "native receipt replay hand renderer"

Assert-ContainsTokens $nativeReceiptLiveHandJoints @(
    'XR_EXT_hand_tracking',
    'XR_KHR_convert_timespec_time_CLOCK_MONOTONIC',
    'LiveHandOpenXrHandles',
    'LiveHandJointRow',
    'LIVE_HAND_ROW_COUNT',
    '__system_property_get',
    'xrCreateHandTrackerEXT',
    'xrLocateHandJointsEXT',
    'xrLocateViews',
    'xrCreateReferenceSpace',
    'xrConvertTimespecTimeToTimeKHR',
    'clock_gettime',
    'recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandJointPlacementMode=viewer-relative-openxr-to-spatial-sdk-panel-plane',
    'liveHandCoordinateTransform=',
    'viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'raw-openxr-local-floor-to-spatial-sdk-scene-fallback',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'LIVE_HAND_SCENE_OFFSET_Z_PROPERTY',
    'LIVE_HAND_SCENE_YAW_DEGREES_PROPERTY',
    'LIVE_HAND_SCENE_HORIZONTAL_SIGN_PROPERTY',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'current_live_hand_scene_transform',
    'apply_live_hand_scene_transform',
    'store_live_hand_panel_basis',
    'current_view_panel_mapping',
    'apply_live_hand_view_panel_mapping',
    'ViewConfigurationType::PRIMARY_STEREO',
    'poll_live_hand_scene_sign_property',
    'multiply_quat_xyzw',
    'live-hand-scene-transform-hotload-updated',
    'liveHandSceneHorizontalSignDefault=-1.000',
    'liveHandPoseOrientationUpload=true',
    'liveHandJointStatusY=pose-valid',
    'liveHandCompactUploadEquivalent=true',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveHandRuntimeJointPoseCount=',
    'liveHandTipLengthCount=',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'LIVE_HAND_COMPACT_RUNTIME_OPENXR_JOINTS',
    'LIVE_HAND_COMPACT_TIP_OPENXR_PAIRS',
    'liveHandJointFrameReady',
    'liveHandFallbackToReplay',
    'liveHandCorrectPositionSizeProof=spatial-sdk-panel-plane-projection'
) "native receipt live hand joint source"

Assert-ContainsTokens $nativeReceiptComputeShader @(
    'layout\(local_size_x = 64',
    'layout\(set = 0, binding = 0, std430\) buffer ParticleBuffer',
    'ParticleRow',
    'driver0Value01',
    'driver1Value01',
    'pointScale',
    'particleBuffer\.particles\[index\]\.positionSize',
    'particleBuffer\.particles\[index\]\.color'
) "native receipt surface particle compute shader"

Assert-ContainsTokens $nativeReceiptVertexShader @(
    'float eyeIndex = clamp\(pc\.reserved0',
    'index < 32u',
    'markerColor',
    'eyeTint',
    'gl_Position = vec4\(markerX, markerY',
    'outColor = vec4\(tinted, particle\.color\.a\)'
) "native receipt surface particle vertex shader"

Assert-ContainsTokens $nativeReceiptReplayHandVertexShader @(
    'ReplayHandVertex',
    'ReplayHandVertexBuffer',
    'LiveHandJointBuffer',
    'SkinningVertex',
    'SkinningVertexBuffer',
    'SkinningTriangleBuffer',
    'BindJointPoseBuffer',
    'BindJointSourceBuffer',
    'ReplayHandPush',
    'eyeIndex',
    'liveFrameReady',
    'pc\.dynamics',
    'pc\.profile',
    'pc\.liveAdjust',
    'LIVE_MESH_TRIANGLE_VALIDATION_ATTEMPTS',
    'bindNormal',
    'transform_joint_normal',
    'skin_normal_at',
    'fallbackNormal',
    'triangle\.w >= 2u',
    'diagnosticMode',
    'degenerateTriangle',
    'particle\.debug0',
    'particle\.debug1',
    'projectionDiagnosticVisible',
    'transform_joint\(joints\.x, vertex\.bindPosition\) \* weights\.x',
    'valid = true',
    'weighted / totalWeight',
    'particle\.center -= panelForward \* pc\.liveAdjust\.x',
    'OPENXR_HAND_JOINT_COUNT',
    'BIND_JOINT_COUNT_PER_HAND',
    'anchor_barycentric',
    'openxr_joint_for_runtime',
    'tip_length_at',
    'current_bind_joint_pose',
    'skin_vertex_at',
    'live_mesh_particle',
    'gl_InstanceIndex',
    'QUAD_POSITIONS',
    'pc\.projection\.w',
    'tangent',
    'gl_Position'
) "native receipt replay hand vertex shader"

Assert-ContainsTokens $nativeReceiptReplayHandFragmentShader @(
    'inMaskUv',
    'softMask',
    'outColor',
    'vec4\(rgb \* alpha, alpha\)'
) "native receipt replay hand fragment shader"

Assert-ContainsTokens $liveHandSceneTransformTool @(
    'rusty\.quest\.kuramoto_spatial_live_hand_scene_transform_set\.v1',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Pass -Serial or set RUSTY_QUEST_SERIAL',
    'adb setprop',
    'adb getprop'
) "live hand scene-transform hotload tool"

Assert-ContainsTokens $store @(
    'QUESTIONNAIRE_SCHEMA = "rusty\.kuramoto\.mesh\.experiment_questionnaire\.v2"',
    'DEFAULT_BLOCK_DURATION_MS = 10_000L',
    'fun prioritizeConditionForValidation\(conditionId: String\)',
    'validation-condition-prioritized',
    'validation_condition_prioritized',
    'participant_id',
    'session_id',
    'block_index',
    'block_number',
    'condition_id',
    'profile_id',
    'surface_target_id',
    '"signature"',
    'questionnaire_results\.jsonl',
    'polar_events\.jsonl',
    'ecg_events\.jsonl',
    'lcle',
    'lche',
    'hcle',
    'hche',
    'real-hands',
    'gpu-replay-hands',
    'icosphere'
) "experiment store"

Assert-ContainsTokens $buildScript @(
    'NdkHome = \$env:ANDROID_NDK_HOME',
    'RecordedHandCaptureDir = \$env:RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RecordedHandFrameLimit = 24',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_FRAME_LIMIT',
    'gradle-\$Version-bin\.zip',
    'services\.gradle\.org',
    'CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER',
    'aarch64-linux-android',
    'generated\\rustJniLibs',
    'lib/arm64-v8a/libkuramoto_spatial_native_receipt\.so',
    'Test-ZipEntry',
    'GRADLE_USER_HOME',
    ':app:assembleDebug',
    'rusty-quest-kuramoto-spatial-sdk\.apk',
    'rusty\.quest\.kuramoto_spatial_sdk_android\.build_manifest\.v1',
    'high_rate_json_payload = \$false',
    'hand_rendering_expected = \$true',
    'native_interop_probe = "spatial-sdk-openxr-handles-and-panelsurface-capability"',
    'native_interop_probe_rendering = "no-render"',
    'native_interop_probe_surface = "PanelSurface-create-destroy"',
    'native_receipt_probe = "rust-jni-openxr-handle-and-panelsurface-receipt"',
    'native_receipt_openxr_probe = "xrGetInstanceProperties-vulkan-requirements-and-no-present-vulkan-objects-through-sdk-getInstanceProcAddr"',
    'native_receipt_vulkan_object_probe = "no-present-instance-device-queue-create-destroy"',
    'native_receipt_mask_bits = @\(',
    'xrGetVulkanGraphicsRequirements2KHR-succeeded',
    'xrCreateVulkanInstanceKHR-resolved',
    'vk-instance-created',
    'vk-device-created',
    'vk-objects-destroyed',
    'native_receipt_jni_bridge = "KuramotoSpatialActivity\.nativeRecordNoRenderInteropReceipt"',
    'native_receipt_library_packaged = \$nativeReceiptLibraryPackaged',
    'native_surface_particle_layer = "VideoSurfacePanelRegistration-native-vulkan-wsi-surface-panel"',
    'native_surface_particle_layer_rendering = "native-vulkan-wsi-surface-panel-live-openxr-gpu-skinned-resident-rig-kuramoto-study-hand-anchor-particles-packed-stereo-left-right"',
    'native_surface_particle_layer_jni_bridge = "KuramotoSpatialActivity\.nativeStartSurfaceParticleLayer"',
    'native_surface_particle_layer_parameter_bridge = "KuramotoSpatialActivity\.nativeUpdateSurfaceParticleParameters"',
    'native_surface_particle_layer_parameter_transport = "jni-live-queue"',
    'native_surface_particle_layer_hotload_property = "debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters"',
    'native_surface_particle_layer_live_hand_depth_offset_default_meters = 0\.0',
    'native_surface_particle_layer_live_hand_scene_transform = "viewer-relative-openxr-to-spatial-sdk-panel-basis"',
    'native_surface_particle_layer_live_hand_scene_fallback_transform = "raw-openxr-local-floor-to-spatial-sdk-scene"',
    'native_surface_particle_layer_live_hand_scene_transform_source = "runtime-hotload-android-property"',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_x_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_y_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.yaw_degrees',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'native_surface_particle_layer_live_hand_scene_offset_default_meters = "0\.0;0\.0;2\.0"',
    'native_surface_particle_layer_live_hand_scene_yaw_default_degrees = 180\.0',
    'native_surface_particle_layer_live_hand_scene_horizontal_sign_default = -1\.0',
    'native_surface_particle_layer_target_distance_hotload_property = "debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters"',
    'native_surface_particle_layer_target_distance_default_meters = 0\.72',
    'native_surface_particle_layer_target_distance_range_meters = "0\.20\.\.1\.50"',
    'forced_replay_hand_source_mode',
    'forced_replay_hand_frame_limit',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandJointFrameSource=XR_EXT_hand_tracking',
    'liveHandJointGpuInputPath=recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandJointPlacementMode=viewer-relative-openxr-to-spatial-sdk-panel-plane',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'liveHandSceneOffsetDefaultM=0\.000;0\.000;2\.000',
    'liveHandSceneYawDefaultDegrees=180\.000',
    'liveHandSceneHorizontalSignDefault=-1\.000',
    'liveHandCompactUploadEquivalent=true',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveHandRuntimeJointPoseCount=',
    'liveHandTipLengthCount=',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandCorrectPositionSizeProof=spatial-sdk-panel-plane-projection',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'liveHandDepthOffsetParameterSource=runtime-hotload-android-property',
    'liveHandDepthOffsetProperty=debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'particleLayerTargetDistanceParameterSource=runtime-hotload-android-property',
    'particleLayerTargetDistanceProperty=debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'privateKuramotoPayloadActive=false',
    'studyProfileDynamicsActive=true',
    'kuramotoConditionId=lche',
    'kuramotoStudyProfileId=kuramoto.private.native.profile.high-energy-low-coherence.movement-only.v1',
    'kuramotoMovementBaseHz=0.88',
    'kuramotoMovementCoupling=0.0',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'native-surface-compute-stereo-proof=true',
    'sideBySideStereoProof=true',
    'stereoMode=LeftRight',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=viewer-pose-projection-locked-quad',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'width_px = 2048',
    'per_eye_width_px = 1024',
    'height_px = 1024',
    'stereo_mode = "StereoMode\.LeftRight"',
    'packed_stereo_layout = "left-right"',
    'width_meters = 1\.44',
    'height_meters = 1\.44',
    'target_distance_meters = 0\.72',
    'x_meters = 0\.0',
    'z_meters = -0\.72',
    'placement_authority = "spatial-sdk-viewer-pose-scene-tick"',
    'target_coordinate_space = "spatial-sdk-surface-panel-eye-uv"',
    'target_projection_space = "spatial-sdk-panel-plane-perspective-projection"',
    'target_fov_tangents = "panel-plane-derived"',
    'left_target_surface_uv_rect = "0\.0;0\.0;1\.0;1\.0"',
    'first-frame-presented',
    'particle_surface_panel_registration_id = "kuramoto_particle_surface_panel"',
    'diagnostic_backdrop = "skybox-and-reference-geometry"',
    'panel_content_probe = "sample-quaternion-opaque-yellow-background-teal-banner-orange-button"'
) "build wrapper"

Assert-ContainsTokens $depthOffsetTool @(
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_live_hand_depth_offset_set\.v1',
    'requested_meters',
    'applied_meters'
) "live hand depth-offset hotload tool"

Assert-ContainsTokens $targetDistanceTool @(
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_particle_layer_target_distance_set\.v1',
    'requested_meters',
    'applied_meters'
) "particle layer target-distance hotload tool"

Assert-ContainsTokens $diagnosticModeTool @(
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'Parameter\(Mandatory = \$true\)',
    'RUSTY_QUEST_SERIAL',
    'shell setprop \$propertyName \$value',
    'shell getprop \$propertyName',
    'rusty\.quest\.kuramoto_spatial_particle_diagnostic_mode_set\.v1',
    'requested_mode',
    'applied_mode'
) "particle diagnostic mode hotload tool"

Assert-ContainsTokens $readme @(
    'separate Meta Spatial SDK lane',
    'does not replace the native renderer APK',
    'libkuramoto_spatial_native_receipt\.so',
    'nativeRecordNoRenderInteropReceipt',
    'xrGetInstanceProperties',
    'xrGetVulkanGraphicsRequirements2KHR',
    'RUSTY_QUEST_KURAMOTO_SPATIAL_NATIVE',
    'nativeUpdateSurfaceParticleParameters',
    'compute-written\s+storage buffer',
    'native Kuramoto study hand-anchor particle draw path',
    'RUSTY_QUEST_NATIVE_RECORDED_HAND_CAPTURE_DIR',
    'StereoMode\.LeftRight',
    'packed extent `2048x1024`',
    'per-eye extent\s+`1024x1024`',
    'properStereoStudyParticles=true',
    'replayStereoProjection=per-eye-spatial-sdk-panel-plane-ray-intersection',
    'surfaceLayerMode=native-kuramoto-study-hand-anchor-particles',
    'forcedReplayHands=true',
    'forcedReplayMeshVisible=false',
    'diagnosticParticlesVisible=false',
    'nativeStudyParticlesVisible=true',
    'handAnchorParticlesVisible=true',
    'gpuReplayHandsResident=true',
    'handAnchorParticlePath=resident-recorded-rig-gpu-skinned-mesh-coordinate-anchor-billboards',
    'handAnchorParticleCoordinateSource=live-openxr-world-joints-gpu-skinned-resident-mesh-with-forced-replay-fallback',
    'liveHandJointGpuInputPath=recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Set-KuramotoSpatialLiveHandSceneTransform\.ps1',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'particleDiagnosticModeProperty=debug\.rustyquest\.kuramoto_spatial\.particle_layer\.diagnostic_mode',
    'Set-KuramotoSpatialParticleDiagnosticMode\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Set-KuramotoSpatialLiveHandDepthOffset\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Set-KuramotoSpatialParticleLayerTargetDistance\.ps1',
    'privateKuramotoPayloadActive=false',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'native-surface-compute-stereo-proof=true',
    'stereoMode=LeftRight',
    'perEyeExtent=1024x1024',
    'packedExtent=2048x1024',
    'cameraFacingParticleSurface=true',
    'projectionLockedParticleSurface=true',
    'placementMode=viewer-pose-projection-locked-quad',
    'targetProjectionSpace=spatial-sdk-panel-plane-perspective-projection',
    'projectionContentMappingMode=world-to-spatial-sdk-panel-plane-left-right',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial/\.KuramotoSpatialActivity',
    'target/kuramoto-spatial-sdk-android/rusty-quest-kuramoto-spatial-sdk\.apk'
) "app README"

Assert-ContainsTokens $plan @(
    'Initial Hypothesis',
    'Resources Consulted',
    'Architecture Decisions',
    'Iteration Log',
    'Final Build/Run Recipe',
    'Remaining Risks And Follow-Ups',
    'apps/kuramoto-spatial-sdk-android',
    'io\.github\.mesmerprism\.rustyquest\.kuramoto_spatial',
    'Foreground coexistence boundary',
    'native_frame_like_after_spatial_count=0',
    'same native process id',
    'simultaneous overlay over the current NativeActivity renderer',
    'single-immersive-owner architecture',
    'native receipt probe',
    'libkuramoto_spatial_native_receipt\.so',
    'nativeRecordNoRenderInteropReceipt',
    'OpenXR handle-usability',
    'OpenXR Vulkan capability',
    'xrGetInstanceProperties',
    'xrGetVulkanGraphicsRequirements2KHR',
    'xrCreateVulkanInstanceKHR',
    'VR-ready native receipt mask\s+was `2097151`',
    'Adreno__TM__740',
    'native-vulkan-object-probe',
    'no-present Vulkan',
    'Panel-to-native parameter boundary',
    'compute-resource parity source slice',
    'nativeUpdateSurfaceParticleParameters',
    'computeParticleStateBuffer=true',
    'computeShaderDispatchReady=true',
    'computeParameterBridge=true',
    'native Vulkan particle layer embedded in Spatial SDK world',
    'VideoSurfacePanelRegistration',
    'SceneSwapchain\.createAsAndroid',
    'Scene\.createQuadLayer',
    'ANativeWindow',
    'xrWaitFrame',
    'onSceneTick',
    'native-surface-compute-stereo-proof',
    'StereoMode\.LeftRight',
    'per-eye extent `1024x1024`',
    'packed surface extent\s+`2048x1024`',
    'viewer-pose-projection-locked-quad',
    'spatial-sdk-panel-plane-perspective-projection',
    'spatial-sdk-surface-panel-eye-uv',
    'world-to-spatial-sdk-panel-plane-left-right',
    'resident rig live-skinning correction',
    'live skinning robustness and diagnostic depth hotload',
    'live hand raw-to-scene transform correction',
    'live hand viewer-relative panel-basis correction',
    'recorded-compatible-compact-joint-pose-gpu-skinning',
    'liveHandCoordinateTransform=viewer-relative-openxr-to-spatial-sdk-panel-basis',
    'liveHandViewPoseSource=xrLocateViews',
    'liveHandPanelBasisSource=Scene.getViewerPose-panel-plane',
    'liveHandSceneTransformSource=runtime-hotload-android-property',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.offset_z_m',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_scene\.horizontal_sign',
    'Set-KuramotoSpatialLiveHandSceneTransform\.ps1',
    'liveHandCompactFrameGate=native-equivalent-21-runtime-5-tip',
    'liveMeshSkinningPolicy=native-compact-frame-gated-full-weight-skinning',
    'liveMeshTriangleRetryPolicy=bounded-alternate-triangle-sampling',
    'liveMeshTriangleValidationAttempts=6',
    'liveHandJointStatusY=pose-valid',
    'liveHandSkinningValidityPolicy=native-compact-frame-gate-trust-all-weights',
    'debug\.rustyquest\.kuramoto_spatial\.live_hand_depth_offset_meters',
    'Set-KuramotoSpatialLiveHandDepthOffset\.ps1',
    'debug\.rustyquest\.kuramoto_spatial\.particle_layer\.target_distance_meters',
    'Set-KuramotoSpatialParticleLayerTargetDistance\.ps1',
    'Open Questions For Meta Or SDK Reference Checks'
) "implementation plan"

Write-Host "Rusty Quest Kuramoto Spatial SDK Android static validation passed"
