[CmdletBinding()]
param([Parameter(Mandatory)][string]$AndroidHome,[Parameter(Mandatory)][string]$JavaHome,[Parameter(Mandatory)][string]$BuildLeaseId)
$ErrorActionPreference='Stop'
if($PSVersionTable.PSVersion -lt [version]'7.6'){throw 'PowerShell 7.6 required'}
$source=$PSScriptRoot;$repo=(Resolve-Path (Join-Path $source '../../..')).Path;$platform=Join-Path $AndroidHome 'platforms/android-35/android.jar';$d8=Join-Path $AndroidHome 'build-tools/35.0.0/d8.bat';$javac=Join-Path $JavaHome 'bin/javac.exe';$jar=Join-Path $JavaHome 'bin/jar.exe';$java=Join-Path $source QuestOfflineHotspotHandoff.java
foreach($p in @($platform,$d8,$javac,$jar,$java)){if(-not(Test-Path -LiteralPath $p)){throw "missing $p"}}
$identity=[ordered]@{schema='rusty.quest.offline_hotspot_handoff_build_inputs.v1';main='QuestOfflineHotspotHandoff';min_sdk=29;source_sha256=(Get-FileHash $java -Algorithm SHA256).Hash.ToLowerInvariant();builder_sha256=(Get-FileHash $PSCommandPath -Algorithm SHA256).Hash.ToLowerInvariant()};$compact=$identity|ConvertTo-Json -Compress;$hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($compact))).ToLowerInvariant();$out=Join-Path $repo "target/quest-offline-hotspot-handoff/$hash";if(Test-Path -LiteralPath $out){throw "immutable output exists $out"};New-Item -ItemType Directory -Path $out,(Join-Path $out classes),(Join-Path $out dex)|Out-Null
function Run([string]$exe,[string[]]$arguments,[string]$log){$v=&$exe @arguments 2>&1;$exit=$LASTEXITCODE;$v|Set-Content -LiteralPath (Join-Path $out $log);if($exit-ne0){$v|Write-Output;throw "$log failed $exit"}}
Run $javac @('-encoding','UTF-8','-source','8','-target','8','-cp',$platform,'-d',(Join-Path $out classes),$java) javac.txt;Run $jar @('cf',(Join-Path $out classes.jar),'-C',(Join-Path $out classes),'.') jar.txt;Run $d8 @('--min-api','29','--lib',$platform,'--output',(Join-Path $out dex),(Join-Path $out classes.jar)) d8.txt
$dex=Join-Path $out 'quest-offline-hotspot-handoff.dex';Move-Item (Join-Path $out dex/classes.dex) $dex;$result=[ordered]@{schema='rusty.quest.offline_hotspot_handoff_build.v1';status='built_device_unverified';input_sha256=$hash;build_lease_id=$BuildLeaseId;main='QuestOfflineHotspotHandoff';dex=$dex;sha256=(Get-FileHash $dex -Algorithm SHA256).Hash.ToLowerInvariant();bytes=(Get-Item $dex).Length;modes=@('snapshot','connect','restore','guard','watchdog-probe')};[IO.File]::WriteAllText((Join-Path $out 'RESULT.json'),($result|ConvertTo-Json -Depth 5),[Text.UTF8Encoding]::new($false));$result|ConvertTo-Json -Depth 5
