import android.content.AttributionSource;
import android.content.Context;
import android.content.ContextWrapper;
import android.net.ConnectivityManager;
import android.net.LinkAddress;
import android.net.LinkProperties;
import android.net.wifi.WifiConfiguration;
import android.net.wifi.WifiInfo;
import android.net.wifi.WifiManager;
import android.os.IBinder;
import android.os.Looper;
import android.os.Process;
import android.os.SystemClock;
import android.system.Os;
import java.io.*;
import java.lang.reflect.*;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.security.MessageDigest;
import java.net.Inet4Address;
import java.util.*;

/**
 * Fixed shell-UID diagnostic for one saved-network A -> temporary WPA2 B -> A handoff.
 * It has four closed modes: snapshot, connect, restore, and guard.  It accepts no
 * network-management RPC or arbitrary WifiManager method name.
 */
public final class QuestOfflineHotspotHandoff {
  static String stage="entry";
  static final long CONNECT_WAIT_MS=20000L;
  static final long GUARD_POLL_MS=100L;
  static final class Config {
    final String run,ssid,password,path;
    final int originalId;
    final long deadline;
    Config(String p)throws Exception {
      path=p; Properties x=new Properties(); try(InputStream in=new FileInputStream(p)){x.load(in);}
      run=need(x,"run_token"); ssid=need(x,"temporary_ssid"); password=need(x,"temporary_wpa2_password");
      originalId=Integer.parseInt(need(x,"original_network_id")); deadline=Long.parseLong(need(x,"deadline_elapsed_realtime_ms"));
      if(!run.matches("[0-9a-f]{32}")||ssid.length()<1||ssid.length()>32||password.length()<8||password.length()>63||originalId<0||deadline<1)throw new IllegalArgumentException("config");
      if(!p.equals("/data/local/tmp/rqohh-"+run+".properties"))throw new IllegalArgumentException("config_path");
    }
    static String need(Properties p,String k){String v=p.getProperty(k);if(v==null||v.indexOf('\n')>=0||v.indexOf('\r')>=0)throw new IllegalArgumentException("config_"+k);return v;}
    File state(){return new File(path+".state");} File lock(){return new File(path+".lock");} File ready(){return new File(path+".guard-ready");} File done(){return new File(path+".done");} File probeReady(){return new File(path+".probe-ready");} File probeComplete(){return new File(path+".probe-completed");}
  }
  static final class Snapshot {
    final String all,original; final int id,status,reason,current; final String currentSsid;
    Snapshot(String a,String o,int i,int s,int r,int c,String q){all=a;original=o;id=i;status=s;reason=r;current=c;currentSsid=q;}
  }
  final Config cfg; final WifiManager wifi; final ConnectivityManager connectivity;
  QuestOfflineHotspotHandoff(Config c)throws Exception {cfg=c; stage="shell_uid"; if(Process.myUid()!=2000)throw new SecurityException("uid2000_required"); if(Looper.getMainLooper()==null)Looper.prepareMainLooper(); stage="framework"; Class<?> at=Class.forName("android.app.ActivityThread"); Object thread=at.getMethod("systemMain").invoke(null); Context sys=(Context)at.getMethod("getSystemContext").invoke(thread); Context base=sys.createPackageContext("com.android.shell",0); Context shell=new ContextWrapper(base){public String getPackageName(){return "com.android.shell";} public String getOpPackageName(){return "com.android.shell";} public AttributionSource getAttributionSource(){return new AttributionSource.Builder(2000).setPackageName("com.android.shell").build();}}; Class<?> sm=Class.forName("android.os.ServiceManager"), iw=Class.forName("android.net.wifi.IWifiManager"), ic=Class.forName("android.net.IConnectivityManager"); Object service=Class.forName("android.net.wifi.IWifiManager$Stub").getMethod("asInterface",IBinder.class).invoke(null,sm.getMethod("getService",String.class).invoke(null,"wifi")); Object cs=Class.forName("android.net.IConnectivityManager$Stub").getMethod("asInterface",IBinder.class).invoke(null,sm.getMethod("getService",String.class).invoke(null,"connectivity")); wifi=(WifiManager)WifiManager.class.getConstructor(Context.class,iw,Looper.class).newInstance(shell,service,Looper.getMainLooper()); connectivity=(ConnectivityManager)ConnectivityManager.class.getConstructor(Context.class,ic).newInstance(shell,cs);
  }
  static int constant(String name)throws Exception{return Class.forName("android.net.wifi.WifiConfiguration$NetworkSelectionStatus").getField(name).getInt(null);}
  static String sha(String s)throws Exception {byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes("UTF-8"));StringBuilder q=new StringBuilder();for(byte x:b)q.append(String.format(Locale.ROOT,"%02x",x&255));return q.toString();}
  static String q(String x){if(x==null)return "null";return "\""+x.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
  static String quoteWifi(String x){return "\""+x.replace("\\","\\\\").replace("\"","\\\"")+"\"";}
  static String profile(WifiConfiguration c)throws Exception {Object s=c.getClass().getMethod("getNetworkSelectionStatus").invoke(c); Class<?> t=s.getClass(); return c.networkId+"|"+String.valueOf(c.SSID)+"|"+String.valueOf(c.BSSID)+"|"+c.hiddenSSID+"|"+c.allowedKeyManagement+"|"+c.allowedProtocols+"|"+c.allowedAuthAlgorithms+"|"+c.allowedPairwiseCiphers+"|"+c.allowedGroupCiphers+"|"+c.getClass().getField("allowAutojoin").getBoolean(c)+"|"+t.getMethod("getNetworkSelectionStatus").invoke(s)+"|"+t.getMethod("getNetworkSelectionDisableReason").invoke(s)+"|"+String.valueOf(c.getClass().getMethod("getIpConfiguration").invoke(c));}
  static String ownedProjection(WifiConfiguration c){return String.valueOf(c.SSID)+"|"+c.hiddenSSID+"|"+c.allowedKeyManagement+"|"+c.allowedProtocols+"|"+c.allowedAuthAlgorithms;}
  Snapshot snapshot()throws Exception {stage="readback_profiles"; List<WifiConfiguration> xs=wifi.getConfiguredNetworks();if(xs==null||xs.isEmpty())throw new IllegalStateException("configured_networks_unavailable"); ArrayList<String> rows=new ArrayList<>();String own=null;int status=-1,reason=-1;for(WifiConfiguration c:xs){String row=profile(c);rows.add(sha(row));if(c.networkId==cfg.originalId){own=sha(row);Object s=c.getClass().getMethod("getNetworkSelectionStatus").invoke(c);status=(Integer)s.getClass().getMethod("getNetworkSelectionStatus").invoke(s);reason=(Integer)s.getClass().getMethod("getNetworkSelectionDisableReason").invoke(s);}}Collections.sort(rows);WifiInfo i=wifi.getConnectionInfo();if(i==null)throw new IllegalStateException("connection_info_unavailable");return new Snapshot(sha(String.join("\n",rows)),own,cfg.originalId,status,reason,i.getNetworkId(),i.getSSID());}
  void baseline(Snapshot s)throws Exception {stage="baseline";if(!wifi.isWifiEnabled()||s.original==null||s.current!=cfg.originalId||s.currentSsid==null)throw new IllegalStateException("original_not_current");if(s.status!=constant("NETWORK_SELECTION_ENABLED")||s.reason!=constant("DISABLED_NONE"))throw new IllegalStateException("original_selection_not_enabled");}
  WifiConfiguration temporary(){WifiConfiguration b=new WifiConfiguration();b.SSID=quoteWifi(cfg.ssid);b.preSharedKey=quoteWifi(cfg.password);b.allowedKeyManagement.set(WifiConfiguration.KeyMgmt.WPA_PSK);b.allowedProtocols.set(WifiConfiguration.Protocol.RSN);b.allowedAuthAlgorithms.set(WifiConfiguration.AuthAlgorithm.OPEN);try{Field f=WifiConfiguration.class.getField("noInternetAccessExpected");f.setBoolean(b,true);}catch(NoSuchFieldException unavailable){}catch(IllegalAccessException denied){throw new SecurityException("noInternetAccessExpected");}return b;}
  WifiConfiguration find(int id){List<WifiConfiguration> xs=wifi.getConfiguredNetworks();if(xs!=null)for(WifiConfiguration x:xs)if(x.networkId==id)return x;return null;}
  void write(File f,String s)throws Exception {File tmp=new File(f.getPath()+".tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write(s.getBytes("UTF-8"));out.getFD().sync();}Os.chmod(tmp.getPath(),0600);if(!tmp.renameTo(f))throw new IOException("state_rename");Os.chmod(f.getPath(),0600);}
  Properties state()throws Exception {Properties p=new Properties();try(InputStream in=new FileInputStream(cfg.state())){p.load(in);}return p;}
  void requireState(Properties p)throws Exception {String h=p.getProperty("temporary_profile_sha256","");if(!cfg.run.equals(p.getProperty("run_token"))||!("pending".equals(h)||h.matches("[0-9a-f]{64}")))throw new SecurityException("state_identity");}
  void withLock(Action a)throws Exception {try(RandomAccessFile r=new RandomAccessFile(cfg.lock(),"rw");FileChannel ch=r.getChannel();FileLock ignored=ch.lock()){a.run();}}
  interface Action {void run()throws Exception;}
  boolean activeIpv4(){try{LinkProperties p=connectivity.getLinkProperties(connectivity.getActiveNetwork());if(p!=null)for(LinkAddress a:p.getLinkAddresses())if(a.getAddress() instanceof Inet4Address&&!a.getAddress().isLoopbackAddress()&&!a.getAddress().isAnyLocalAddress())return true;}catch(Throwable ignored){}return false;}
  void awaitTemporary(int id)throws Exception {stage="temporary_association";long until=Math.min(cfg.deadline,SystemClock.elapsedRealtime()+CONNECT_WAIT_MS);while(SystemClock.elapsedRealtime()<until){WifiInfo current=wifi.getConnectionInfo();if(current!=null&&current.getNetworkId()==id&&activeIpv4())return;Thread.sleep(100);}throw new IllegalStateException("temporary_association_or_ipv4_unconfirmed");}
  void connect()throws Exception {stage="connect_preflight";if(cfg.deadline<=SystemClock.elapsedRealtime())throw new IllegalStateException("deadline_elapsed");Snapshot before=snapshot();baseline(before);WifiConfiguration wanted=temporary();for(WifiConfiguration x:wifi.getConfiguredNetworks())if(quoteWifi(cfg.ssid).equals(x.SSID))throw new IllegalStateException("temporary_ssid_already_present");stage="guard_start";startGuard();long until=SystemClock.elapsedRealtime()+2000;while(!cfg.ready().exists()&&SystemClock.elapsedRealtime()<until)Thread.sleep(20);if(!cfg.ready().exists())throw new IllegalStateException("guardian_not_ready");withLock(()->{stage="connect_recheck";Snapshot check=snapshot();if(!before.all.equals(check.all)||!before.original.equals(check.original))throw new IllegalStateException("baseline_changed");stage="add_temporary";int b=wifi.addNetwork(wanted);if(b<0)throw new IllegalStateException("add_network_rejected");write(cfg.state(),"run_token="+cfg.run+"\ntemporary_network_id="+b+"\ntemporary_profile_sha256=pending\noriginal_profiles_sha256="+before.all+"\noriginal_profile_sha256="+before.original+"\n");WifiConfiguration created=find(b);if(created==null||created.networkId!=b||!quoteWifi(cfg.ssid).equals(created.SSID))throw new IllegalStateException("temporary_id_ssid_readback_mismatch");String createdHash=sha(ownedProjection(created));write(cfg.state(),"run_token="+cfg.run+"\ntemporary_network_id="+b+"\ntemporary_profile_sha256="+createdHash+"\noriginal_profiles_sha256="+before.all+"\noriginal_profile_sha256="+before.original+"\n");stage="select_temporary";if(!wifi.enableNetwork(b,true))throw new IllegalStateException("select_temporary_rejected");awaitTemporary(b);});emit("connect",true,null);}
  void restore(boolean fromGuard)throws Exception {withLock(()->{stage="restore_state";Properties p=state();requireState(p);int b=Integer.parseInt(p.getProperty("temporary_network_id","-1"));String h=p.getProperty("temporary_profile_sha256");WifiConfiguration created=find(b);if(created!=null&&(created.networkId!=b||!quoteWifi(cfg.ssid).equals(created.SSID)||(!"pending".equals(h)&&!h.equals(sha(ownedProjection(created))))))throw new SecurityException("temporary_identity_mismatch");stage="restore_original";if(!wifi.enableNetwork(cfg.originalId,true))throw new IllegalStateException("select_original_rejected");long until=SystemClock.elapsedRealtime()+CONNECT_WAIT_MS;boolean joined=false;while(SystemClock.elapsedRealtime()<until){Snapshot s=snapshot();if(s.current==cfg.originalId){joined=true;break;}Thread.sleep(100);}if(!joined)throw new IllegalStateException("original_join_unconfirmed");stage="remove_temporary";if(created!=null&&!wifi.removeNetwork(b))throw new IllegalStateException("remove_temporary_rejected");Snapshot finalState=snapshot();if(!p.getProperty("original_profiles_sha256").equals(finalState.all)||!p.getProperty("original_profile_sha256").equals(finalState.original)||finalState.current!=cfg.originalId)throw new IllegalStateException("baseline_restore_readback");write(cfg.done(),"restored="+(fromGuard?"guardian":"operator")+"\n");});emit(fromGuard?"guardian_restore":"restore",true,null);}
  void startGuard()throws Exception {String cp=System.getenv("CLASSPATH");if(cp==null||cp.indexOf('\n')>=0||cp.indexOf('\r')>=0||cp.indexOf('\'')>=0)throw new IllegalStateException("classpath");String command="umask 077; CLASSPATH='"+cp+"' app_process /system/bin QuestOfflineHotspotHandoff guard '"+cfg.path+"' >/data/local/tmp/rqohh-"+cfg.run+".guard.log 2>&1 &";new ProcessBuilder("/system/bin/sh","-c",command).start();}
  void guard()throws Exception {write(cfg.ready(),"ready\n");while(SystemClock.elapsedRealtime()<cfg.deadline){if(cfg.done().exists())return;Thread.sleep(GUARD_POLL_MS);}if(!cfg.done().exists())restore(true);}
  void watchdogProbe()throws Exception {stage="probe_preflight";long remain=cfg.deadline-SystemClock.elapsedRealtime();if(remain<1||remain>30000)throw new IllegalStateException("probe_deadline_not_bounded");startProbeChild();long until=SystemClock.elapsedRealtime()+2000;while(!cfg.probeReady().exists()&&SystemClock.elapsedRealtime()<until)Thread.sleep(20);if(!cfg.probeReady().exists())throw new IllegalStateException("probe_child_not_ready");emit("watchdog-probe",true,null);}
  void watchdogProbeChild()throws Exception {stage="probe_ready";write(cfg.probeReady(),"ready\n");while(SystemClock.elapsedRealtime()<cfg.deadline)Thread.sleep(GUARD_POLL_MS);stage="probe_completed";write(cfg.probeComplete(),"completed\n");emit("watchdog-probe-child",true,null);}
  void startProbeChild()throws Exception {String cp=System.getenv("CLASSPATH");if(cp==null||cp.indexOf('\n')>=0||cp.indexOf('\r')>=0||cp.indexOf('\'')>=0)throw new IllegalStateException("classpath");String command="umask 077; CLASSPATH='"+cp+"' app_process /system/bin QuestOfflineHotspotHandoff watchdog-probe-child '"+cfg.path+"' >/data/local/tmp/rqohh-"+cfg.run+".watchdog-probe.log 2>&1 &";new ProcessBuilder("/system/bin/sh","-c",command).start();}
  static String detail(Throwable x){if(!(x instanceof IllegalStateException))return null;String m=x.getMessage();for(String allowed:new String[]{"deadline_elapsed","temporary_ssid_already_present","guardian_not_ready","baseline_changed","add_network_rejected","temporary_id_ssid_readback_mismatch","select_temporary_rejected","temporary_association_or_ipv4_unconfirmed","select_original_rejected","original_join_unconfirmed","remove_temporary_rejected","baseline_restore_readback","probe_deadline_not_bounded","probe_child_not_ready"})if(allowed.equals(m))return m;return null;}
  void emit(String mode,boolean ok,Throwable error){String e=error==null?null:error.getClass().getName();System.out.println("{\"schema\":\"rusty.quest.offline_hotspot_handoff.v1\",\"mode\":"+q(mode)+",\"ok\":"+ok+",\"stage\":"+q(stage)+",\"run_token\":"+q(cfg==null?null:cfg.run)+",\"error_type\":"+q(e)+",\"error_code\":"+q(error==null?null:detail(error))+"}");System.out.flush();}
  void emitSnapshot(Snapshot s){System.out.println("{\"schema\":\"rusty.quest.offline_hotspot_handoff.v1\",\"mode\":\"snapshot\",\"ok\":true,\"stage\":\"baseline\",\"run_token\":"+q(cfg.run)+",\"original_network_id\":"+s.id+",\"selection_status\":"+s.status+",\"selection_disable_reason\":"+s.reason+"}");System.out.flush();}
  static void usage(){throw new IllegalArgumentException("mode_config");}
  public static void main(String[] a){QuestOfflineHotspotHandoff h=null;try{if(a.length!=2)usage();Config c=new Config(a[1]);h=new QuestOfflineHotspotHandoff(c);if("snapshot".equals(a[0])){Snapshot s=h.snapshot();h.baseline(s);h.emitSnapshot(s);}else if("connect".equals(a[0]))h.connect();else if("restore".equals(a[0]))h.restore(false);else if("guard".equals(a[0]))h.guard();else if("watchdog-probe".equals(a[0]))h.watchdogProbe();else if("watchdog-probe-child".equals(a[0]))h.watchdogProbeChild();else usage();}catch(Throwable x){if(h!=null)h.emit(a.length>0?a[0]:"invalid",false,x);else System.out.println("{\"schema\":\"rusty.quest.offline_hotspot_handoff.v1\",\"ok\":false,\"stage\":\"bootstrap\",\"error_type\":"+q(x.getClass().getName())+"}");System.exit(1);}}
}
