param([Parameter(Mandatory=$true)][string]$PrimarySerial,[Parameter(Mandatory=$true)][string]$SecondarySerial,[string]$TermuxProfile="",[string]$SidecarPlan="",[string]$ApkPath="",[string]$EvidenceDir="",[string]$Adb="S:\Work\tools\Android\windows-sdk\platform-tools\adb.exe")
$ErrorActionPreference="Stop";$repo=(Resolve-Path (Join-Path $PSScriptRoot "..")).Path;$activeRoot=Split-Path $repo -Parent;$utf8NoBom=[Text.UTF8Encoding]::new($false);$package="io.github.mesmerprism.rustyquest.peer_rendezvous"
if($PrimarySerial-eq$SecondarySerial){throw "Two distinct Quest serials are required."}
if([string]::IsNullOrWhiteSpace($TermuxProfile)){$TermuxProfile=Join-Path $activeRoot "quest-termux-lab\examples\peer-workflow-source-profile.synthetic.json"}
if([string]::IsNullOrWhiteSpace($SidecarPlan)){$SidecarPlan=Join-Path $activeRoot "rusty-quest-sidecar-mesh\fixtures\valid\configured-peer-rehearsal-plan.synthetic.json"}
if([string]::IsNullOrWhiteSpace($ApkPath)){$ApkPath=Join-Path $repo "target\peer-rendezvous-android\rusty-quest-peer-rendezvous.apk"}
if([string]::IsNullOrWhiteSpace($EvidenceDir)){$EvidenceDir=Join-Path "S:\Work\tmp" ("morphospace-net012-n-peer-"+(Get-Date -Format "yyyyMMdd-HHmmss"))}
foreach($path in @($Adb,$TermuxProfile,$SidecarPlan,$ApkPath)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Missing N-peer input: $path"}}
New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$runId="net012-"+(Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ");$pairDir=Join-Path $repo "target\peer-rendezvous-pairs\$runId";$bundlePath=Join-Path $EvidenceDir "n-peer-decision-bundle.json";$summaryPath=Join-Path $EvidenceDir "summary.json"
function Write-Json([string]$Path,$Value){[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 20),$utf8NoBom)}
function Invoke-Adb([string]$Serial,[string[]]$AdbArgs,[switch]$AllowFailure){$output=& $Adb -s $Serial @AdbArgs 2>&1;$code=$LASTEXITCODE;if($code-ne0-and-not$AllowFailure){throw "adb -s $Serial $($AdbArgs-join' ') failed: $($output-join' ')"};@($output)}
try{
  foreach($serial in @($PrimarySerial,$SecondarySerial)){if(((Invoke-Adb $serial @("get-state"))-join"").Trim()-ne"device"){throw "Quest $serial is not ready"};Invoke-Adb $serial @("uninstall",$package)-AllowFailure|Out-Null;Invoke-Adb $serial @("install","-r",$ApkPath)|Out-Null}
  & (Join-Path $PSScriptRoot "Invoke-PeerRendezvousAndroidPair.ps1") -PrimarySerial $PrimarySerial -SecondarySerial $SecondarySerial -CoordinationMode user_authorized_serial_scoped -RunId $runId -ApkPath $ApkPath -OutDir $pairDir -SkipInstall|Out-Null
  $pairPath=Join-Path $pairDir "summary.json";$pair=Get-Content -Raw -LiteralPath $pairPath|ConvertFrom-Json
  if($pair.status-ne"pass"-or-not$pair.role_swap_completed-or$pair.authenticated_phase_count-ne2-or-not$pair.cleanup.complete-or$pair.cleanup.app_fatal_count-ne0){throw "Live BLE pair evidence failed"}
  & cargo run --quiet -p rusty-quest-peer-session-adapter --bin evaluate_n_peer_mesh -- $pairPath $TermuxProfile $SidecarPlan $bundlePath;if($LASTEXITCODE-ne0){throw "N-peer Manifold evaluation failed"}
  $bundle=Get-Content -Raw -LiteralPath $bundlePath|ConvertFrom-Json;$accepted=$bundle.accepted_decision.accepted_state;$issues=@()
  if($bundle.schema-ne"rusty.quest.peer_mesh_decision_bundle.v1"){$issues+="bundle_schema"};if(-not$bundle.termux_source_privacy_only-or-not$bundle.sidecar_advisory_only){$issues+="advisory_boundary"};if(@($accepted.members).Count-ne3){$issues+="member_count"};if(@($accepted.selected_routes).Count-ne1-or-not$accepted.selected_routes[0].direct_media_lane_eligible){$issues+="direct_lane_schedule"};if($bundle.replay_decision.rejection_reason-ne"replayed_proposal"){$issues+="replay_gate"};if($bundle.split_brain_decision.rejection_reason-ne"split_brain"){$issues+="split_brain_gate"};if($bundle.advisory_media_decision.rejection_reason-ne"media_gossip_forbidden"){$issues+="media_gossip_gate"};if(($bundle.expiry_receipt.removed_peer_ids-join",")-ne"peer.gamma"){$issues+="expiry_gate"};if(($bundle.revocation_receipt.removed_peer_ids-join",")-ne"peer.gamma"){$issues+="revocation_gate"}
  $rows=@();$systemFatalTotal=0;foreach($serial in @($PrimarySerial,$SecondarySerial)){$log=(Invoke-Adb $serial @("logcat","-d"))-join"`n";$systemFatals=([regex]::Matches($log,'FATAL EXCEPTION IN SYSTEM PROCESS|Watchdog.*system_server|Fatal signal.*system_server')).Count;$systemFatalTotal+=$systemFatals;$rows+=[ordered]@{serial=$serial;live_authenticated_role_swap=$true;app_fatal_count=0;system_fatal_count=$systemFatals;cleanup_process_absent=$true}};if($systemFatalTotal-ne0){$issues+="system_fatal_present"}
  $summary=[ordered]@{schema="rusty.quest.n_peer_mesh_two_quest_configured_peer_evidence.v1";status=if($issues.Count-eq0){"pass"}else{"fail"};coordination_mode="user_authorized_serial_scoped";live_peer_count=2;configured_peer_count=1;accepted_member_count=@($accepted.members).Count;selected_direct_lane_count=@($accepted.selected_routes).Count;termux_source_privacy_only=[bool]$bundle.termux_source_privacy_only;sidecar_advisory_only=[bool]$bundle.sidecar_advisory_only;replay_rejection=$bundle.replay_decision.rejection_reason;split_brain_rejection=$bundle.split_brain_decision.rejection_reason;media_gossip_rejection=$bundle.advisory_media_decision.rejection_reason;expired_peer_ids=@($bundle.expiry_receipt.removed_peer_ids);revoked_peer_ids=@($bundle.revocation_receipt.removed_peer_ids);pair_summary=$pairPath;decision_bundle=$bundlePath;rows=$rows;issues=$issues};Write-Json $summaryPath $summary;if($issues.Count-ne0){throw "N-peer evidence failed: $($issues-join',')"}
}finally{foreach($serial in @($PrimarySerial,$SecondarySerial)){Invoke-Adb $serial @("shell","am","force-stop",$package)-AllowFailure|Out-Null;Invoke-Adb $serial @("uninstall",$package)-AllowFailure|Out-Null}}
Write-Output $summaryPath
