param(
    [switch]$Build,
    [string]$AndroidHome = $env:ANDROID_HOME,
    [string]$JavaHome = $env:JAVA_HOME
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$appRoot = Join-Path $repoRoot "apps\qcl041-wifi-direct-harness-android"
$manifestPath = Join-Path $appRoot "AndroidManifest.xml"
$activityPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041WifiDirectHarnessActivity.java"
$servicePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041WifiDirectHarnessService.java"
$lifecyclePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041WifiDirectLifecycle.java"
$networkBinderPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041WifiDirectNetworkBinder.java"
$appBoundSocketMatrixPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041AppBoundSocketMatrix.java"
$qcl030LocalOnlyHotspotProbePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl030LocalOnlyHotspotProbe.java"
$nativeSocketProbeBridgePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041NativeSocketProbe.java"
$qcl082MediaLanesPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl082MediaLanes.java"
$qcl082CopyProgressPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl082CopyProgress.java"
$qcl082ControlTcpMediaCarrierPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl082ControlTcpMediaCarrier.java"
$receiverSocketCandidatePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\ReceiverSocketCandidate.java"
$artifactPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041LifecycleArtifact.java"
$configPath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl041ProbeConfig.java"
$lslBridgePath = Join-Path $appRoot "src\main\java\io\github\mesmerprism\rustyquest\qcl041\Qcl081LslNativeBridge.java"
$nativeBridgePath = Join-Path $appRoot "src\main\cpp\qcl081_lsl_outlet_bridge.cpp"
$nativeHeaderPath = Join-Path $appRoot "src\main\cpp\liblsl_qcl081_min.h"
$nativeSocketProbePath = Join-Path $appRoot "src\main\cpp\qcl041_socket_probe.c"
$buildPath = Join-Path $PSScriptRoot "Build-Qcl041WifiDirectHarnessAndroid.ps1"
$invokePath = Join-Path $PSScriptRoot "Invoke-Qcl041WifiDirectLifecycle.ps1"
$q2qMatrixInvokePath = Join-Path $PSScriptRoot "Invoke-Qcl041QuestToQuestAppBoundSocketMatrix.ps1"
$qcl030InvokePath = Join-Path $PSScriptRoot "Invoke-Qcl030QuestLocalOnlyHotspotProbe.ps1"
$qcl100InvokePath = Join-Path $PSScriptRoot "Invoke-Qcl100QuestToQuestNativeStereoProjectionWifiDirect.ps1"
$qcl100CommonPath = Join-Path $PSScriptRoot "qcl100_native_projection\Common.ps1"
$qcl100ParityBlockersPath = Join-Path $PSScriptRoot "qcl100_native_projection\ParityBlockers.ps1"
$qcl100RelayPath = Join-Path $PSScriptRoot "qcl100_native_projection\Qcl041Relay.ps1"
$qcl100FreshnessPath = Join-Path $PSScriptRoot "qcl100_native_projection\Freshness.ps1"
$qcl100RuntimeSummaryPath = Join-Path $PSScriptRoot "qcl100_native_projection\RuntimeSummary.ps1"
$qcl100MatrixGatePath = Join-Path $PSScriptRoot "qcl100_native_projection\Qcl041MatrixGate.ps1"
$readmePath = Join-Path $appRoot "README.md"

foreach ($path in @($manifestPath, $activityPath, $servicePath, $lifecyclePath, $networkBinderPath, $appBoundSocketMatrixPath, $qcl030LocalOnlyHotspotProbePath, $nativeSocketProbeBridgePath, $qcl082MediaLanesPath, $qcl082CopyProgressPath, $qcl082ControlTcpMediaCarrierPath, $receiverSocketCandidatePath, $artifactPath, $configPath, $lslBridgePath, $nativeBridgePath, $nativeHeaderPath, $nativeSocketProbePath, $buildPath, $invokePath, $q2qMatrixInvokePath, $qcl030InvokePath, $qcl100InvokePath, $qcl100CommonPath, $qcl100ParityBlockersPath, $qcl100RelayPath, $qcl100FreshnessPath, $qcl100RuntimeSummaryPath, $qcl100MatrixGatePath, $readmePath)) {
    if (-not (Test-Path $path)) {
        throw "Missing QCL-041 Wi-Fi Direct harness file: $path"
    }
}

$manifest = Get-Content -Raw -Path $manifestPath
$activity = Get-Content -Raw -Path $activityPath
$service = Get-Content -Raw -Path $servicePath
$lifecycle = Get-Content -Raw -Path $lifecyclePath
$networkBinder = Get-Content -Raw -Path $networkBinderPath
$appBoundSocketMatrix = Get-Content -Raw -Path $appBoundSocketMatrixPath
$qcl030LocalOnlyHotspotProbe = Get-Content -Raw -Path $qcl030LocalOnlyHotspotProbePath
$nativeSocketProbeBridge = Get-Content -Raw -Path $nativeSocketProbeBridgePath
$qcl082MediaLanes = Get-Content -Raw -Path $qcl082MediaLanesPath
$qcl082CopyProgress = Get-Content -Raw -Path $qcl082CopyProgressPath
$qcl082ControlTcpMediaCarrier = Get-Content -Raw -Path $qcl082ControlTcpMediaCarrierPath
$receiverSocketCandidate = Get-Content -Raw -Path $receiverSocketCandidatePath
$lifecycleSurface = "$lifecycle`n$networkBinder`n$appBoundSocketMatrix`n$qcl082MediaLanes`n$qcl082CopyProgress`n$qcl082ControlTcpMediaCarrier`n$receiverSocketCandidate"
$artifact = Get-Content -Raw -Path $artifactPath
$config = Get-Content -Raw -Path $configPath
$lslBridge = Get-Content -Raw -Path $lslBridgePath
$nativeBridge = Get-Content -Raw -Path $nativeBridgePath
$nativeHeader = Get-Content -Raw -Path $nativeHeaderPath
$nativeSocketProbe = Get-Content -Raw -Path $nativeSocketProbePath
$buildText = Get-Content -Raw -Path $buildPath
$invoke = Get-Content -Raw -Path $invokePath
$q2qMatrixInvoke = Get-Content -Raw -Path $q2qMatrixInvokePath
$qcl030Invoke = Get-Content -Raw -Path $qcl030InvokePath
$qcl100Invoke = Get-Content -Raw -Path $qcl100InvokePath
$qcl100Common = Get-Content -Raw -Path $qcl100CommonPath
$qcl100ParityBlockers = Get-Content -Raw -Path $qcl100ParityBlockersPath
$qcl100Relay = Get-Content -Raw -Path $qcl100RelayPath
$qcl100Freshness = Get-Content -Raw -Path $qcl100FreshnessPath
$qcl100RuntimeSummary = Get-Content -Raw -Path $qcl100RuntimeSummaryPath
$qcl100MatrixGate = Get-Content -Raw -Path $qcl100MatrixGatePath
$readme = Get-Content -Raw -Path $readmePath
$combined = "$manifest`n$activity`n$service`n$lifecycleSurface`n$qcl030LocalOnlyHotspotProbe`n$nativeSocketProbeBridge`n$artifact`n$config`n$lslBridge`n$nativeBridge`n$nativeHeader`n$nativeSocketProbe`n$buildText`n$invoke`n$q2qMatrixInvoke`n$qcl030Invoke`n$qcl100Invoke`n$qcl100Common`n$qcl100ParityBlockers`n$qcl100Relay`n$qcl100Freshness`n$qcl100RuntimeSummary`n$qcl100MatrixGate`n$readme"

function Assert-ContainsTokens {
    param(
        [string]$Text,
        [string[]]$Tokens,
        [string]$Label
    )
    foreach ($token in $Tokens) {
        if ($Text -notmatch $token) {
            throw "QCL-041 Wi-Fi Direct harness static check failed for ${Label}: missing token: $token"
        }
    }
}

function Assert-TextOrder {
    param(
        [string]$Text,
        [string]$First,
        [string]$Second,
        [string]$Label
    )
    $firstIndex = $Text.IndexOf($First, [StringComparison]::Ordinal)
    $secondIndex = $Text.IndexOf($Second, [StringComparison]::Ordinal)
    if ($firstIndex -lt 0 -or $secondIndex -lt 0 -or $firstIndex -ge $secondIndex) {
        throw "QCL-041 Wi-Fi Direct harness static check failed for ${Label}: expected '$First' before '$Second'."
    }
}

Assert-ContainsTokens $manifest @(
    'package="io\.github\.mesmerprism\.rustyquest\.qcl041"',
    'android\.hardware\.wifi\.direct',
    'android\.permission\.ACCESS_WIFI_STATE',
    'android\.permission\.CHANGE_WIFI_STATE',
    'android\.permission\.ACCESS_NETWORK_STATE',
    'android\.permission\.CHANGE_NETWORK_STATE',
    'android\.permission\.INTERNET',
    'android\.permission\.POST_NOTIFICATIONS',
    'android\.permission\.FOREGROUND_SERVICE',
    'android\.permission\.FOREGROUND_SERVICE_DATA_SYNC',
    'com\.oculus\.permission\.HAND_TRACKING',
    'oculus\.software\.handtracking',
    'android\.permission\.NEARBY_WIFI_DEVICES',
    'android:usesPermissionFlags="neverForLocation"',
    'android\.permission\.ACCESS_FINE_LOCATION',
    'android:maxSdkVersion="32"',
    'com\.oculus\.supportedDevices',
    'com\.oculus\.vr\.focusaware',
    'com\.oculus\.handtracking\.version',
    'com\.oculus\.intent\.category\.VR',
    'Qcl041WifiDirectHarnessActivity',
    'Qcl041WifiDirectHarnessService',
    'android:foregroundServiceType="dataSync"',
    'android:stopWithTask="false"',
    'android:debuggable="true"'
) "Android manifest"

Assert-ContainsTokens $activity @(
    'requestPermissions',
    'Manifest\.permission\.NEARBY_WIFI_DEVICES',
    'Manifest\.permission\.ACCESS_FINE_LOCATION',
    'Build\.VERSION_CODES\.TIRAMISU',
    'onRequestPermissionsResult',
    'Qcl030LocalOnlyHotspotProbe',
    'isQcl030LocalOnlyHotspotRoute',
    'QCL-030 foreground Activity runtime permission denied',
    'Qcl041WifiDirectLifecycle'
) "runtime permission Activity"

Assert-ContainsTokens $service @(
    'extends Service',
    'startForeground',
    'NotificationChannel',
    'START_STICKY',
    'Manifest\.permission\.NEARBY_WIFI_DEVICES',
    'Manifest\.permission\.ACCESS_FINE_LOCATION',
    'Qcl041WifiDirectLifecycle',
    'Qcl030LocalOnlyHotspotProbe',
    'QCL-030 lifecycle complete',
    'QCL-041 lifecycle complete',
    'foreground service cannot request UI'
) "foreground service harness"

Assert-ContainsTokens $invoke @(
    'Invoke-AndroidPermissionPreflight',
    'dumpsys",\s*"package"',
    'grant_state_found',
    'pm",\s*"grant"',
    'uiautomator',
    'transport_bind_local_address',
    'transport_owner',
    'wifi_direct_local_address',
    'qcl041\.qcl082_relay_enabled',
    'qcl041\.qcl082_relay_start_delay_ms',
    'android\.permission\.POST_NOTIFICATIONS',
    'qcl041-wifi-direct-permission-pregrant\.json',
    'qcl041-wifi-direct-permission-uiautomator\.json',
    'qcl041-harness-launch\.json',
    'rusty\.quest\.qcl041\.harness_launch\.v1',
    'Qcl041WifiDirectHarnessService',
    'qcl041LaunchSurface',
    'foreground_service',
    'start-foreground-service',
    'qcl082-broker-permission-preflight\.json',
    'qcl082-broker-prestart\.json',
    'Start-Qcl082ProductMediaSourceBeforeHarness',
    'qcl041_wifi_direct_relay_prestarted_source',
    'QCL-082 pre-harness start_source live Android command',
    'Qcl082SenderSourceKind',
    'camera2_mediacodec_surface',
    'camera_permission_required',
    'Qcl082SenderCameraIds',
    'qcl082-broker-camera-permission-uiautomator\.json',
    'Invoke-BrokerCameraPermissionUiFallbackIfNeeded',
    'Get-Qcl082RelaySourcePort',
    'RunQcl082LivePreview',
    '--preview-ffplay',
    '--preview-window-title',
    'QCL-082 WPF product receiver with ffplay preview',
    'Qcl082Ffplay',
    'Prestarted QCL-082 WPF receiver already exited',
    'rusty-manifold-broker\.apk',
    'Build-ManifoldBrokerAndroid\.ps1',
    'QCL-082 broker APK install',
    'Start-Qcl082BrokerBeforeHarness',
    'Wait-AndroidPackagePid',
    'QuestLeaseWaitSeconds',
    '--wait',
    '--timeout',
    'BrokerStartService',
    'start-foreground-service',
    'foreground_service',
    'avoid_horizon_reprojected_os_dialog_before_qcl041_launch',
    'broker_foreground_service_start_failed',
    'service_start_exit_code',
    'activity_start_exit_code',
    'brokerPid',
    'packagePid',
    '--no-launch-broker',
    'PrestartedBroker',
    'broker_prestart_artifact',
    'force_stop_exit_code',
    'am force-stop io\.github\.mesmerprism\.rustyquest\.qcl041',
    'am_start_exit_code',
    'launch_evidence_path',
    'broker_pid_missing_after_prestart'
) "live permission pregrant and UIAutomator fallback"

Assert-ContainsTokens $q2qMatrixInvoke @(
    'rusty\.quest\.qcl041_q2q_app_bound_socket_matrix_run\.v1',
    'RequireInfrastructureWifiDisconnected',
    'RequireP2p0Ipv4Cleared',
    'RequireCandidateWifiDirectRoutesClear',
    'RequireTcpTunnelStreamPass',
    'Qcl100ControlTcpGate',
    'PreflightOnly',
    '"cmd",\s*"wifi",\s*"status"',
    'Wifi is connected to',
    'blocked_preflight',
    'wifi_direct_candidate_route_preflight',
    'infrastructure_wifi_connected',
    'p2p0_ipv4_present',
    'candidate_wifi_direct_routes_not_clear',
    'require_p2p0_ipv4_cleared',
    'require_candidate_wifi_direct_routes_clear',
    'requested_require_tcp_tunnel_stream_pass',
    'require_tcp_tunnel_stream_pass',
    'matrix_focus',
    'qcl100_control_tcp_gate',
    'delayed_udp_required',
    'whole_matrix_completion_required',
    'requested_delayed_udp_delay_seconds',
    'effectiveDelayedUdpDelaySeconds',
    'qcl041\.q2q_app_bound_socket_matrix_enabled',
    'qcl041\.q2q_app_bound_socket_matrix_delayed_udp_delay_ms',
    'DelayedUdpDelaySeconds',
    'tcp_tunnel_control_socket',
    'tcp_tunnel_stream_socket',
    'TcpTunnelStreamSeconds',
    'TcpTunnelStreamBytesPerDirection',
    'RouteProbeTarget',
    'OwnerWifiDirectAddress',
    'ClientWifiDirectAddress',
    'ActiveRouteProbeWaitSeconds',
    'Get-Qcl041ShellRouteSnapshot',
    'Get-Qcl041ShellRouteSnapshots',
    'Get-Qcl041CandidateWifiDirectRoutes',
    'Get-Qcl041CandidateWifiDirectRouteSnapshot',
    'Wait-Qcl041ActiveShellRouteSnapshot',
    '"ip",\s*"route",\s*"get"',
    '"ip",\s*"rule",\s*"show"',
    '"ip",\s*"route",\s*"show",\s*"table",\s*"all"',
    'candidate_wifi_direct_shell_routes',
    'owner_to_owner_wifi_direct_address',
    'client_to_client_wifi_direct_address',
    'candidate_wifi_direct_routes_using_wlan0',
    'candidate_wifi_direct_routes_using_p2p0',
    'candidate_wifi_direct_routes_using_loopback',
    'candidate_wifi_direct_local_self_routes',
    'candidate_wifi_direct_routes_unreachable',
    'candidate_wifi_direct_routes_reachable',
    'candidate_wifi_direct_prelaunch_routes_clear',
    'route_get_from_p2p_source_uses_p2p0',
    'route_get_summary',
    'route_get_uses_wlan0',
    'route_get_uses_loopback',
    'route_get_local_self_route',
    'route_get_unreachable',
    'active-group-shell-routes\.json',
    'post-run-shell-routes\.json',
    'preflight-shell-routes\.json',
    'preflight-candidate-wifi-direct-routes\.json',
    'Get-Qcl041AppNetworkVisibility',
    'app-network-visibility-summary\.json',
    'qcl041_sees_p2p_network_shell_route_not_p2p0',
    'qcl041_client_p2p_network_not_visible',
    'qcl041_and_shell_source_route_use_p2p0',
    'client_wifi_p2p_network_request_visible',
    'initial_wifi_p2p_request_network_found',
    'initial_wifi_p2p_request_matches_selected_network',
    'qcl041\.q2q_app_bound_socket_matrix_tcp_tunnel_stream_seconds',
    'qcl041\.q2q_app_bound_socket_matrix_tcp_tunnel_stream_bytes_per_direction',
    'udp_process_bound',
    'tcp_process_bound',
    'udp_native_fd_network_bound',
    'early_bound_delayed_udp_network_bound',
    'early_bound_delayed_udp_source_and_network_bound',
    'delayed_udp_network_bound',
    'delayed_udp_source_and_network_bound',
    'delayed_udp_native_fd_network_bound',
    'delayed_udp_process_bound',
    'tcp_native_fd_network_bound',
    'native_udp_fd_pass',
    'delayed_app_bound_udp_socket_pass',
    'delayed_native_udp_fd_pass',
    'delayed_process_bound_udp_pass',
    'early_bound_delayed_app_bound_udp_socket_pass',
    'sender_prepare_error',
    'sender_skipped',
    'native_tcp_fd_pass',
    'receiver_client_to_owner_bytes',
    'sender_owner_to_client_rx_bytes',
    'tcp_tunnel_stream_configured_bytes_per_direction',
    'tcp_tunnel_stream_required_bytes_per_direction',
    'client_to_owner_udp_evidence_scope',
    'client_to_owner_wifi_direct_udp_matrix_mode_pass',
    'client_to_owner_wifi_direct_udp_receiver_observed_modes',
    'client_to_owner_app_bound_udp_socket_pass',
    'client_to_owner_app_bound_udp_receiver_observed_modes',
    'same_group_udp_duplex_media_proven_by_matrix',
    'same_group_udp_duplex_media_proof_required',
    '-TcpTunnelStreamBytesPerDirection \(\[Math\]::Max\(0, \$TcpTunnelStreamBytesPerDirection\)\)',
    '-ge \$tcpTunnelStreamMinimumBytes',
    'Test-Qcl041ControlTcpGateArtifactReady',
    'ControlTcpGateReady',
    'tcp_tunnel_bidirectional_bytes_pass',
    'tcp_tunnel_stream_bidirectional_bytes_pass',
    'tcp_tunnel_stream_not_bidirectional',
    'receiver_packets',
    'receiver_accepts',
    'receiver_observed_bytes',
    'process_bound_udp_pass',
    'latestArtifact',
    'Test-Qcl041MatrixArtifactComplete',
    'owner_matrix_complete',
    'client_matrix_complete',
    'owner_matrix_last_checkpoint',
    'client_matrix_last_checkpoint',
    'owner_matrix_missing',
    'client_matrix_missing',
    'owner_matrix_incomplete',
    'client_matrix_incomplete',
    'q2q_app_bound_socket_matrix',
    'Get-Qcl041P2pIpv4Status',
    'active_group_shell_routes',
    'app_network_visibility',
    'post_run_network',
    'p2p0_ipv4_cleared'
) "Quest-to-Quest app-bound socket matrix wrapper"

Assert-ContainsTokens $qcl100Invoke @(
    'Qcl041ArtifactWaitSeconds',
    'Qcl082TransportProtocol',
    'control-tcp',
    'Qcl082ControlTcpMediaStreamBytesPerDirection',
    'Qcl082ControlTcpMediaStreamChunkBytes',
    'RequireQcl082UdpReceiveProxyNetworkBinding',
    'FreshnessSelfTest',
    'Invoke-Qcl100ParityBlockerSelfTest',
    'Invoke-Qcl100RuntimeSummarySelfTest',
    'Invoke-Qcl100Qcl041ArtifactFreshnessWaitSelfTest',
    'Invoke-Qcl100Qcl041MatrixGateSelfTest',
    'RequireRelayFreshness',
    'RequireReceiveProxyFreshness',
    'owner-final-qcl041',
    'client-final-qcl041',
    'RequireP2p0Ipv4Cleared',
    'RequireCandidateWifiDirectRoutesClear',
    'RunQcl041PreclearBeforeAirgapPreflight',
    'RequireQcl041MatrixGatePass',
    'AllowWakePrepMutation',
    'external_keep_awake_managed',
    'blocked_wake_prep_mutation_without_explicit_allow',
    'wake_prep_policy',
    'RequiredQcl041MatrixSummaryPath',
    'RequiredQcl041MatrixRunId',
    'effectiveRequireQcl041MatrixGatePass',
    'qcl041MatrixRunIdPinRequiresGate',
    'qcl041MatrixGatePassesRequirement',
    '\$qcl041MatrixGatePassesRequirement -and',
    'XrLaunchReadinessOnly',
    'MaxQcl041MatrixGateAgeSeconds',
    'wifi_direct_p2p0_ipv4_preflight',
    'wifi_direct_candidate_route_preflight',
    'xr_launch_readiness_preflight',
    'qcl041_matrix_gate_preflight',
    'p2p0_ipv4_present',
    'candidate_wifi_direct_routes_not_clear',
    'require_p2p0_ipv4_cleared',
    'require_candidate_wifi_direct_routes_clear',
    'qcl041_preflight_preclear',
    'airgap-preflight-before-qcl041-preclear\.json',
    'before_p2p0_ipv4_cleared',
    'after_p2p0_ipv4_cleared',
    'require_qcl041_matrix_gate_pass',
    'requested_require_qcl041_matrix_gate_pass',
    'qcl041_matrix_run_id_pin_requires_gate',
    'required_qcl041_matrix_summary_path',
    'required_qcl041_matrix_run_id',
    'max_qcl041_matrix_gate_age_seconds',
    'qcl041_matrix_gate',
    'qcl041_matrix_gate_artifact',
    'qcl041_matrix_gate_required',
    'qcl041_matrix_gate_evaluated',
    'qcl041_matrix_gate_passed',
    'qcl041_matrix_gate_passes_requirement',
    'qcl041_matrix_gate_blocked_reason',
    'qcl041_matrix_gate_run_id',
    'qcl041_matrix_gate_transport_protocol',
    'qcl041_matrix_gate_required_topology',
    'candidate_wifi_direct_prelaunch_routes_clear',
    'qcl100_native_stereo_projection_orchestration_failure',
    'blocked_orchestration',
    'New-Qcl100TrapNativeLogSummary',
    'native_log_summary',
    'Invoke-Qcl100FinalQcl041ArtifactRead',
    'qcl041_artifact_reads',
    'qcl041_final_artifact_read_blocked',
    'system_fatal_count',
    'owner_relay_transport_protocols',
    'client_relay_transport_protocols',
    'owner_relay_control_tcp_media_carrier_lane_count',
    'client_relay_control_tcp_media_carrier_lane_count',
    'owner_receive_proxy_control_tcp_media_carrier_lane_count',
    'client_receive_proxy_control_tcp_media_carrier_lane_count',
    'owner_relay_all_lanes_use_control_tcp_media_carrier',
    'client_receive_proxy_all_lanes_use_control_tcp_media_carrier',
    'owner_broker_receiver_observed_bytes_fresh',
    'client_broker_receiver_observed_bytes_fresh',
    'owner_broker_receiver_observed_passed',
    'client_broker_receiver_observed_passed',
    'qcl082_media_topology_acceptance',
    'qcl082_media_topology_accepted',
    'qcl082_media_topology_passed',
    'qcl082_media_topology_required_transport_topology',
    'qcl082_media_topology_modes',
    'qcl082_media_topology_accepted_modes',
    'qcl082_media_topology_control_tcp_media_carrier_path_count',
    'qcl082_media_topology_app_bound_udp_media_path_count',
    'qcl082_media_topology_local_p2p_udp_media_rejected_path_count',
    'qcl082_media_topology_unsupported_path_count',
    'qcl082_media_topology_first_issue',
    'qcl082_media_topology_issues',
    'Add-Qcl100ParityBlocker',
    'Set-Qcl100ParityBlockers',
    'New-Qcl100PreflightParityBlockers',
    'wifi_direct_p2p0_ipv4_preflight',
    'wifi_direct_candidate_route_preflight',
    'qcl041_matrix_gate',
    'owner_xr_launch_readiness',
    'client_xr_launch_readiness',
    'owner_xr_launch_not_ready',
    'client_xr_launch_not_ready',
    'readiness_only_no_media_launched',
    'owner_camera_source',
    'client_camera_source',
    'owner_qcl082_relay',
    'client_qcl082_relay',
    'owner_qcl082_receive_proxy',
    'client_qcl082_receive_proxy',
    'owner_broker_receiver_observed',
    'client_broker_receiver_observed',
    'qcl082_media_topology',
    'owner_native_renderer_stream',
    'client_native_renderer_stream',
    'owner_native_renderer_scorecard',
    'client_native_renderer_scorecard',
    'udp_network_binding_required',
    'qcl041_artifact_wait_seconds',
    'RequireRelayFreshness',
    'RequireReceiveProxyFreshness',
    'owner-final-qcl041',
    'client-final-qcl041',
    'Stop-Qcl100NativeRendererLogcatCapture',
    'Stop-Qcl100DeviceApps'
) "QCL-100 orchestration failure cleanup"

Assert-TextOrder `
    -Text $qcl100Invoke `
    -First '$ownerFinalStatusProbe = Invoke-LiveBridgeCommand "owner-final-status"' `
    -Second 'Read-Qcl041Artifact `' `
    -Label "QCL-100 final broker status before QCL041 artifact freshness wait"

Assert-ContainsTokens $qcl100Relay @(
    'Get-Qcl041ArtifactFreshnessWaitState',
    'Invoke-Qcl100Qcl041ArtifactFreshnessWaitSelfTest',
    'RequireRelayFreshness',
    'RequireReceiveProxyFreshness',
    'qcl041_artifact_qcl082_freshness_wait',
    'qcl082_relay_not_fresh',
    'qcl082_receive_proxy_not_fresh',
    'qcl100-qcl041-artifact-freshness-wait-self-test\.json'
) "QCL-100 QCL041 artifact freshness wait helper"

Assert-ContainsTokens $qcl100MatrixGate @(
    'rusty\.quest\.qcl100_qcl041_matrix_gate\.v1',
    'rusty\.quest\.qcl100_qcl041_matrix_gate_self_test\.v1',
    'Get-Qcl100Qcl041MatrixGateEvidence',
    'Qcl082TransportProtocol',
    'required_qcl100_media_topology',
    'qcl100_media_topology_supported_by_gate',
    'accepted_udp_matrix_modes',
    'accepted_tcp_matrix_modes',
    'qcl041_matrix_summary_path_missing',
    'qcl041_matrix_summary_missing',
    'qcl041_matrix_status_not_pass',
    'qcl041_matrix_not_launched',
    'qcl041_matrix_missing_infrastructure_wifi_gate',
    'qcl041_matrix_missing_p2p0_clear_gate',
    'qcl041_matrix_missing_candidate_route_clear_gate',
    'qcl041_matrix_missing_tcp_tunnel_stream_gate',
    'qcl041_matrix_owner_serial_missing',
    'qcl041_matrix_owner_serial_mismatch',
    'qcl041_matrix_client_serial_missing',
    'qcl041_matrix_client_serial_mismatch',
    'qcl041_matrix_run_id_missing',
    'qcl041_matrix_run_id_mismatch',
    'qcl041_matrix_summary_stale',
    'qcl041_matrix_client_to_owner_udp_mode_absent',
    'qcl041_matrix_control_tcp_stream_mode_absent',
    'qcl041_matrix_qcl100_transport_not_supported',
    'expected_run_id',
    'expected_owner_serial',
    'expected_client_serial',
    'owner_serial',
    'client_serial',
    'matrix_focus',
    'qcl100_control_tcp_gate',
    'delayed_udp_required',
    'whole_matrix_completion_required',
    'requested_delayed_udp_delay_seconds',
    'delayed_udp_delay_seconds',
    'tcp_tunnel_stream_bytes_per_direction',
    'matrix_tcp_tunnel_stream_configured_bytes_per_direction',
    'matrix_tcp_tunnel_stream_required_bytes_per_direction',
    'artifact_last_write_utc',
    'artifact_age_seconds',
    'artifact_age_limit_seconds',
    'artifact_fresh_enough',
    'RequireFresh',
    'qcl041_matrix_receiver_observed_bytes_absent',
    'qcl041_matrix_tcp_tunnel_stream_not_bidirectional',
    'owner_matrix_complete',
    'client_matrix_complete',
    'owner_matrix_last_checkpoint',
    'client_matrix_last_checkpoint',
    'receiver_observed_bytes',
    'tcp_tunnel_stream_bidirectional_bytes_pass',
    'receiver_observed_udp_modes',
    'receiver_observed_tcp_modes',
    'matrix_app_bound_udp_mode_present',
    'matrix_client_to_owner_udp_evidence_scope',
    'matrix_client_to_owner_wifi_direct_udp_matrix_mode_present',
    'matrix_client_to_owner_wifi_direct_udp_receiver_observed_modes',
    'matrix_client_to_owner_app_bound_udp_socket_pass',
    'matrix_client_to_owner_app_bound_udp_receiver_observed_modes',
    'matrix_same_group_udp_duplex_media_proven_by_matrix',
    'matrix_same_group_udp_duplex_media_proof_required',
    'matrix_control_tcp_stream_mode_present',
    'missing_run_id_case',
    'wrong_run_id_case',
    'missing_run_id_summary_path',
    'wrong_run_id_summary_path',
    'wrong_client_case',
    'stale_case',
    'udp_missing_case',
    'control_tcp_case',
    'control_tcp_gate_incomplete_matrix_case',
    'control_tcp_gate_incomplete_matrix_summary_path',
    'unsupported_transport_case',
    'qcl100-qcl041-matrix-gate-self-test\.json'
) "QCL-100 QCL041 matrix gate"

Assert-ContainsTokens $qcl100ParityBlockers @(
    'Add-Qcl100ParityBlocker',
    'Set-Qcl100ParityBlockers',
    'New-Qcl100PreflightParityBlockers',
    'Invoke-Qcl100ParityBlockerSelfTest',
    'rusty\.quest\.qcl100_parity_blocker_self_test\.v1',
    'qcl100_airgap_preflight',
    'infrastructure_wifi_airgap',
    'wifi_direct_p2p0_ipv4_preflight',
    'wifi_direct_candidate_route_preflight',
    'client-stale-p2p0',
    'first_parity_blocker',
    'parity_blocker_count',
    'parity_blockers'
) "QCL-100 parity blocker helper"

Assert-ContainsTokens $qcl100Common @(
    'New-Qcl100AirgapPreflight',
    'rusty\.quest\.qcl100_infrastructure_wifi_airgap_preflight\.v1',
    'Get-Qcl100RouteSnapshot',
    'shell_routes',
    'owner_to_owner_wifi_direct_address',
    'client_to_client_wifi_direct_address',
    'candidate_wifi_direct_routes_using_wlan0',
    'candidate_wifi_direct_routes_using_p2p0',
    'candidate_wifi_direct_routes_using_loopback',
    'candidate_wifi_direct_local_self_routes',
    'candidate_wifi_direct_routes_unreachable',
    'candidate_wifi_direct_routes_reachable',
    'candidate_wifi_direct_prelaunch_routes_clear',
    'ip route get',
    'target_address',
    'route_device',
    'route_source',
    'uses_p2p0',
    'uses_wlan0',
    'uses_loopback',
    'local_self_route',
    'Network is unreachable'
) "QCL-100 passive route preflight"

Assert-ContainsTokens $qcl100Relay @(
    'rusty\.quest\.qcl100_qcl041_preclear_receipt\.v1',
    'qcl041_preclear_only',
    'qcl041_preclear_stale_group',
    'final_force_stop_attempted',
    'qcl041_artifact_wait_timeout',
    'artifact_mid_hold_or_final_wait',
    'ConvertFrom-Json',
    'Start-Sleep -Milliseconds 500',
    'qcl041\.qcl082_control_tcp_media_stream_bytes_per_direction',
    'qcl041\.qcl082_control_tcp_media_stream_chunk_bytes',
    'qcl041\.qcl082_udp_receive_proxy_require_wifi_direct_network_binding'
) "QCL-100 QCL041 artifact wait"

Assert-ContainsTokens $qcl100Freshness @(
    'final-window native renderer camera-projection scorecards',
    'Test-Qcl100RemoteBrokerProjectionScorecardLine',
    'source_authority_required',
    'manifold-broker-rmanvid1-camera2-h264',
    'camera_id_required_prefix',
    'remote-broker-',
    'metadata-target-remote-broker-camera2-h264',
    'cameraProjectionPath=\*remote-broker',
    'active_lane_ahb_frames_ready',
    'active_lane_projection_imports_ready',
    'system_fatal_count',
    'nativePackagePattern',
    'fresh-frames-system-fatal-blocks-projection',
    'fresh-frames-missing-rmanvid1-scorecard-authority',
    'ExpectedScorecardFresh',
    'scorecard_fresh_frames'
) "QCL-100 native renderer final-window scorecard gate"

Assert-ContainsTokens $qcl100RuntimeSummary @(
    'Invoke-Qcl100RuntimeSummarySelfTest',
    'Assert-Qcl100Qcl082CarrierFreshness',
    'New-Qcl100Qcl082TopologyPath',
    'Get-Qcl100Qcl082MediaTopologyAcceptance',
    'Assert-Qcl100Qcl082MediaTopologyAcceptance',
    'New-Qcl100TransportClaims',
    'Assert-Qcl100TransportClaims',
    'Get-BrokerReceiverObservedFreshness',
    'Assert-Qcl100BrokerReceiverObservedFreshness',
    'rusty\.quest\.qcl100_runtime_summary_self_test\.v1',
    'qcl100-runtime-summary-self-test\.json',
    'relay-control-tcp-carrier-fresh',
    'receive-proxy-control-tcp-carrier-fresh',
    'relay-control-tcp-carrier-stale-left-byte',
    'receive-proxy-udp-app-bound-socket-fresh',
    'topology-control-tcp-carrier-accepted',
    'topology-app-bound-udp-accepted',
    'topology-local-p2p-udp-rejected',
    'receiver-observed-broker-bytes-fresh',
    'receiver-observed-broker-bytes-stale-left-read',
    'qcl082_media_topology_not_app_bound_udp_or_control_tcp',
    'required_transport_topology',
    'app_bound_udp_media_lanes_or_justified_control_tcp_media_carrier',
    'justified_control_tcp_media_carrier',
    'app_bound_udp_media_lanes',
    'local_p2p_udp_media_bind_rejected',
    'same_group_app_bound_udp_duplex_claimed',
    'justified_alternate_topology_claimed',
    'same_group_duplex_proven_with_justified_control_tcp_alternate',
    'same_group_app_bound_udp_duplex_proven',
    'same_group_duplex_topology_not_accepted',
    'active_direction_stream_render_proven',
    'transport-claims-control-tcp-duplex-justified-alternate',
    'transport-claims-app-bound-udp-duplex',
    'transport-claims-unaccepted-topology-does-not-claim-duplex',
    'transport-claims-one-way-does-not-claim-duplex',
    'transport-claims-blocked-does-not-claim-duplex',
    'qcl082_media_topology_accepted',
    'udp_media_lanes_missing_app_bound_binding',
    'control_tcp_media_carrier_path_count',
    'app_bound_udp_media_path_count',
    'local_p2p_udp_media_rejected_path_count',
    'unsupported_media_topology_path_count',
    'first_issue',
    'fresh_receiver_observed_bytes',
    'transport_protocol',
    'uses_control_tcp_media_carrier',
    'frames_sent',
    'frames_received',
    'transport_protocols',
    'control_tcp_media_carrier_lane_count',
    'all_lanes_use_control_tcp_media_carrier'
) "QCL-100 QCL082 runtime summary carrier provenance"

Assert-ContainsTokens $lifecycleSurface @(
    'PackageManager\.FEATURE_WIFI_DIRECT',
    'isP2pSupported',
    'WifiP2pManager',
    'initialize',
    'WIFI_P2P_STATE_CHANGED_ACTION',
    'WIFI_P2P_PEERS_CHANGED_ACTION',
    'WIFI_P2P_CONNECTION_CHANGED_ACTION',
    'WIFI_P2P_THIS_DEVICE_CHANGED_ACTION',
    'discoverPeers',
    'requestPeers',
    'connect',
    'groupOwnerIntent',
    'WifiP2pConfig\.Builder',
    'setNetworkName',
    'setPassphrase',
    'enablePersistentMode\(false\)',
    'NETWORK_ID_TEMPORARY',
    'buildQuestGroupOwnerConfig',
    'buildQuestPeerConfig',
    'recordWifiP2pGroupDiagnostics',
    'requestConnectionInfo',
    'requestGroupInfo',
    'groupOwnerAddress',
    'isGroupOwner',
    'Quest became group owner',
    'ConnectivityManager',
    'getAllNetworks',
    'NetworkCapabilities',
    'NetworkInterface',
    'bindSocket',
    'socket_bound_to_wifi_direct_local_address',
    'socket_bound_to_wifi_direct_network',
    'bindProcessToNetwork',
    'Qcl081LslNativeBridge',
    'qcl081_lsl_echo',
    'qcl082_relay',
    'qcl082_receive_proxy',
    'qcl082_relay_',
    'qcl082_receive_proxy_',
    'Qcl082RelayLane',
    'Qcl082ReceiveProxyLane',
    'qcl082RelayLanes',
    'qcl082ReceiveProxyLanes',
    'relayLaneSummary',
    'receiveProxyLaneSummary',
    'group_owner_wifi_direct_local_address_without_connectivity_network',
    'wildcard_for_group_owner_udp_without_connectivity_network',
    'resolveQcl082GroupOwnerRelayReceiverHost',
    'findQcl082P2pPeerAddressFromArp',
    'announceQcl082PeerAddress',
    'waitForQcl082PeerAddressAnnouncement',
    'QCL082_PEER_ADDRESS',
    'QCL082_P2P_FANOUT_PREFIX',
    'QCL082_UDP_PEER_HELLO',
    'QCL082_UDP_PEER_ACK',
    'qcl082UdpReceiverAddresses',
    'waitForQcl082UdpPeerProof',
    'sendQcl082UdpPeerProofHelloIfNeeded',
    'udp_peer_proof_source_address',
    'udp_peer_proof_source_port',
    'udp_peer_proof_tx_role',
    'target_matches_udp_peer_proof',
    'effective_receiver_bind_address',
    'udp_last_sender_source_address',
    'udp_receiver_fanout_enabled',
    'udp_source_packets',
    'qcl082_peer_address',
    'qcl082_peer_address_announcement',
    'dynamic_receiver_host',
    'proc_net_arp_p2p0',
    'lane_count',
    'pollPeerDiscoveryUntilConnectStarts',
    'peer_discovery_poll_count',
    'initial_stale_group_preclear',
    'removeStaleQuestGroupBeforeInitialCreate',
    'q2qPreclearOnly',
    'removeStaleQuestGroupOnlyAndFinish',
    'preclear_only_remove_group',
    'removeStaleQuestGroupBeforeCreateRetry',
    'createGroup_busy_retry_removeGroup',
    'createGroup_retry_failure_treated_as_existing_group_candidate',
    'createGroup_busy_treated_as_existing_group_candidate',
    'createGroup_config_source',
    'credentialed_temporary_config',
    'temporary_network_id',
    'persistent_network_id',
    'group_owner_client_wait',
    'group_owner_peer_connect_suppressed',
    'copyMediaBytes',
    'copyReceiveProxyBytes',
    'shouldRecycleQcl082RelaySegment',
    'shouldRecycleQcl082ReceiveProxySegment',
    'if \(total > 0L\)',
    'createQcl082ReceiverSocket',
    'createQcl082ReceiveProxyServerSocket',
    'acceptReceiveProxyPeerWithRetry',
    'connectReceiveProxyTargetWithRetry',
    'receiver_socket_created_from_wifi_direct_network", true',
    'receiver_socket_bound_to_wifi_direct_network", true',
    'ReceiverSocketCandidate',
    'receiver_socket_network_factory_fallback',
    'local_address_bind',
    'receiver_socket_local_address_bind_skipped',
    'receiver_socket_local_address_bind_fallback',
    'receiver_connected_before_source',
    'source_connected_after_receiver',
    'source\.setSoTimeout\(1000\)',
    'SocketTimeoutException',
    'publishQcl082RelayProgress',
    'copy_last_byte_age_ms',
    'copy_bytes_read_from_source',
    'copy_bytes_written_to_receiver',
    'copy_bytes_read_from_peer',
    'copy_bytes_written_to_target',
    'ack_pacing_enabled',
    'ack_receives',
    'ack_sends',
    'ack_timeouts',
    'consecutiveAckTimeouts',
    'ack_soft_timeout_continues',
    'copy_segments',
    'receiver_reconnects',
    'receive_proxy_accepted_peers',
    'receive_proxy_peer_reconnects',
    'qcl082CopyReadLimit',
    'waitForQcl082AckIfNeeded',
    'sendQcl082AckIfNeeded',
    'copy_last_read_age_ms',
    'copy_last_write_age_ms',
    'noteWriteStarted',
    'writeInFlight',
    'startQcl082RelayWriteStallWatchdog',
    'startQcl082RelayReceiverProgressWatchdog',
    'receiver_write_stall_timeout',
    'receiver_progress_timeout',
    'sendQcl082ReceiverProgressIfNeeded',
    'qcl082RotatedPort',
    'runQcl082UdpMediaRelay',
    'runQcl082UdpReceiveProxy',
    'qcl082UdpMediaRelayRequiresWifiDirectNetworkBinding',
    'qcl082UdpReceiveProxyAllowsNetworkBinding',
    'qcl082UdpReceiveProxyRequiresNetworkBinding',
    'udp_sender_wifi_direct_network_binding_required',
    'udp_receive_proxy_wifi_direct_network_binding_required',
    'udp_receive_proxy_wifi_direct_network_binding_skipped',
    'udp_receive_proxy_wifi_direct_network_binding_mode',
    'socket_level_network_bind_with_local_p2p_fallback',
    'required_socket_level_network_bind',
    'findUsableWifiDirectNetwork',
    'relay_udp_required_usable_network_',
    'receive_proxy_udp_required_usable_network_',
    'receive_proxy_udp_required_binding_mode',
    'network_bound_listen_socket',
    'selected_nonvalidated_fallback',
    'selected_validated',
    'partial_connectivity',
    'relay_udp_required_binding_mode',
    'network_bound_auto_bind_source',
    'auto_bind_on_first_send',
    'udp_peer_proof_last_local_socket',
    'udp_peer_proof_last_send_target',
    'udp_socket_recreate_count',
    'udp_socket_recreate_reason',
    'relay_udp_recreate_',
    'shouldRecycleQcl082UdpSendSocket',
    'network is unreachable',
    'tcp_peer_proof_warmup_disabled_reason',
    'tcp_peer_proof_warmup_server_disabled_reason',
    'QCL082_TCP_PEER_HELLO',
    'QCL082_TCP_PEER_ACK',
    'sendQcl082TcpPeerProofWarmup',
    'startQcl082TcpPeerProofWarmupServer',
    'tcp_peer_proof_warmup_enabled',
    'tcp_peer_proof_warmup_server_enabled',
    'tcp_peer_proof_warmup_ack_received',
    'tcp_peer_proof_warmup_ack_sent',
    'QCL082_CONTROL_KEEPALIVE',
    'QCL082_CONTROL_KEEPALIVE_ACK',
    'QCL082_CONTROL_MEDIA_STREAM',
    'QCL082_CONTROL_MEDIA_STREAM_ACK',
    'Qcl082ControlTcpMediaCarrier',
    'TRANSPORT_PROTOCOL',
    'control-tcp',
    'QCL082_CONTROL_TCP_MEDIA_CARRIER',
    'QCL082_CONTROL_TCP_MEDIA_CARRIER_ACK',
    'QCL082_CONTROL_TCP_MEDIA_CARRIER_READY',
    'handled_by_control_tcp_media_carrier',
    'qcl082ControlTcpMediaCarrierEnabled',
    'qcl082RelayTransportProtocolControlTcp',
    'qcl082ReceiveProxyTransportProtocolControlTcp',
    'runQcl082ControlTcpMediaKeepalive',
    'runQcl082ControlTcpMediaStream',
    'qcl082ControlTcpMediaStreamBytesPerDirection',
    'qcl082ControlTcpMediaKeepaliveHoldMs',
    'media_carrier_enabled',
    'media_carrier_protocol',
    'media_carrier_completed',
    'PROGRESS_PUBLISH_INTERVAL_MS',
    'publishRelayProgressIfDue',
    'publishRelayProgress',
    'progress_publish_interval_ms',
    'frames_sent',
    'frames_received',
    'readControlLine',
    'writeControlLine',
    'qcl082UdpPeerProofAckAllowedForReceiveProxy',
    'media_keepalive_enabled',
    'media_keepalive_hold_ms',
    'media_keepalive_sent',
    'media_keepalive_received',
    'media_stream_enabled',
    'media_stream_bidirectional_observed',
    'media_stream_client_to_owner_bytes',
    'media_stream_owner_to_client_bytes',
    'ack_not_required_for_go_to_client_probe',
    'QCL-082 UDP media relay requires route-matched non-partial Wi-Fi Direct Network',
    'udp_initial_sequence_resync',
    'udp_initial_sequence_missing_count',
    'udp_sequence_resync_count',
    'udp_next_expected_sequence',
    'udp_received_datagrams',
    'udp_peer_proof_ack_required',
    'udp_peer_proof_media_start_gate',
    'udp_peer_proof_tx_send_errors',
    'udp_peer_proof_last_send_error',
    'udp_peer_proof_pre_target_wait_enabled',
    'udp_peer_proof_pre_target_received',
    'QCL-082 UDP peer-proof ACK not received before media source connect',
    'wifi_direct_network_binding_allowed',
    'socket_role_uses_local_p2p_bind',
    'skipped_for_required_socket_level_binding',
    'wifi_direct_network_binding_required',
    'required Wi-Fi Direct datagram socket binding failed',
    'Wi-Fi Direct Network required for QCL-082 UDP datagram socket',
    'runQcl082ReverseTcpSourceExport',
    'runQcl082ReverseTcpReceiveProxy',
    'reverse-tcp-recycling',
    'reverse-tcp-reconnecting-peer',
    'DatagramSocket',
    'QCL082_UDP_MAGIC',
    'qcl082RelayTransportProtocolUdp',
    'qcl082ReceiveProxyTransportProtocolUdp',
    'active_listen_port',
    'receiver_active_port',
    'closeSocketForQcl082Recycle',
    'write-stall-timeout',
    'write_stall_socket_closes',
    'noteRead',
    'noteWrite',
    'copy_completed_reason',
    'peer_idle_timeout',
    'peer_read_error_after_bytes',
    'receiver_write_error_after_bytes',
    'target_write_error_after_bytes',
    'copy_current_elapsed_ms',
    'relay_thread_started',
    'relay_thread_start_delay_ms',
    'Qcl041AppBoundSocketMatrix',
    'Qcl041NativeSocketProbe',
    'q2q_app_bound_socket_matrix',
    'receiver_observed_bytes_on_group_owner',
    'runs_after_bounded_tcp_failure',
    'after_bounded_tcp_timeout',
    'tcp_tunnel_control_socket',
    'tcp_tunnel_stream_socket',
    'TCP_TUNNEL_BYTES_PER_DIRECTION',
    'TCP_TUNNEL_STREAM_CHUNK_BYTES',
    'runTcpTunnelReceiver',
    'runTcpTunnelClient',
    'runTcpTunnelStreamReceiver',
    'runTcpTunnelStreamClient',
    'checkpoint',
    'last_checkpoint',
    'client_sender_completed',
    'group_owner_receiver_completed',
    'client_after_tcp_tunnel_stream',
    'startTcpTunnelStreamWatchdog',
    'stall_watchdog_closed_socket',
    'noteTcpTunnelStreamProgress',
    '_progress_bytes',
    '_progress_frames',
    'client_to_owner_rx_bytes',
    'owner_to_client_rx_bytes',
    'bidirectional_client_observed',
    'udp_source_and_network_bound',
    'udp_native_fd_network_bound',
    'udp_process_bound',
    'early_bound_delayed_udp_network_bound',
    'early_bound_delayed_udp_source_and_network_bound',
    'network_bound_before_delay',
    'prepared_before_delay',
    'runDelayedUdpSendModesWithTimeout',
    'delayed_udp_thread_timeout_ms',
    'delayed_udp_thread_alive_after_join',
    'client_delayed_udp_timeout',
    'delayed_udp_network_bound',
    'delayed_udp_source_and_network_bound',
    'delayed_udp_native_fd_network_bound',
    'delayed_udp_process_bound',
    'recordNetworkVisibility\("delayed_udp_pre_send"\)',
    '_link_properties_found',
    'udp_receive_window_ms',
    'tcp_network_bind_socket',
    'tcp_network_factory',
    'tcp_native_fd_network_bound',
    'tcp_process_bound',
    'native_fd_android_setsocknetwork',
    'process_bind_experiment_enabled',
    'getBoundNetworkForProcess',
    'process_bind_restored',
    'control_tcp',
    'local_socket_after_connect',
    'accepted_peer_port',
    'recordConnectivitySnapshot',
    'NetworkRequest',
    'registerNetworkCallback',
    'recordWifiP2pNetworkRequestVisibility',
    'recordWifiP2pNetworkRequestVisibility\("initial"\)',
    '_wifi_p2p_request_',
    'callback_observed',
    'matches_selected_network',
    'NET_CAPABILITY_WIFI_P2P',
    'preferred_network_available',
    'selected_from_preferred',
    'selected_missing_link_properties_fallback',
    'accepted_without_current_link_properties',
    'inspectUsableWifiDirectNetworkCandidate',
    'findWifiDirectNetworkOnce',
    'wifi_direct_network_wait_attempts',
    'wifi_direct_network_wait_elapsed_ms',
    'receiver_connected_local_address',
    'receiver_last_connect_error',
    'source_last_connect_error',
    'receiver connected from non Wi-Fi Direct local address',
    'qcl041_wifi_direct_harness',
    'qcl081_lsl',
    'Socket',
    'bounded TCP',
    'stopPeerDiscovery',
    'removeGroup'
) "WifiP2pManager lifecycle"

Assert-TextOrder `
    -Text $lifecycle `
    -First "receiver = connectReceiverWithRetry(" `
    -Second "source = connectSourceWithRetry(deadline," `
    -Label "QCL-082 relay receiver-first sequencing"

Assert-ContainsTokens $artifact @(
    '"QCL-041"',
    '"windows"',
    '"live_wifi_direct_lifecycle"',
    '"wifi_direct"',
    '"peer_to_peer_group"',
    '"windows_wifi_direct_api"',
    '"permission_state"',
    '"peer_discovery"',
    '"group_formation"',
    '"socket_exchange"',
    '"bounded_tcp_probe"',
    '"cleanup"',
    '"Agent Board"',
    'released_after_live_steps',
    'diagnostics'
) "lifecycle source artifact"

Assert-ContainsTokens $config @(
    'rusty\.quest\.connectivity_wifi_direct_lifecycle\.v1',
    'rusty-quest-wifi-direct-qcl041-android-harness',
    'quest_windows_wifi_direct_lifecycle',
    'qcl041\.lease_id',
    'qcl041\.lease_resource',
    'qcl041\.windows_api_observed',
    'qcl041\.windows_peer_name_contains',
    'qcl041\.group_owner_intent',
    'qcl041\.allow_quest_group_owner',
    'qcl041\.q2q_preclear_stale_group',
    'qcl041\.q2q_preclear_only',
    'qcl041\.q2q_network_name',
    'qcl041\.q2q_passphrase',
    'DEFAULT_Q2Q_NETWORK_NAME',
    'DEFAULT_Q2Q_PASSPHRASE',
    'qcl041\.listen_port',
    'qcl041\.qcl081_lsl_enabled',
    'qcl041\.qcl081_lsl_stream_name',
    'qcl041\.qcl081_lsl_source_id',
    'qcl041\.qcl081_lsl_echo_enabled',
    'qcl041\.qcl081_lsl_echo_command_source_id',
    'qcl041\.qcl081_lsl_echo_source_id',
    'qcl041\.qcl082_relay_enabled',
    'qcl041\.q2q_app_bound_socket_matrix_enabled',
    'qcl041\.q2q_app_bound_socket_matrix_port',
    'qcl041\.q2q_app_bound_socket_matrix_tcp_tunnel_stream_seconds',
    'qcl041\.q2q_app_bound_socket_matrix_tcp_tunnel_stream_bytes_per_direction',
    'quest_local_only_hotspot_probe',
    'qcl041\.qcl030_local_only_hotspot_enabled',
    'qcl041\.qcl030_local_only_hotspot_role',
    'qcl041\.qcl030_local_only_hotspot_hold_ms',
    'qcl041\.qcl030_local_only_hotspot_port',
    'qcl041\.qcl030_local_only_hotspot_ssid',
    'qcl041\.qcl030_local_only_hotspot_passphrase',
    'qcl041\.qcl030_local_only_hotspot_owner_host',
    'qcl041\.qcl030_local_only_hotspot_socket_bytes',
    'qcl041\.qcl030_local_only_hotspot_socket_timeout_ms',
    'qcl041\.qcl030_local_only_hotspot_client_join_mode',
    'qcl041\.qcl030_local_only_hotspot_require_ssid_match',
    'qcl041\.qcl082_relay_source_host',
    'qcl041\.qcl082_relay_receiver_host',
    'qcl041\.qcl082_relay_lanes',
    'qcl041\.qcl082_relay_start_delay_ms',
    'qcl041\.qcl082_relay_write_stall_timeout_ms',
    'qcl041\.qcl082_relay_receiver_progress_timeout_ms',
    'qcl041\.qcl082_relay_port_rotation_count',
    'qcl041\.qcl082_transport_protocol',
    'qcl041\.qcl082_ack_pacing_enabled',
    'qcl041\.qcl082_ack_chunk_bytes',
    'qcl041\.qcl082_ack_timeout_ms',
    'qcl041\.qcl082_ack_soft_timeout_limit',
    'qcl041\.qcl082_control_tcp_media_stream_bytes_per_direction',
    'qcl041\.qcl082_control_tcp_media_stream_chunk_bytes',
    'qcl041\.qcl082_receive_proxy_enabled',
    'qcl041\.qcl082_receive_proxy_lanes',
    'qcl041\.qcl082_receive_proxy_target_port',
    'qcl041\.qcl082_receive_proxy_peer_idle_timeout_ms',
    'qcl041\.qcl082_udp_receive_proxy_require_wifi_direct_network_binding',
    'product_harness',
    'RMANVID1'
) "intent config"

Assert-ContainsTokens $qcl030LocalOnlyHotspotProbe @(
    'rusty\.quest\.qcl030\.local_only_hotspot_probe\.v1',
    'QCL-030',
    'startLocalOnlyHotspot',
    'LocalOnlyHotspotReservation',
    'WifiNetworkSpecifier',
    'requestNetwork',
    'NetworkCallback',
    'QCL030_CLIENT_JOIN_MODE_ACTIVE_WIFI',
    'getActiveNetwork',
    'active_wifi_socket_matrix',
    'client_active_network_not_wifi',
    'client_active_wifi_ssid_present',
    'client_active_wifi_ssid_match_status',
    'normalizeSsid',
    'WifiInfo',
    'TRANSPORT_WIFI',
    'network\.bindSocket',
    'DatagramSocket',
    'ServerSocket',
    'hotspot_client',
    'getWifiConfiguration',
    'getSoftApConfiguration',
    'credential_sensitive',
    'quest_local_only_hotspot',
    'receiver_observed_bytes_required_before_media',
    'receiver_observed_bytes',
    'client_network_available',
    'client_udp_sent_bytes',
    'client_tcp_sent_bytes',
    'client_join_and_socket_matrix_pending',
    'qcl030',
    'hotspot_started_and_reservation_closed_cleanly',
    'ERROR_NO_CHANNEL',
    'ERROR_INCOMPATIBLE_MODE',
    'ERROR_TETHERING_DISALLOWED'
) "QCL-030 LocalOnlyHotspot Android probe"

Assert-ContainsTokens $qcl030Invoke @(
    'rusty\.quest\.qcl030_local_only_hotspot_probe_run\.v1',
    'rusty\.quest\.qcl030_android_permission_preflight\.v1',
    'PreflightOnly',
    'SkipInstall',
    'RunClientJoinMatrix',
    'OwnerSerial',
    'ClientSerial',
    'LaunchClientViaActivity',
    'Qcl041Activity',
    'client_launch_surface',
    'foreground_activity',
    'clientLaunchCommand',
    'clientLaunchComponent',
    'AutoApproveClientNetworkRequest',
    'uiautomator',
    'NetworkRequestDialogActivity',
    'dumpsys",\s*"package"',
    'grant_state_found',
    'pm",\s*"grant"',
    'permission_ready',
    'qcl030-permission-preflight\.json',
    'cmd",\s*"wifi",\s*"status"',
    'pm",\s*"list",\s*"features"',
    'start-foreground-service',
    'run-as',
    'files/qcl030',
    'qcl041\.qcl030_local_only_hotspot_enabled',
    'qcl041\.qcl030_local_only_hotspot_hold_ms',
    'qcl041\.qcl030_local_only_hotspot_port',
    'qcl041\.qcl030_local_only_hotspot_ssid',
    'qcl041\.qcl030_local_only_hotspot_passphrase',
    'qcl041\.qcl030_local_only_hotspot_owner_host',
    'qcl041\.qcl030_local_only_hotspot_socket_bytes',
    'qcl041\.qcl030_local_only_hotspot_socket_timeout_ms',
    'qcl041\.qcl030_local_only_hotspot_client_join_mode',
    'qcl041\.qcl030_local_only_hotspot_require_ssid_match',
    'quest_local_only_hotspot',
    'receiver_observed_bytes_required_before_media',
    'owner_receiver_observed_bytes',
    'client_join_matrix',
    'ClientJoinMode',
    'RequireActiveWifiSsidMatch',
    'HostJoinClientWithWifiSuggestion',
    'HostJoinWaitSeconds',
    'cmd",\s*"wifi",\s*"add-suggestion"',
    'cmd",\s*"wifi",\s*"remove-suggestion"',
    'network-suggestions-set-user-approved',
    'client_wifi_suggestion_join',
    'connected_to_target_ssid',
    'client_join_mode',
    'require_active_wifi_ssid_match',
    'active_wifi',
    'network_specifier',
    'credential_sensitive_redacted',
    'client_join_and_socket_matrix_pending',
    'credential_sensitive'
) "QCL-030 LocalOnlyHotspot wrapper"

Assert-ContainsTokens $lslBridge @(
    'System\.loadLibrary\("lsl"\)',
    'System\.loadLibrary\("qcl081_lsl_outlet_bridge"\)',
    'nativePublishSamples',
    'nativeEchoRoundTrip',
    'source_timestamps_monotonic'
) "QCL-081 Java native bridge"

Assert-ContainsTokens $nativeBridge @(
    'lsl_create_streaminfo',
    'lsl_create_outlet',
    'lsl_create_inlet',
    'lsl_resolve_byprop',
    'lsl_time_correction',
    'lsl_pull_sample_d',
    'lsl_local_clock',
    'lsl_push_sample_ftp',
    'lsl_push_sample_dtp',
    'Quest-owned liblsl outlet'
) "QCL-081 native liblsl outlet bridge"

Assert-ContainsTokens $nativeHeader @(
    'lsl_streaminfo',
    'lsl_outlet',
    'lsl_inlet',
    'cft_float32',
    'lsl_push_sample_ftp',
    'lsl_pull_sample_d'
) "QCL-081 liblsl C API header"

Assert-ContainsTokens $nativeSocketProbeBridge @(
    'System\.loadLibrary\("qcl041_socket_probe"\)',
    'native fd android_setsocknetwork',
    'nativeSendUdp',
    'nativeConnectTcp',
    'qcl041_native_socket_probe_unavailable'
) "QCL-041 Java native socket probe bridge"

Assert-ContainsTokens $nativeSocketProbe @(
    'android_setsocknetwork',
    'udp_native_fd_network_bound',
    'tcp_native_fd_network_bound',
    'rusty\.quest\.qcl041_native_socket_probe\.v1',
    'qcl041_socket_probe/native_fd_android_setsocknetwork/v1'
) "QCL-041 native fd socket probe"

Assert-ContainsTokens $buildText @(
    'qcl041-wifi-direct-harness-android',
    'javac',
    'd8\.bat',
    'aapt2',
    'aarch64-linux-android29-clang\+\+\.cmd',
    'aarch64-linux-android29-clang\.cmd',
    'qcl041_socket_probe\.c',
    'libqcl041_socket_probe\.so',
    '-landroid',
    'qcl041_socket_probe_native_packaged',
    'libqcl081_lsl_outlet_bridge\.so',
    'qcl081_lsl_native_packaged',
    '--target-sdk-version", "34"',
    'rusty\.quest\.qcl041_wifi_direct_harness_android\.build_manifest\.v1',
    'live_evidence_synthesized = \$false'
) "manual Android build"

Assert-ContainsTokens $invoke @(
    'agent-board\.ps1',
    'reserve',
    'quest:\$Serial',
    'release',
    'adb',
    '-s',
    'dotnet',
    'qcl041_wifi_direct_peer_helper',
    'Windows Mobile Hotspot',
    'RunQcl081Lsl',
    'RunQcl081LslEcho',
    'Qcl081LslBackend',
    'Qcl081ReceiverBackend',
    'Qcl081EchoBackend',
    'qcl081_wifi_direct_lsl_receiver\.py',
    'qcl081_wifi_direct_lsl_echo_roundtrip\.py',
    'receiver_backend',
    'command_producer_backend',
    'qcl041\.qcl081_lsl_enabled',
    'qcl041\.qcl081_lsl_backend',
    'qcl041\.qcl081_lsl_echo_enabled',
    'released_after_live_steps',
    'connectivity-probe run --mode fixture --probe-id QCL-041'
) "live wrapper"

Assert-ContainsTokens $readme @(
    'no Android phone',
    'Quest headset',
    'Windows QCL-041 helper',
    'Hostess normalization',
    'official `liblsl`',
    'private planning notes'
) "app README"

$legacyTokens = @(
    ("RUSTY" + "_XR_"),
    ("rusty" + ".xr."),
    ("/rusty" + "xr/v1"),
    ("com.example." + "rustyxr"),
    ("Rusty" + "XR")
)
foreach ($token in $legacyTokens) {
    if ($combined.Contains($token)) {
        throw "QCL-041 Wi-Fi Direct harness contains legacy token: $token"
    }
}

if ($Build) {
    & (Join-Path $PSScriptRoot "Build-Qcl041WifiDirectHarnessAndroid.ps1") -AndroidHome $AndroidHome -JavaHome $JavaHome | Out-Host
}

Write-Output "Rusty Quest QCL-041 Wi-Fi Direct Android harness validation passed"
