[CmdletBinding()]
param([Parameter(Mandatory)][string]$AndroidHome,[Parameter(Mandatory)][string]$JavaHome,[Parameter(Mandatory)][string]$BuildLeaseId)
$ErrorActionPreference='Stop';if($PSVersionTable.PSVersion-lt[version]'7.6'){throw 'PowerShell 7.6 required'}
$source=$PSScriptRoot;$repo=(Resolve-Path(Join-Path $source '../../..')).Path;$platform=Join-Path $AndroidHome 'platforms/android-35/android.jar';$d8=Join-Path $AndroidHome 'build-tools/35.0.0/d8.bat';$javac=Join-Path $JavaHome 'bin/javac.exe';$jar=Join-Path $JavaHome 'bin/jar.exe'
$files=@('ProbeCore.java','BinderProtocol.java','LeaseShellRole.java')|ForEach-Object{Join-Path $source "src/io/github/mesmerprism/rustyquest/shellcapabilities/$_"};foreach($p in @($platform,$d8,$javac,$jar)+$files){if(-not(Test-Path $p)){throw "missing $p"}}
$identity=[ordered]@{schema='rusty.quest.shell_capabilities_shell_inputs.v1';main='io.github.mesmerprism.rustyquest.shellcapabilities.LeaseShellRole';sources=@($files|ForEach-Object{[ordered]@{name=(Split-Path $_ -Leaf);sha256=(Get-FileHash $_ -Algorithm SHA256).Hash.ToLowerInvariant()}})};$json=$identity|ConvertTo-Json -Depth 6 -Compress;$hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($json))).ToLowerInvariant();$out=Join-Path $repo "target/quest-shell-capabilities/shell/$hash";if(Test-Path $out){throw "immutable output exists $out"};New-Item -ItemType Directory $out,(Join-Path $out classes),(Join-Path $out dex)|Out-Null
function Run([string]$exe,[string[]]$arguments,[string]$log){$v=&$exe @arguments 2>&1;$c=$LASTEXITCODE;$v|Set-Content(Join-Path $out $log);if($c-ne0){$v|Write-Output;throw "$log failed $c"}}
Run $javac (@('-encoding','UTF-8','-source','8','-target','8','-cp',$platform,'-d',(Join-Path $out classes))+$files) javac.txt;Run $jar @('cf',(Join-Path $out classes.jar),'-C',(Join-Path $out classes),'.') jar.txt;Run $d8 @('--min-api','29','--lib',$platform,'--output',(Join-Path $out dex),(Join-Path $out classes.jar)) d8.txt
$dex=Join-Path $out 'shell-capabilities.dex';Move-Item(Join-Path $out dex/classes.dex)$dex;$result=[ordered]@{schema='rusty.quest.shell_capabilities_shell_build.v1';status='built_device_unverified';input_sha256=$hash;build_lease_id=$BuildLeaseId;main=$identity.main;artifact=$dex;sha256=(Get-FileHash $dex -Algorithm SHA256).Hash.ToLowerInvariant();bytes=(Get-Item $dex).Length;binder_cli='server|status|stop|negative-callback <token> <installed_app_uid> [ttl_ms]';provider_route='activity_manager_external'};[IO.File]::WriteAllText((Join-Path $out RESULT-SHELL.json),($result|ConvertTo-Json -Depth 6),[Text.UTF8Encoding]::new($false));$result|ConvertTo-Json -Depth 6
